



CREATE   VIEW [dbo].[V_FT_ALL] AS 

SELECT 
    'HSOLS_CH' AS BDADOS, FT.FTSTAMP, FI.FISTAMP, FT.NMDOC, FT.FNO, FDATA, FI.REF, FI.DESIGN, FI.QTT, FI.ETILIQUIDO * (1-(FT.FIN/100)) AS ETTILIQ, FT2.PROCESSO, FT.TIPODOC, SUBSTRING(FT2.PROCESSO,3,4) AS CCUSTO_GERAL,CAST(0 AS BIT) AS INSTRAGRUPO
FROM HSOLS_CH..FT (NOLOCK) 
JOIN HSOLS_CH..FI (NOLOCK) ON FI.FTSTAMP = FT.FTSTAMP
JOIN HSOLS_CH..FT2 (NOLOCK) ON FT2.FT2STAMP = FT.FTSTAMP
LEFT JOIN HSOLS_CH..CL ON CL.NO = FT.NO AND CL.ESTAB = 0 
WHERE FI.REF NOT IN ('RG','RFT') AND FT.TIPODOC IN (1,2,3)
AND FI.ETILIQUIDO <> 0
AND FT.ANULADO = 0

UNION ALL 

SELECT 
    'HSOLS_DE' AS BDADOS, FT.FTSTAMP, FI.FISTAMP, FT.NMDOC, FT.FNO, FDATA, FI.REF, FI.DESIGN, FI.QTT, FI.ETILIQUIDO * (1-(FT.FIN/100)) AS ETTILIQ, FT2.PROCESSO, FT.TIPODOC, SUBSTRING(FT2.PROCESSO,3,4) AS CCUSTO_GERAL,
	CASE WHEN CL.VENDNM = 'INTRAGRUPO' THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS INSTRAGRUPO
FROM HSOLS_DE..FT (NOLOCK) 
JOIN HSOLS_DE..FI (NOLOCK) ON FI.FTSTAMP = FT.FTSTAMP
JOIN HSOLS_DE..FT2 (NOLOCK) ON FT2.FT2STAMP = FT.FTSTAMP
LEFT JOIN HSOLS_DE..CL ON CL.NO = FT.NO AND CL.ESTAB = 0 
WHERE FI.REF NOT IN ('RG','RFT') AND FT.TIPODOC IN (1,2,3)
AND FI.ETILIQUIDO <> 0
AND FT.ANULADO = 0

UNION ALL 

SELECT 
    'HSOLS_ES' AS BDADOS, FT.FTSTAMP, FI.FISTAMP, FT.NMDOC, FT.FNO, FDATA, FI.REF, FI.DESIGN, FI.QTT, FI.ETILIQUIDO * (1-(FT.FIN/100)) AS ETTILIQ, FT2.PROCESSO, FT.TIPODOC, SUBSTRING(FT2.PROCESSO,3,4) AS CCUSTO_GERAL,
	CASE WHEN CL.VENDNM = 'INTRAGRUPO' THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS INSTRAGRUPO
FROM HSOLS_ES..FT (NOLOCK) 
JOIN HSOLS_ES..FI (NOLOCK) ON FI.FTSTAMP = FT.FTSTAMP
JOIN HSOLS_ES..FT2 (NOLOCK) ON FT2.FT2STAMP = FT.FTSTAMP
LEFT JOIN HSOLS_ES..CL ON CL.NO = FT.NO AND CL.ESTAB = 0 
WHERE FI.REF NOT IN ('RG','RFT') AND FT.TIPODOC IN (1,2,3)
AND FI.ETILIQUIDO <> 0
AND FT.ANULADO = 0

UNION ALL 

SELECT 
    'HSOLS_FR' AS BDADOS, FT.FTSTAMP, FI.FISTAMP, FT.NMDOC, FT.FNO, FDATA, FI.REF, FI.DESIGN, FI.QTT, FI.ETILIQUIDO * (1-(FT.FIN/100)) AS ETTILIQ, FT2.PROCESSO, FT.TIPODOC, SUBSTRING(FT2.PROCESSO,3,4) AS CCUSTO_GERAL,
	CASE WHEN CL.VENDNM = 'INTRAGRUPO' THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS INSTRAGRUPO
FROM HSOLS_FR..FT (NOLOCK) 
JOIN HSOLS_FR..FI (NOLOCK) ON FI.FTSTAMP = FT.FTSTAMP
JOIN HSOLS_FR..FT2 (NOLOCK) ON FT2.FT2STAMP = FT.FTSTAMP
LEFT JOIN HSOLS_FR..CL ON CL.NO = FT.NO AND CL.ESTAB = 0 
WHERE FI.REF NOT IN ('RG','RFT') AND 
FT.TIPODOC IN (1,2,3)
AND FI.ETILIQUIDO <> 0
AND FT.ANULADO = 0

UNION ALL 

SELECT 
    'HSOLS_G2S' AS BDADOS, FT.FTSTAMP, FI.FISTAMP, FT.NMDOC, FT.FNO, FDATA, FI.REF, FI.DESIGN, FI.QTT, FI.ETILIQUIDO * (1-(FT.FIN/100)) AS ETTILIQ, FT2.PROCESSO, FT.TIPODOC, SUBSTRING(FT2.PROCESSO,3,4) AS CCUSTO_GERAL,
	CASE WHEN CL.VENDNM = 'INTRAGROUP' THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS INSTRAGRUPO
FROM HSOLS_G2S..FT (NOLOCK) 
JOIN HSOLS_G2S..FI (NOLOCK) ON FI.FTSTAMP = FT.FTSTAMP
JOIN HSOLS_G2S..FT2 (NOLOCK) ON FT2.FT2STAMP = FT.FTSTAMP
LEFT JOIN HSOLS_G2S..CL ON CL.NO = FT.NO AND CL.ESTAB = 0 
WHERE FI.REF NOT IN ('RG','RFT') AND FT.TIPODOC IN (1,2,3)
AND FI.ETILIQUIDO <> 0
AND FT.ANULADO = 0

UNION ALL 

SELECT 
    'HSOLS_GRE' AS BDADOS, FT.FTSTAMP, FI.FISTAMP, FT.NMDOC, FT.FNO, FDATA, FI.REF, FI.DESIGN, FI.QTT, FI.ETILIQUIDO * (1-(FT.FIN/100)) AS ETTILIQ, FT2.PROCESSO, FT.TIPODOC, SUBSTRING(FT2.PROCESSO,3,4) AS CCUSTO_GERAL,
	CASE WHEN CL.VENDNM = 'INTRAGRUPO' THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS INSTRAGRUPO
FROM HSOLS_GRE..FT (NOLOCK) 
JOIN HSOLS_GRE..FI (NOLOCK) ON FI.FTSTAMP = FT.FTSTAMP
JOIN HSOLS_GRE..FT2 (NOLOCK) ON FT2.FT2STAMP = FT.FTSTAMP
LEFT JOIN HSOLS_GRE..CL ON CL.NO = FT.NO AND CL.ESTAB = 0 
WHERE FI.REF NOT IN ('RG','RFT') AND FT.TIPODOC IN (1,2,3)
AND FI.ETILIQUIDO <> 0
AND FT.ANULADO = 0

UNION ALL 

SELECT 
    'HSOLS_IND' AS BDADOS, FT.FTSTAMP, FI.FISTAMP, FT.NMDOC, FT.FNO, FDATA, FI.REF, FI.DESIGN, FI.QTT, FI.ETILIQUIDO * (1-(FT.FIN/100)) AS ETTILIQ, FT2.PROCESSO, FT.TIPODOC, SUBSTRING(FT2.PROCESSO,3,4) AS CCUSTO_GERAL,
	CASE WHEN CL.VENDNM = 'INTRAGRUPO' THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS INSTRAGRUPO
FROM HSOLS_IND..FT (NOLOCK) 
JOIN HSOLS_IND..FI (NOLOCK) ON FI.FTSTAMP = FT.FTSTAMP
JOIN HSOLS_IND..FT2 (NOLOCK) ON FT2.FT2STAMP = FT.FTSTAMP
LEFT JOIN HSOLS_IND..CL ON CL.NO = FT.NO AND CL.ESTAB = 0 
WHERE FI.REF NOT IN ('RG','RFT') AND FT.TIPODOC IN (1,2,3)
AND FI.ETILIQUIDO <> 0
AND FT.ANULADO = 0

UNION ALL 

SELECT 
    'HSOLS_MA' AS BDADOS, FT.FTSTAMP, FI.FISTAMP, FT.NMDOC, FT.FNO, FDATA, FI.REF, FI.DESIGN, FI.QTT, 
	FI.ETILIQUIDO * 
	CASE 
		WHEN FT.MOEDA = 'MAD' THEN ISNULL((SELECT TOP 1 Z.ECAMBIO2 FROM HSOLS_MA..CB AS Z (NOLOCK) WHERE Z.MOEDA = 'EUR' AND Z.DATA <= FT.FDATA ORDER BY Z.DATA DESC),1)
		ELSE 1 
	END
	* (1-(FT.FIN/100))
	AS ETTILIQ, 
	FT2.PROCESSO, FT.TIPODOC, SUBSTRING(FT2.PROCESSO,3,4) AS CCUSTO_GERAL,
	CASE WHEN CL.VENDNM = 'INTRAGRUPO' THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS INSTRAGRUPO
FROM HSOLS_MA..FT (NOLOCK) 
JOIN HSOLS_MA..FI (NOLOCK) ON FI.FTSTAMP = FT.FTSTAMP
JOIN HSOLS_MA..FT2 (NOLOCK) ON FT2.FT2STAMP = FT.FTSTAMP
LEFT JOIN HSOLS_MA..CL ON CL.NO = FT.NO AND CL.ESTAB = 0 
WHERE FI.REF NOT IN ('RG','RFT') AND FT.TIPODOC IN (1,2,3)
AND FI.ETILIQUIDO <> 0
AND FT.ANULADO = 0

UNION ALL 

SELECT 
    'INTERSOL' AS BDADOS, FT.FTSTAMP, FI.FISTAMP, FT.NMDOC, FT.FNO, FDATA, FI.REF, FI.DESIGN, FI.QTT, FI.ETILIQUIDO * (1-(FT.FIN/100)) AS ETTILIQ, FT2.PROCESSO, FT.TIPODOC, SUBSTRING(FT2.PROCESSO,3,4) AS CCUSTO_GERAL,
	CASE WHEN CL.VENDNM = 'INTRAGRUPO' THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS INSTRAGRUPO
FROM INTERSOL..FT (NOLOCK) 
JOIN INTERSOL..FI (NOLOCK) ON FI.FTSTAMP = FT.FTSTAMP
JOIN INTERSOL..FT2 (NOLOCK) ON FT2.FT2STAMP = FT.FTSTAMP
LEFT JOIN INTERSOL..CL ON CL.NO = FT.NO AND CL.ESTAB = 0 
WHERE FI.REF NOT IN ('RG','RFT') AND FT.TIPODOC IN (1,2,3)
AND FI.ETILIQUIDO <> 0
AND FT.ANULADO = 0

UNION ALL 

SELECT 
    'HSOLS_PT' AS BDADOS, FT.FTSTAMP, FI.FISTAMP, FT.NMDOC, FT.FNO, FDATA, FI.REF, FI.DESIGN, FI.QTT, FI.ETILIQUIDO * (1-(FT.FIN/100)) AS ETTILIQ, FT2.PROCESSO, FT.TIPODOC, SUBSTRING(FT2.PROCESSO,3,4) AS CCUSTO_GERAL,
	CASE WHEN CL.VENDNM = 'INTRAGRUPO' THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS INSTRAGRUPO
FROM HSOLS_PT..FT (NOLOCK) 
JOIN HSOLS_PT..FI (NOLOCK) ON FI.FTSTAMP = FT.FTSTAMP
JOIN HSOLS_PT..FT2 (NOLOCK) ON FT2.FT2STAMP = FT.FTSTAMP
LEFT JOIN HSOLS_PT..CL ON CL.NO = FT.NO AND CL.ESTAB = 0 
WHERE FI.REF NOT IN ('RG','RFT') AND FT.TIPODOC IN (1,2,3)
AND FI.ETILIQUIDO <> 0
AND FT.ANULADO = 0

UNION ALL 

SELECT 
    'GR360_TRAD' AS BDADOS, FT.FTSTAMP, FI.FISTAMP, FT.NMDOC, FT.FNO, FDATA, FI.REF, FI.DESIGN, FI.QTT, FI.ETILIQUIDO * (1-(FT.FIN/100)) AS ETTILIQ, FT2.PROCESSO, FT.TIPODOC, SUBSTRING(FT2.PROCESSO,3,4) AS CCUSTO_GERAL,
	CASE WHEN CL.VENDNM = 'INTRAGRUPO' THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS INSTRAGRUPO
FROM GR360_TRAD..FT (NOLOCK) 
JOIN GR360_TRAD..FI (NOLOCK) ON FI.FTSTAMP = FT.FTSTAMP
JOIN GR360_TRAD..FT2 (NOLOCK) ON FT2.FT2STAMP = FT.FTSTAMP
LEFT JOIN GR360_TRAD..CL ON CL.NO = FT.NO AND CL.ESTAB = 0 
WHERE FI.REF NOT IN ('RG','RFT') AND FT.TIPODOC IN (1,2,3)
AND FI.ETILIQUIDO <> 0
AND FT.ANULADO = 0

UNION ALL 

SELECT 
    'GR360' AS BDADOS, FT.FTSTAMP, FI.FISTAMP, FT.NMDOC, FT.FNO, FDATA, FI.REF, FI.DESIGN, FI.QTT, FI.ETILIQUIDO * (1-(FT.FIN/100)) AS ETTILIQ, FT2.PROCESSO, FT.TIPODOC, SUBSTRING(FT2.PROCESSO,3,4) AS CCUSTO_GERAL,
	CASE WHEN CL.VENDNM = 'INTRAGRUPO' THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END AS INSTRAGRUPO
FROM GR360..FT (NOLOCK) 
JOIN GR360..FI (NOLOCK) ON FI.FTSTAMP = FT.FTSTAMP
JOIN GR360..FT2 (NOLOCK) ON FT2.FT2STAMP = FT.FTSTAMP
LEFT JOIN GR360..CL ON CL.NO = FT.NO AND CL.ESTAB = 0 
WHERE FI.REF NOT IN ('RG','RFT') AND FT.TIPODOC IN (1,2,3)
AND FI.ETILIQUIDO <> 0
AND FT.ANULADO = 0

