SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID('dbo.COMODIDADES', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.COMODIDADES (
        ID int IDENTITY(1,1) NOT NULL,
        CODIGO varchar(60) NOT NULL,
        NOME_PT nvarchar(120) NOT NULL,
        NOME_EN nvarchar(120) NOT NULL,
        NOME_ES nvarchar(120) NOT NULL,
        NOME_FR nvarchar(120) NOT NULL,
        CATEGORIA varchar(40) NOT NULL,
        ICONE varchar(60) NOT NULL,
        ORDEM int NOT NULL CONSTRAINT DF_COMODIDADES_ORDEM DEFAULT (0),
        ATIVA bit NOT NULL CONSTRAINT DF_COMODIDADES_ATIVA DEFAULT (1),
        MOSTRA_PORTOBREAK bit NOT NULL CONSTRAINT DF_COMODIDADES_MOSTRA_PB DEFAULT (1),
        FILTRO_PORTOBREAK bit NOT NULL CONSTRAINT DF_COMODIDADES_FILTRO_PB DEFAULT (0),
        CONSTRAINT PK_COMODIDADES PRIMARY KEY CLUSTERED (ID),
        CONSTRAINT UQ_COMODIDADES_CODIGO UNIQUE (CODIGO),
        CONSTRAINT CK_COMODIDADES_CODIGO CHECK (CODIGO <> ''),
        CONSTRAINT CK_COMODIDADES_FILTRO CHECK (FILTRO_PORTOBREAK = 0 OR (ATIVA = 1 AND MOSTRA_PORTOBREAK = 1))
    );
END;

IF OBJECT_ID('dbo.AL_COMODIDADES', 'U') IS NULL
BEGIN
    EXEC(N'CREATE TABLE dbo.AL_COMODIDADES (
        ALOJAMENTO varchar(60) NOT NULL,
        COMODIDADE_ID int NOT NULL,
        CONSTRAINT PK_AL_COMODIDADES PRIMARY KEY CLUSTERED (ALOJAMENTO, COMODIDADE_ID),
        CONSTRAINT FK_AL_COMODIDADES_COMODIDADES FOREIGN KEY (COMODIDADE_ID)
            REFERENCES dbo.COMODIDADES (ID)
    );
    CREATE NONCLUSTERED INDEX IX_AL_COMODIDADES_COMODIDADE
        ON dbo.AL_COMODIDADES (COMODIDADE_ID, ALOJAMENTO);');
END;

-- Correção compatível com uma versão inicial ainda ligada por ALSTAMP.
IF COL_LENGTH('dbo.AL_COMODIDADES', 'ALSTAMP') IS NOT NULL
   AND COL_LENGTH('dbo.AL_COMODIDADES', 'ALOJAMENTO') IS NULL
BEGIN
    EXEC(N'ALTER TABLE dbo.AL_COMODIDADES ADD ALOJAMENTO varchar(60) NULL;');
    EXEC(N'UPDATE AC SET ALOJAMENTO = AL.NOME
      FROM dbo.AL_COMODIDADES AC
      INNER JOIN dbo.AL AL ON AL.ALSTAMP = AC.ALSTAMP;');
    EXEC(N'DELETE FROM dbo.AL_COMODIDADES WHERE ALOJAMENTO IS NULL OR LTRIM(RTRIM(ALOJAMENTO)) = '''';');
    ALTER TABLE dbo.AL_COMODIDADES DROP CONSTRAINT PK_AL_COMODIDADES;
    IF EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.AL_COMODIDADES') AND name='IX_AL_COMODIDADES_COMODIDADE')
        DROP INDEX IX_AL_COMODIDADES_COMODIDADE ON dbo.AL_COMODIDADES;
    ALTER TABLE dbo.AL_COMODIDADES DROP COLUMN ALSTAMP;
    EXEC(N'ALTER TABLE dbo.AL_COMODIDADES ALTER COLUMN ALOJAMENTO varchar(60) NOT NULL;');
    EXEC(N'ALTER TABLE dbo.AL_COMODIDADES ADD CONSTRAINT PK_AL_COMODIDADES PRIMARY KEY CLUSTERED (ALOJAMENTO, COMODIDADE_ID);');
    EXEC(N'CREATE NONCLUSTERED INDEX IX_AL_COMODIDADES_COMODIDADE
        ON dbo.AL_COMODIDADES (COMODIDADE_ID, ALOJAMENTO);');
END;

COMMIT TRANSACTION;
