IF COL_LENGTH('dbo.AL', 'DESCRICAO') IS NULL
BEGIN
    ALTER TABLE dbo.AL
    ADD DESCRICAO text NOT NULL
        CONSTRAINT DF_AL_DESCRICAO DEFAULT ('');
END;

IF COL_LENGTH('dbo.AL', 'DESCRICAOEN') IS NULL
BEGIN
    ALTER TABLE dbo.AL
    ADD DESCRICAOEN text NOT NULL
        CONSTRAINT DF_AL_DESCRICAOEN DEFAULT ('');
END;

IF COL_LENGTH('dbo.AL', 'DESCRICAOFR') IS NULL
BEGIN
    ALTER TABLE dbo.AL
    ADD DESCRICAOFR text NOT NULL
        CONSTRAINT DF_AL_DESCRICAOFR DEFAULT ('');
END;

IF COL_LENGTH('dbo.AL', 'DESCRICAOES') IS NULL
BEGIN
    ALTER TABLE dbo.AL
    ADD DESCRICAOES text NOT NULL
        CONSTRAINT DF_AL_DESCRICAOES DEFAULT ('');
END;

DECLARE @campos TABLE (
    NMCAMPO varchar(25) NOT NULL,
    DESCRICAO varchar(60) NOT NULL,
    TIPO varchar(18) NOT NULL,
    ORDEM int NOT NULL,
    TAM int NOT NULL,
    ORDEM_MOBILE int NOT NULL,
    TAM_MOBILE int NOT NULL
);

INSERT INTO @campos (NMCAMPO, DESCRICAO, TIPO, ORDEM, TAM, ORDEM_MOBILE, TAM_MOBILE)
VALUES
    ('DESCRICAO', 'Descricao PT', 'MEMO', 95, 25, 0, 25),
    ('DESCRICAOEN', 'Descricao EN', 'MEMO', 96, 25, 0, 25),
    ('DESCRICAOFR', 'Descricao FR', 'MEMO', 97, 25, 0, 25),
    ('DESCRICAOES', 'Descricao ES', 'MEMO', 98, 25, 0, 25);

MERGE dbo.CAMPOS AS target
USING @campos AS source
   ON UPPER(LTRIM(RTRIM(ISNULL(target.TABELA, '')))) = 'AL'
  AND UPPER(LTRIM(RTRIM(ISNULL(target.NMCAMPO, '')))) = source.NMCAMPO
WHEN MATCHED THEN
    UPDATE SET
        DESCRICAO = source.DESCRICAO,
        TIPO = source.TIPO,
        ORDEM = source.ORDEM,
        TAM = source.TAM,
        ORDEM_MOBILE = source.ORDEM_MOBILE,
        TAM_MOBILE = source.TAM_MOBILE,
        VISIVEL = 1
WHEN NOT MATCHED THEN
    INSERT (
        CAMPOSSTAMP, ORDEM, NMCAMPO, DESCRICAO, TIPO, TABELA,
        LISTA, FILTRO, FILTRODEFAULT, ADMIN, RONLY, COMBO, VIRTUAL,
        TAM, ORDEM_MOBILE, TAM_MOBILE, CONDICAO_VISIVEL, OBRIGATORIO,
        VISIVEL
    )
    VALUES (
        LEFT(REPLACE(CONVERT(varchar(36), NEWID()), '-', ''), 25),
        source.ORDEM, source.NMCAMPO, source.DESCRICAO, source.TIPO, 'AL',
        0, 0, '', 0, 0, '', '',
        source.TAM, source.ORDEM_MOBILE, source.TAM_MOBILE, '', 0,
        1
    );
