IF COL_LENGTH('dbo.AL', 'ESTACIONAMENTO') IS NULL
BEGIN
    ALTER TABLE dbo.AL
    ADD ESTACIONAMENTO text NOT NULL
        CONSTRAINT DF_AL_ESTACIONAMENTO DEFAULT ('');
END;

IF COL_LENGTH('dbo.AL', 'ESTACIONAMENTOEN') IS NULL
BEGIN
    ALTER TABLE dbo.AL
    ADD ESTACIONAMENTOEN text NOT NULL
        CONSTRAINT DF_AL_ESTACIONAMENTOEN DEFAULT ('');
END;

IF COL_LENGTH('dbo.AL', 'ESTACIONAMENTOFR') IS NULL
BEGIN
    ALTER TABLE dbo.AL
    ADD ESTACIONAMENTOFR text NOT NULL
        CONSTRAINT DF_AL_ESTACIONAMENTOFR DEFAULT ('');
END;

IF COL_LENGTH('dbo.AL', 'ESTACIONAMENTOES') IS NULL
BEGIN
    ALTER TABLE dbo.AL
    ADD ESTACIONAMENTOES text NOT NULL
        CONSTRAINT DF_AL_ESTACIONAMENTOES DEFAULT ('');
END;

DECLARE @campos TABLE (
    NMCAMPO varchar(25) NOT NULL,
    DESCRICAO varchar(60) NOT NULL,
    TIPO varchar(18) NOT NULL,
    ORDEM int NOT NULL,
    TAM int NOT NULL,
    ORDEM_MOBILE int NOT NULL,
    TAM_MOBILE int NOT NULL
);

INSERT INTO @campos (NMCAMPO, DESCRICAO, TIPO, ORDEM, TAM, ORDEM_MOBILE, TAM_MOBILE)
VALUES
    ('ESTACIONAMENTO', 'Estacionamento PT', 'MEMO', 134, 25, 0, 25),
    ('ESTACIONAMENTOEN', 'Estacionamento EN', 'MEMO', 135, 25, 0, 25),
    ('ESTACIONAMENTOFR', 'Estacionamento FR', 'MEMO', 136, 25, 0, 25),
    ('ESTACIONAMENTOES', 'Estacionamento ES', 'MEMO', 137, 25, 0, 25);

MERGE dbo.CAMPOS AS target
USING @campos AS source
   ON UPPER(LTRIM(RTRIM(ISNULL(target.TABELA, '')))) = 'AL'
  AND UPPER(LTRIM(RTRIM(ISNULL(target.NMCAMPO, '')))) = source.NMCAMPO
WHEN MATCHED THEN
    UPDATE SET
        DESCRICAO = source.DESCRICAO,
        TIPO = source.TIPO,
        ORDEM = source.ORDEM,
        TAM = source.TAM,
        ORDEM_MOBILE = source.ORDEM_MOBILE,
        TAM_MOBILE = source.TAM_MOBILE,
        VISIVEL = 1
WHEN NOT MATCHED THEN
    INSERT (
        CAMPOSSTAMP, ORDEM, NMCAMPO, DESCRICAO, TIPO, TABELA,
        LISTA, FILTRO, FILTRODEFAULT, ADMIN, RONLY, COMBO, VIRTUAL,
        TAM, ORDEM_MOBILE, TAM_MOBILE, CONDICAO_VISIVEL, OBRIGATORIO,
        VISIVEL
    )
    VALUES (
        LEFT(REPLACE(CONVERT(varchar(36), NEWID()), '-', ''), 25),
        source.ORDEM, source.NMCAMPO, source.DESCRICAO, source.TIPO, 'AL',
        0, 0, '', 0, 0, '', '',
        source.TAM, source.ORDEM_MOBILE, source.TAM_MOBILE, '', 0,
        1
    );
