IF OBJECT_ID('dbo.PB_USERS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PB_USERS (
        PBUSERSTAMP varchar(50) NOT NULL,
        NOME nvarchar(160) NOT NULL,
        EMAIL nvarchar(255) NOT NULL,
        EMAIL_NORMALIZADO nvarchar(255) NOT NULL,
        TELEFONE nvarchar(60) NOT NULL CONSTRAINT DF_PB_USERS_TELEFONE DEFAULT '',
        MORADA nvarchar(300) NOT NULL CONSTRAINT DF_PB_USERS_MORADA DEFAULT '',
        PAIS nvarchar(100) NOT NULL CONSTRAINT DF_PB_USERS_PAIS DEFAULT '',
        NIF nvarchar(40) NOT NULL CONSTRAINT DF_PB_USERS_NIF DEFAULT '',
        PASSWORD_HASH nvarchar(512) NOT NULL,
        PASSWORD_ALGO nvarchar(50) NOT NULL,
        ATIVO bit NOT NULL CONSTRAINT DF_PB_USERS_ATIVO DEFAULT 1,
        DTCRI datetime2(0) NOT NULL CONSTRAINT DF_PB_USERS_DTCRI DEFAULT SYSUTCDATETIME(),
        DTALT datetime2(0) NULL,
        CONSTRAINT PK_PB_USERS PRIMARY KEY CLUSTERED (PBUSERSTAMP)
    );
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UX_PB_USERS_EMAIL'
      AND object_id = OBJECT_ID('dbo.PB_USERS')
)
BEGIN
    CREATE UNIQUE INDEX UX_PB_USERS_EMAIL ON dbo.PB_USERS (EMAIL_NORMALIZADO);
END;

IF COL_LENGTH('dbo.PB_USERS', 'EMAIL_CONFIRMADO') IS NULL
BEGIN
    ALTER TABLE dbo.PB_USERS
        ADD EMAIL_CONFIRMADO bit NOT NULL
            CONSTRAINT DF_PB_USERS_EMAIL_CONFIRMADO DEFAULT 0 WITH VALUES;
END;

IF COL_LENGTH('dbo.PB_USERS', 'EMAIL_CONFIRMADO_EM') IS NULL
BEGIN
    ALTER TABLE dbo.PB_USERS ADD EMAIL_CONFIRMADO_EM datetime2(0) NULL;
END;

IF OBJECT_ID('dbo.PB_EMAIL_VERIFICATIONS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PB_EMAIL_VERIFICATIONS (
        PBEMAILVERSTAMP varchar(50) NOT NULL,
        PBUSERSTAMP varchar(50) NOT NULL,
        TOKEN_HASH char(64) NOT NULL,
        EXPIRA_EM datetime2(0) NOT NULL,
        USADO_EM datetime2(0) NULL,
        EMAIL_ID bigint NULL,
        DTCRI datetime2(0) NOT NULL
            CONSTRAINT DF_PB_EMAIL_VERIFICATIONS_DTCRI DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_PB_EMAIL_VERIFICATIONS PRIMARY KEY CLUSTERED (PBEMAILVERSTAMP),
        CONSTRAINT FK_PB_EMAIL_VERIFICATIONS_USER
            FOREIGN KEY (PBUSERSTAMP) REFERENCES dbo.PB_USERS(PBUSERSTAMP)
    );
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UX_PB_EMAIL_VERIFICATIONS_TOKEN'
      AND object_id = OBJECT_ID('dbo.PB_EMAIL_VERIFICATIONS')
)
BEGIN
    CREATE UNIQUE INDEX UX_PB_EMAIL_VERIFICATIONS_TOKEN
        ON dbo.PB_EMAIL_VERIFICATIONS (TOKEN_HASH);
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_PB_EMAIL_VERIFICATIONS_USER'
      AND object_id = OBJECT_ID('dbo.PB_EMAIL_VERIFICATIONS')
)
BEGIN
    CREATE INDEX IX_PB_EMAIL_VERIFICATIONS_USER
        ON dbo.PB_EMAIL_VERIFICATIONS (PBUSERSTAMP, USADO_EM, EXPIRA_EM, DTCRI DESC);
END;

IF OBJECT_ID('dbo.PB_BOOKING_REQUESTS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PB_BOOKING_REQUESTS (
        PBBKSTAMP varchar(50) NOT NULL,
        PBUSERSTAMP varchar(50) NULL,
        ALSTAMP varchar(50) NOT NULL,
        AL_NOME nvarchar(180) NOT NULL,
        CHECKIN date NOT NULL,
        CHECKOUT date NOT NULL,
        NOITES int NOT NULL,
        ADULTOS int NOT NULL CONSTRAINT DF_PB_BOOKING_ADULTOS DEFAULT 0,
        CRIANCAS int NOT NULL CONSTRAINT DF_PB_BOOKING_CRIANCAS DEFAULT 0,
        BEBES int NOT NULL CONSTRAINT DF_PB_BOOKING_BEBES DEFAULT 0,
        CLIENTE_NOME nvarchar(160) NOT NULL,
        CLIENTE_EMAIL nvarchar(255) NOT NULL,
        CLIENTE_TELEFONE nvarchar(60) NOT NULL CONSTRAINT DF_PB_BOOKING_TELEFONE DEFAULT '',
        CLIENTE_MORADA nvarchar(300) NOT NULL CONSTRAINT DF_PB_BOOKING_MORADA DEFAULT '',
        CLIENTE_PAIS nvarchar(100) NOT NULL,
        CLIENTE_NIF nvarchar(40) NOT NULL CONSTRAINT DF_PB_BOOKING_NIF DEFAULT '',
        CRIOU_CONTA bit NOT NULL CONSTRAINT DF_PB_BOOKING_CRIOU_CONTA DEFAULT 0,
        ESTADO nvarchar(30) NOT NULL CONSTRAINT DF_PB_BOOKING_ESTADO DEFAULT 'PENDENTE',
        PRECO_ESTIMADO decimal(12, 2) NULL,
        PRECO_LABEL nvarchar(40) NOT NULL CONSTRAINT DF_PB_BOOKING_PRECO_LABEL DEFAULT '',
        EMAIL_ID bigint NULL,
        OBSERVACOES nvarchar(max) NOT NULL CONSTRAINT DF_PB_BOOKING_OBS DEFAULT '',
        DADOS_JSON nvarchar(max) NOT NULL CONSTRAINT DF_PB_BOOKING_JSON DEFAULT '{}',
        IP_CLIENTE nvarchar(80) NOT NULL CONSTRAINT DF_PB_BOOKING_IP DEFAULT '',
        USER_AGENT nvarchar(500) NOT NULL CONSTRAINT DF_PB_BOOKING_UA DEFAULT '',
        DTCRI datetime2(0) NOT NULL CONSTRAINT DF_PB_BOOKING_DTCRI DEFAULT SYSUTCDATETIME(),
        DTALT datetime2(0) NULL,
        CONSTRAINT PK_PB_BOOKING_REQUESTS PRIMARY KEY CLUSTERED (PBBKSTAMP),
        CONSTRAINT FK_PB_BOOKING_USER FOREIGN KEY (PBUSERSTAMP) REFERENCES dbo.PB_USERS(PBUSERSTAMP),
        CONSTRAINT CK_PB_BOOKING_INTERVALO CHECK (CHECKOUT > CHECKIN),
        CONSTRAINT CK_PB_BOOKING_ESTADO CHECK (ESTADO IN ('PENDENTE', 'CONFIRMADO', 'RECUSADO', 'CANCELADO'))
    );
END;

IF COL_LENGTH('dbo.PB_BOOKING_REQUESTS', 'EMAIL_ID') IS NULL
BEGIN
    ALTER TABLE dbo.PB_BOOKING_REQUESTS ADD EMAIL_ID bigint NULL;
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_PB_BOOKING_AL_DATAS'
      AND object_id = OBJECT_ID('dbo.PB_BOOKING_REQUESTS')
)
BEGIN
    CREATE INDEX IX_PB_BOOKING_AL_DATAS
        ON dbo.PB_BOOKING_REQUESTS (ALSTAMP, CHECKIN, CHECKOUT, ESTADO);
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_PB_BOOKING_EMAIL'
      AND object_id = OBJECT_ID('dbo.PB_BOOKING_REQUESTS')
)
BEGIN
    CREATE INDEX IX_PB_BOOKING_EMAIL
        ON dbo.PB_BOOKING_REQUESTS (CLIENTE_EMAIL, DTCRI);
END;
