IF OBJECT_ID('dbo.PB_STRIPE_TEST_PAYMENTS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PB_STRIPE_TEST_PAYMENTS (
        PBPAYSTAMP varchar(50) NOT NULL,
        PBBKSTAMP varchar(50) NOT NULL,
        PBUSERSTAMP varchar(50) NULL,
        ESTADO varchar(30) NOT NULL,
        MOEDA char(3) NOT NULL CONSTRAINT DF_PB_STRIPE_TEST_PAYMENTS_MOEDA DEFAULT 'EUR',
        VALOR decimal(12, 2) NOT NULL,
        IDEMPOTENCY_KEY varchar(100) NOT NULL,
        CHECKOUT_SESSION_ID varchar(120) NULL,
        PAYMENT_INTENT_ID varchar(120) NULL,
        RSSTAMP varchar(25) NULL,
        STRIPE_STATUS varchar(80) NULL,
        DTCRI datetime2(0) NOT NULL CONSTRAINT DF_PB_STRIPE_TEST_PAYMENTS_DTCRI DEFAULT SYSUTCDATETIME(),
        DTALT datetime2(0) NULL,
        CONSTRAINT PK_PB_STRIPE_TEST_PAYMENTS PRIMARY KEY CLUSTERED (PBPAYSTAMP),
        CONSTRAINT FK_PB_STRIPE_TEST_PAYMENTS_BOOKING
            FOREIGN KEY (PBBKSTAMP) REFERENCES dbo.PB_BOOKING_REQUESTS(PBBKSTAMP),
        CONSTRAINT FK_PB_STRIPE_TEST_PAYMENTS_USER
            FOREIGN KEY (PBUSERSTAMP) REFERENCES dbo.PB_USERS(PBUSERSTAMP),
        CONSTRAINT CK_PB_STRIPE_TEST_PAYMENTS_ESTADO
            CHECK (ESTADO IN ('CRIADO', 'PAGO_TESTE', 'FALHADO', 'EXPIRADO'))
    );
END;

IF COL_LENGTH('dbo.PB_STRIPE_TEST_PAYMENTS', 'PBUSERSTAMP') IS NOT NULL
BEGIN
    ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS
        ALTER COLUMN PBUSERSTAMP varchar(50) NULL;
END;

IF COL_LENGTH('dbo.PB_STRIPE_TEST_PAYMENTS', 'RSSTAMP') IS NULL
BEGIN
    EXEC('ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS ADD RSSTAMP varchar(25) NULL;');
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UX_PB_STRIPE_TEST_PAYMENTS_SESSION'
      AND object_id = OBJECT_ID('dbo.PB_STRIPE_TEST_PAYMENTS')
)
BEGIN
    CREATE UNIQUE INDEX UX_PB_STRIPE_TEST_PAYMENTS_SESSION
        ON dbo.PB_STRIPE_TEST_PAYMENTS (CHECKOUT_SESSION_ID)
        WHERE CHECKOUT_SESSION_ID IS NOT NULL;
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UX_PB_STRIPE_TEST_PAYMENTS_RSSTAMP'
      AND object_id = OBJECT_ID('dbo.PB_STRIPE_TEST_PAYMENTS')
)
BEGIN
    EXEC('CREATE UNIQUE INDEX UX_PB_STRIPE_TEST_PAYMENTS_RSSTAMP
        ON dbo.PB_STRIPE_TEST_PAYMENTS (RSSTAMP)
        WHERE RSSTAMP IS NOT NULL;');
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_PB_STRIPE_TEST_PAYMENTS_BOOKING'
      AND object_id = OBJECT_ID('dbo.PB_STRIPE_TEST_PAYMENTS')
)
BEGIN
    CREATE INDEX IX_PB_STRIPE_TEST_PAYMENTS_BOOKING
        ON dbo.PB_STRIPE_TEST_PAYMENTS (PBBKSTAMP, PBUSERSTAMP, ESTADO, DTCRI DESC);
END;
