IF OBJECT_ID('dbo.PB_STRIPE_TEST_PAYMENTS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PB_STRIPE_TEST_PAYMENTS (
        PBPAYSTAMP varchar(50) NOT NULL,
        PBBKSTAMP varchar(50) NOT NULL,
        PBUSERSTAMP varchar(50) NULL,
        ESTADO varchar(30) NOT NULL,
        MOEDA char(3) NOT NULL CONSTRAINT DF_PB_STRIPE_TEST_PAYMENTS_MOEDA DEFAULT 'EUR',
        VALOR decimal(12, 2) NOT NULL,
        IDEMPOTENCY_KEY varchar(100) NOT NULL,
        CHECKOUT_SESSION_ID varchar(120) NULL,
        PAYMENT_INTENT_ID varchar(120) NULL,
        RSSTAMP varchar(25) NULL,
        STRIPE_STATUS varchar(80) NULL,
        DTCRI datetime2(0) NOT NULL CONSTRAINT DF_PB_STRIPE_TEST_PAYMENTS_DTCRI DEFAULT SYSUTCDATETIME(),
        DTALT datetime2(0) NULL,
        CONSTRAINT PK_PB_STRIPE_TEST_PAYMENTS PRIMARY KEY CLUSTERED (PBPAYSTAMP),
        CONSTRAINT FK_PB_STRIPE_TEST_PAYMENTS_BOOKING
            FOREIGN KEY (PBBKSTAMP) REFERENCES dbo.PB_BOOKING_REQUESTS(PBBKSTAMP),
        CONSTRAINT FK_PB_STRIPE_TEST_PAYMENTS_USER
            FOREIGN KEY (PBUSERSTAMP) REFERENCES dbo.PB_USERS(PBUSERSTAMP),
        CONSTRAINT CK_PB_STRIPE_TEST_PAYMENTS_ESTADO
            CHECK (ESTADO IN ('CRIADO', 'PAGO_TESTE', 'FALHADO', 'EXPIRADO'))
    );
END;

IF COL_LENGTH('dbo.PB_STRIPE_TEST_PAYMENTS', 'PBUSERSTAMP') IS NOT NULL
BEGIN
    ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS
        ALTER COLUMN PBUSERSTAMP varchar(50) NULL;
END;

IF COL_LENGTH('dbo.PB_STRIPE_TEST_PAYMENTS', 'RSSTAMP') IS NULL
BEGIN
    EXEC('ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS ADD RSSTAMP varchar(25) NULL;');
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UX_PB_STRIPE_TEST_PAYMENTS_SESSION'
      AND object_id = OBJECT_ID('dbo.PB_STRIPE_TEST_PAYMENTS')
)
BEGIN
    CREATE UNIQUE INDEX UX_PB_STRIPE_TEST_PAYMENTS_SESSION
        ON dbo.PB_STRIPE_TEST_PAYMENTS (CHECKOUT_SESSION_ID)
        WHERE CHECKOUT_SESSION_ID IS NOT NULL;
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UX_PB_STRIPE_TEST_PAYMENTS_RSSTAMP'
      AND object_id = OBJECT_ID('dbo.PB_STRIPE_TEST_PAYMENTS')
)
BEGIN
    EXEC('CREATE UNIQUE INDEX UX_PB_STRIPE_TEST_PAYMENTS_RSSTAMP
        ON dbo.PB_STRIPE_TEST_PAYMENTS (RSSTAMP)
        WHERE RSSTAMP IS NOT NULL;');
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_PB_STRIPE_TEST_PAYMENTS_BOOKING'
      AND object_id = OBJECT_ID('dbo.PB_STRIPE_TEST_PAYMENTS')
)
BEGIN
    CREATE INDEX IX_PB_STRIPE_TEST_PAYMENTS_BOOKING
        ON dbo.PB_STRIPE_TEST_PAYMENTS (PBBKSTAMP, PBUSERSTAMP, ESTADO, DTCRI DESC);
END;

IF COL_LENGTH('dbo.PB_STRIPE_TEST_PAYMENTS', 'AMBIENTE') IS NULL
BEGIN
    ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS
        ADD AMBIENTE varchar(10) NOT NULL
            CONSTRAINT DF_PB_STRIPE_TEST_PAYMENTS_AMBIENTE DEFAULT 'TEST';
END;

DECLARE @payment_state_constraint sysname;
DECLARE @drop_payment_state_constraint_sql nvarchar(max);
SELECT @payment_state_constraint = name
FROM sys.check_constraints
WHERE parent_object_id = OBJECT_ID('dbo.PB_STRIPE_TEST_PAYMENTS')
  AND name = 'CK_PB_STRIPE_TEST_PAYMENTS_ESTADO';

IF @payment_state_constraint IS NOT NULL
BEGIN
    SET @drop_payment_state_constraint_sql =
        N'ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS DROP CONSTRAINT ' + QUOTENAME(@payment_state_constraint);
    EXEC(@drop_payment_state_constraint_sql);
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.check_constraints
    WHERE parent_object_id = OBJECT_ID('dbo.PB_STRIPE_TEST_PAYMENTS')
      AND name = 'CK_PB_STRIPE_TEST_PAYMENTS_ESTADO'
)
BEGIN
    ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS
        ADD CONSTRAINT CK_PB_STRIPE_TEST_PAYMENTS_ESTADO
        CHECK (ESTADO IN ('CRIADO', 'PAGO_TESTE', 'PAGO', 'FALHADO', 'EXPIRADO'));
END;

IF OBJECT_ID('dbo.PB_STRIPE_WEBHOOK_EVENTS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PB_STRIPE_WEBHOOK_EVENTS (
        EVENT_ID varchar(255) NOT NULL,
        EVENT_TYPE varchar(120) NOT NULL,
        AMBIENTE varchar(10) NOT NULL,
        PBPAYSTAMP varchar(50) NULL,
        ESTADO varchar(20) NOT NULL CONSTRAINT DF_PB_STRIPE_WEBHOOK_EVENTS_ESTADO DEFAULT 'RECEBIDO',
        ULTIMO_ERRO varchar(1000) NULL,
        RECEBIDO_EM datetime2(0) NOT NULL CONSTRAINT DF_PB_STRIPE_WEBHOOK_EVENTS_RECEBIDO DEFAULT SYSUTCDATETIME(),
        PROCESSADO_EM datetime2(0) NULL,
        CONSTRAINT PK_PB_STRIPE_WEBHOOK_EVENTS PRIMARY KEY CLUSTERED (EVENT_ID),
        CONSTRAINT FK_PB_STRIPE_WEBHOOK_EVENTS_PAYMENT
            FOREIGN KEY (PBPAYSTAMP) REFERENCES dbo.PB_STRIPE_TEST_PAYMENTS(PBPAYSTAMP),
        CONSTRAINT CK_PB_STRIPE_WEBHOOK_EVENTS_ESTADO
            CHECK (ESTADO IN ('RECEBIDO', 'PROCESSADO', 'IGNORADO', 'ERRO'))
    );
END;

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'IX_PB_STRIPE_WEBHOOK_EVENTS_PAYMENT'
      AND object_id = OBJECT_ID('dbo.PB_STRIPE_WEBHOOK_EVENTS')
)
BEGIN
    CREATE INDEX IX_PB_STRIPE_WEBHOOK_EVENTS_PAYMENT
        ON dbo.PB_STRIPE_WEBHOOK_EVENTS (PBPAYSTAMP, EVENT_TYPE, RECEBIDO_EM DESC);
END;
