SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID('dbo.PB_FX_RATES', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PB_FX_RATES (
        MOEDA char(3) NOT NULL,
        TAXA_POR_EUR decimal(18, 8) NOT NULL,
        DATA_TAXA date NOT NULL,
        ATUALIZADO_EM datetime2(0) NOT NULL,
        FONTE varchar(120) NOT NULL,
        ATIVA bit NOT NULL CONSTRAINT DF_PB_FX_RATES_ATIVA DEFAULT 1,
        ULTIMO_ERRO varchar(1000) NULL,
        CONSTRAINT PK_PB_FX_RATES PRIMARY KEY CLUSTERED (MOEDA),
        CONSTRAINT CK_PB_FX_RATES_MOEDA CHECK (MOEDA IN ('EUR', 'GBP', 'USD')),
        CONSTRAINT CK_PB_FX_RATES_TAXA CHECK (TAXA_POR_EUR > 0)
    );
END;

IF NOT EXISTS (SELECT 1 FROM dbo.PARA WHERE UPPER(LTRIM(RTRIM(PARAMETRO))) = 'FX_MARGIN_PERCENT')
BEGIN
    INSERT INTO dbo.PARA
        (PARASTAMP, PARAMETRO, DESCRICAO, TIPO, CVALOR, DVALOR, NVALOR, LVALOR, GRUPO, FEID)
    VALUES
        (LEFT(REPLACE(CONVERT(varchar(36), NEWID()), '-', ''), 25),
         'FX_MARGIN_PERCENT', 'Margem cambial PortoBreak (%)', 'NUMERICO', '1.5',
         '19000101', 1.5000, 0, 'PORTOBREAK', NULL);
END;

IF COL_LENGTH('dbo.PB_BOOKING_REQUESTS', 'MOEDA_APRESENTACAO') IS NULL
    ALTER TABLE dbo.PB_BOOKING_REQUESTS ADD MOEDA_APRESENTACAO char(3) NOT NULL CONSTRAINT DF_PB_BOOKING_MOEDA DEFAULT 'EUR' WITH VALUES;
IF COL_LENGTH('dbo.PB_BOOKING_REQUESTS', 'VALOR_APRESENTADO') IS NULL
    ALTER TABLE dbo.PB_BOOKING_REQUESTS ADD VALOR_APRESENTADO decimal(12, 2) NULL;
IF COL_LENGTH('dbo.PB_BOOKING_REQUESTS', 'CAMBIO_APRESENTACAO') IS NULL
    ALTER TABLE dbo.PB_BOOKING_REQUESTS ADD CAMBIO_APRESENTACAO decimal(18, 8) NULL;
IF COL_LENGTH('dbo.PB_BOOKING_REQUESTS', 'CAMBIO_BASE') IS NULL
    ALTER TABLE dbo.PB_BOOKING_REQUESTS ADD CAMBIO_BASE decimal(18, 8) NULL;
IF COL_LENGTH('dbo.PB_BOOKING_REQUESTS', 'FX_MARGIN_PERCENT') IS NULL
    ALTER TABLE dbo.PB_BOOKING_REQUESTS ADD FX_MARGIN_PERCENT decimal(9, 4) NULL;
IF COL_LENGTH('dbo.PB_BOOKING_REQUESTS', 'FX_DATA_TAXA') IS NULL
    ALTER TABLE dbo.PB_BOOKING_REQUESTS ADD FX_DATA_TAXA date NULL;
IF COL_LENGTH('dbo.PB_BOOKING_REQUESTS', 'FX_FONTE') IS NULL
    ALTER TABLE dbo.PB_BOOKING_REQUESTS ADD FX_FONTE varchar(120) NULL;

UPDATE dbo.PB_BOOKING_REQUESTS
SET VALOR_APRESENTADO = COALESCE(VALOR_APRESENTADO, PRECO_ESTIMADO),
    CAMBIO_APRESENTACAO = COALESCE(CAMBIO_APRESENTACAO, 1),
    CAMBIO_BASE = COALESCE(CAMBIO_BASE, 1),
    FX_MARGIN_PERCENT = COALESCE(FX_MARGIN_PERCENT, 0)
WHERE MOEDA_APRESENTACAO = 'EUR';

IF COL_LENGTH('dbo.PB_STRIPE_TEST_PAYMENTS', 'VALOR_EUR') IS NULL
    ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS ADD VALOR_EUR decimal(12, 2) NULL;
IF COL_LENGTH('dbo.PB_STRIPE_TEST_PAYMENTS', 'CAMBIO') IS NULL
    ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS ADD CAMBIO decimal(18, 8) NULL;
IF COL_LENGTH('dbo.PB_STRIPE_TEST_PAYMENTS', 'CAMBIO_BASE') IS NULL
    ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS ADD CAMBIO_BASE decimal(18, 8) NULL;
IF COL_LENGTH('dbo.PB_STRIPE_TEST_PAYMENTS', 'FX_MARGIN_PERCENT') IS NULL
    ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS ADD FX_MARGIN_PERCENT decimal(9, 4) NULL;
IF COL_LENGTH('dbo.PB_STRIPE_TEST_PAYMENTS', 'FX_DATA_TAXA') IS NULL
    ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS ADD FX_DATA_TAXA date NULL;
IF COL_LENGTH('dbo.PB_STRIPE_TEST_PAYMENTS', 'FX_FONTE') IS NULL
    ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS ADD FX_FONTE varchar(120) NULL;
IF COL_LENGTH('dbo.PB_STRIPE_TEST_PAYMENTS', 'CHARGE_ID') IS NULL
    ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS ADD CHARGE_ID varchar(120) NULL;
IF COL_LENGTH('dbo.PB_STRIPE_TEST_PAYMENTS', 'BALANCE_TRANSACTION_ID') IS NULL
    ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS ADD BALANCE_TRANSACTION_ID varchar(120) NULL;
IF COL_LENGTH('dbo.PB_STRIPE_TEST_PAYMENTS', 'STRIPE_LIQUIDO') IS NULL
    ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS ADD STRIPE_LIQUIDO decimal(12, 2) NULL;
IF COL_LENGTH('dbo.PB_STRIPE_TEST_PAYMENTS', 'STRIPE_LIQUIDO_MOEDA') IS NULL
    ALTER TABLE dbo.PB_STRIPE_TEST_PAYMENTS ADD STRIPE_LIQUIDO_MOEDA char(3) NULL;

UPDATE dbo.PB_STRIPE_TEST_PAYMENTS
SET VALOR_EUR = COALESCE(VALOR_EUR, VALOR),
    CAMBIO = COALESCE(CAMBIO, 1),
    CAMBIO_BASE = COALESCE(CAMBIO_BASE, 1),
    FX_MARGIN_PERCENT = COALESCE(FX_MARGIN_PERCENT, 0)
WHERE ISNULL(MOEDA, 'EUR') = 'EUR';

IF COL_LENGTH('dbo.RS', 'MOEDA_PAGAMENTO') IS NULL
    ALTER TABLE dbo.RS ADD MOEDA_PAGAMENTO char(3) NULL;
IF COL_LENGTH('dbo.RS', 'VALOR_PAGAMENTO') IS NULL
    ALTER TABLE dbo.RS ADD VALOR_PAGAMENTO numeric(12, 2) NULL;
IF COL_LENGTH('dbo.RS', 'CAMBIO_PAGAMENTO') IS NULL
    ALTER TABLE dbo.RS ADD CAMBIO_PAGAMENTO numeric(18, 8) NULL;
IF COL_LENGTH('dbo.RS', 'STRIPE_PAYMENT_INTENT') IS NULL
    ALTER TABLE dbo.RS ADD STRIPE_PAYMENT_INTENT varchar(120) NULL;
IF COL_LENGTH('dbo.RS', 'STRIPE_CHARGE_ID') IS NULL
    ALTER TABLE dbo.RS ADD STRIPE_CHARGE_ID varchar(120) NULL;
IF COL_LENGTH('dbo.RS', 'STRIPE_BALANCE_TRANSACTION') IS NULL
    ALTER TABLE dbo.RS ADD STRIPE_BALANCE_TRANSACTION varchar(120) NULL;
IF COL_LENGTH('dbo.RS', 'STRIPE_LIQUIDO') IS NULL
    ALTER TABLE dbo.RS ADD STRIPE_LIQUIDO numeric(12, 2) NULL;
IF COL_LENGTH('dbo.RS', 'STRIPE_LIQUIDO_MOEDA') IS NULL
    ALTER TABLE dbo.RS ADD STRIPE_LIQUIDO_MOEDA char(3) NULL;

UPDATE R
SET R.MOEDA_PAGAMENTO = COALESCE(R.MOEDA_PAGAMENTO, P.MOEDA),
    R.VALOR_PAGAMENTO = COALESCE(R.VALOR_PAGAMENTO, P.VALOR),
    R.CAMBIO_PAGAMENTO = COALESCE(R.CAMBIO_PAGAMENTO, P.CAMBIO),
    R.STRIPE_PAYMENT_INTENT = COALESCE(R.STRIPE_PAYMENT_INTENT, P.PAYMENT_INTENT_ID),
    R.STRIPE_CHARGE_ID = COALESCE(R.STRIPE_CHARGE_ID, P.CHARGE_ID),
    R.STRIPE_BALANCE_TRANSACTION = COALESCE(R.STRIPE_BALANCE_TRANSACTION, P.BALANCE_TRANSACTION_ID),
    R.STRIPE_LIQUIDO = COALESCE(R.STRIPE_LIQUIDO, P.STRIPE_LIQUIDO),
    R.STRIPE_LIQUIDO_MOEDA = COALESCE(R.STRIPE_LIQUIDO_MOEDA, P.STRIPE_LIQUIDO_MOEDA)
FROM dbo.RS AS R
INNER JOIN dbo.PB_STRIPE_TEST_PAYMENTS AS P ON P.RSSTAMP = R.RSSTAMP
WHERE ISNULL(R.ORIGEM, '') = 'PORTOBREAK';

IF OBJECT_ID('dbo.PB_ANALYTICS_SESSIONS', 'U') IS NOT NULL
   AND COL_LENGTH('dbo.PB_ANALYTICS_SESSIONS', 'currency') IS NULL
    ALTER TABLE dbo.PB_ANALYTICS_SESSIONS ADD currency varchar(3) NOT NULL CONSTRAINT DF_PB_ANALYTICS_SESSIONS_CURRENCY DEFAULT 'EUR' WITH VALUES;
IF OBJECT_ID('dbo.PB_ANALYTICS_PAGEVIEWS', 'U') IS NOT NULL
   AND COL_LENGTH('dbo.PB_ANALYTICS_PAGEVIEWS', 'currency') IS NULL
    ALTER TABLE dbo.PB_ANALYTICS_PAGEVIEWS ADD currency varchar(3) NOT NULL CONSTRAINT DF_PB_ANALYTICS_PAGEVIEWS_CURRENCY DEFAULT 'EUR' WITH VALUES;
IF OBJECT_ID('dbo.PB_ANALYTICS_TOTALS', 'U') IS NOT NULL
   AND COL_LENGTH('dbo.PB_ANALYTICS_TOTALS', 'currency') IS NULL
    ALTER TABLE dbo.PB_ANALYTICS_TOTALS ADD currency varchar(3) NOT NULL CONSTRAINT DF_PB_ANALYTICS_TOTALS_CURRENCY DEFAULT 'EUR' WITH VALUES;

COMMIT TRANSACTION;
