IF COL_LENGTH('dbo.CAMPOS', 'ORDEM_LISTA') IS NULL
BEGIN
    ALTER TABLE dbo.CAMPOS
    ADD ORDEM_LISTA int NOT NULL
        CONSTRAINT DF_CAMPOS_ORDEM_LISTA DEFAULT 0;

    UPDATE dbo.CAMPOS
    SET ORDEM_LISTA = CASE
        WHEN ISNULL(LISTA, 0) = 1 THEN ISNULL(ORDEM, 0)
        ELSE 0
    END;
END
GO

IF COL_LENGTH('dbo.CAMPOS', 'TAM_LISTA') IS NULL
BEGIN
    ALTER TABLE dbo.CAMPOS
    ADD TAM_LISTA int NOT NULL
        CONSTRAINT DF_CAMPOS_TAM_LISTA DEFAULT 5;

    UPDATE dbo.CAMPOS
    SET TAM_LISTA = CASE
        WHEN ISNULL(TAM, 0) > 0 THEN ISNULL(TAM, 5)
        ELSE 5
    END;
END
GO
