IF COL_LENGTH('dbo.CAMPOS', 'ORDEM_LISTA_MOBILE') IS NULL
BEGIN
    ALTER TABLE dbo.CAMPOS
    ADD ORDEM_LISTA_MOBILE int NOT NULL
        CONSTRAINT DF_CAMPOS_ORDEM_LISTA_MOBILE DEFAULT 0;
END
GO

IF COL_LENGTH('dbo.CAMPOS', 'TAM_LISTA_MOBILE') IS NULL
BEGIN
    ALTER TABLE dbo.CAMPOS
    ADD TAM_LISTA_MOBILE int NOT NULL
        CONSTRAINT DF_CAMPOS_TAM_LISTA_MOBILE DEFAULT 5;
END
GO

IF COL_LENGTH('dbo.CAMPOS', 'LISTA_MOBILE_BOLD') IS NULL
BEGIN
    ALTER TABLE dbo.CAMPOS
    ADD LISTA_MOBILE_BOLD bit NOT NULL
        CONSTRAINT DF_CAMPOS_LISTA_MOBILE_BOLD DEFAULT 0;
END
GO

IF COL_LENGTH('dbo.CAMPOS', 'LISTA_MOBILE_ITALIC') IS NULL
BEGIN
    ALTER TABLE dbo.CAMPOS
    ADD LISTA_MOBILE_ITALIC bit NOT NULL
        CONSTRAINT DF_CAMPOS_LISTA_MOBILE_ITALIC DEFAULT 0;
END
GO

IF COL_LENGTH('dbo.CAMPOS', 'LISTA_MOBILE_SHOW_LABEL') IS NULL
BEGIN
    ALTER TABLE dbo.CAMPOS
    ADD LISTA_MOBILE_SHOW_LABEL bit NOT NULL
        CONSTRAINT DF_CAMPOS_LISTA_MOBILE_SHOW_LABEL DEFAULT 1;
END
GO

IF COL_LENGTH('dbo.CAMPOS', 'LISTA_MOBILE_LABEL') IS NULL
BEGIN
    ALTER TABLE dbo.CAMPOS
    ADD LISTA_MOBILE_LABEL varchar(100) NOT NULL
        CONSTRAINT DF_CAMPOS_LISTA_MOBILE_LABEL DEFAULT '';
END
GO

UPDATE dbo.CAMPOS
SET ORDEM_LISTA_MOBILE = CASE
        WHEN ISNULL(LISTA, 0) = 1 AND ISNULL(ORDEM_MOBILE, 0) > 0 THEN ISNULL(ORDEM_MOBILE, 0)
        WHEN ISNULL(LISTA, 0) = 1 AND ISNULL(ORDEM_LISTA, 0) > 0 THEN ISNULL(ORDEM_LISTA, 0)
        WHEN ISNULL(LISTA, 0) = 1 AND ISNULL(ORDEM, 0) > 0 THEN ISNULL(ORDEM, 0)
        ELSE ISNULL(ORDEM_LISTA_MOBILE, 0)
    END,
    TAM_LISTA_MOBILE = CASE
        WHEN ISNULL(TAM_MOBILE, 0) > 0 THEN ISNULL(TAM_MOBILE, 5)
        WHEN ISNULL(TAM_LISTA, 0) > 0 THEN ISNULL(TAM_LISTA, 5)
        WHEN ISNULL(TAM, 0) > 0 THEN ISNULL(TAM, 5)
        ELSE ISNULL(TAM_LISTA_MOBILE, 5)
    END,
    LISTA_MOBILE_SHOW_LABEL = ISNULL(LISTA_MOBILE_SHOW_LABEL, 1),
    LISTA_MOBILE_LABEL = CASE
        WHEN LTRIM(RTRIM(ISNULL(LISTA_MOBILE_LABEL, ''))) <> '' THEN LTRIM(RTRIM(ISNULL(LISTA_MOBILE_LABEL, '')))
        ELSE LTRIM(RTRIM(ISNULL(DESCRICAO, '')))
    END
WHERE 1 = 1;
