/* GR360_CORE - Signature mensuelle forfait-jours et PDF signé */
SET XACT_ABORT ON;
GO
BEGIN TRANSACTION;
IF OBJECT_ID('dbo.COLAB_FORFAIT_JOURS_ASSINATURA', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.COLAB_FORFAIT_JOURS_ASSINATURA (
        ASSINATURASTAMP varchar(25) NOT NULL CONSTRAINT PK_COLAB_FORFAIT_JOURS_ASSINATURA PRIMARY KEY,
        PENO int NOT NULL, PEFEID int NOT NULL CONSTRAINT DF_COLAB_FORFAIT_ASSINATURA_PEFEID DEFAULT 0,
        USSTAMP varchar(25) NOT NULL CONSTRAINT DF_COLAB_FORFAIT_ASSINATURA_USSTAMP DEFAULT '', LOGIN varchar(60) NOT NULL CONSTRAINT DF_COLAB_FORFAIT_ASSINATURA_LOGIN DEFAULT '',
        ANO smallint NOT NULL, MES tinyint NOT NULL, ASSINATURA_PNG varbinary(max) NOT NULL, PDF_ASSINADO varbinary(max) NOT NULL,
        NOME_FICHEIRO varchar(160) NOT NULL CONSTRAINT DF_COLAB_FORFAIT_ASSINATURA_FICHEIRO DEFAULT '', DTASSINATURA datetime NOT NULL CONSTRAINT DF_COLAB_FORFAIT_ASSINATURA_DATA DEFAULT GETDATE(),
        CONSTRAINT UQ_COLAB_FORFAIT_ASSINATURA_PERIODO UNIQUE (PENO, PEFEID, ANO, MES), CONSTRAINT CK_COLAB_FORFAIT_ASSINATURA_MES CHECK (MES BETWEEN 1 AND 12)
    );
    CREATE INDEX IX_COLAB_FORFAIT_JOURS_ASSINATURA_COLAB ON dbo.COLAB_FORFAIT_JOURS_ASSINATURA (PENO, PEFEID, ANO DESC, MES DESC);
END;
COMMIT TRANSACTION;
GO
