/* GR360_CORE — Registo diário para colaboradores em forfait-jours */
SET XACT_ABORT ON;
GO
BEGIN TRANSACTION;

IF OBJECT_ID('dbo.COLAB_FORFAIT_JOURS_REGISTO', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.COLAB_FORFAIT_JOURS_REGISTO (
        REGISTOSTAMP varchar(25) NOT NULL CONSTRAINT PK_COLAB_FORFAIT_JOURS_REGISTO PRIMARY KEY,
        PENO int NOT NULL,
        PEFEID int NOT NULL CONSTRAINT DF_COLAB_FORFAIT_JOURS_PEFEID DEFAULT 0,
        USSTAMP varchar(25) NOT NULL CONSTRAINT DF_COLAB_FORFAIT_JOURS_USSTAMP DEFAULT '',
        LOGIN varchar(60) NOT NULL CONSTRAINT DF_COLAB_FORFAIT_JOURS_LOGIN DEFAULT '',
        DATA_REGISTO date NOT NULL,
        FRACAO_TRABALHADA decimal(2,1) NOT NULL CONSTRAINT DF_COLAB_FORFAIT_JOURS_FRACAO DEFAULT 0,
        TIPO_AUSENCIA varchar(30) NOT NULL CONSTRAINT DF_COLAB_FORFAIT_JOURS_AUSENCIA DEFAULT '',
        OBSERVACOES nvarchar(1000) NOT NULL CONSTRAINT DF_COLAB_FORFAIT_JOURS_OBS DEFAULT N'',
        DTCRI datetime NOT NULL CONSTRAINT DF_COLAB_FORFAIT_JOURS_DTCRI DEFAULT GETDATE(),
        DTALT datetime NULL,
        USERCRIACAO varchar(60) NOT NULL CONSTRAINT DF_COLAB_FORFAIT_JOURS_USERCRI DEFAULT '',
        USERALTERACAO varchar(60) NOT NULL CONSTRAINT DF_COLAB_FORFAIT_JOURS_USERALT DEFAULT '',
        VERSION int NOT NULL CONSTRAINT DF_COLAB_FORFAIT_JOURS_VERSION DEFAULT 1,
        CONSTRAINT UQ_COLAB_FORFAIT_JOURS_COLAB_DIA UNIQUE (PENO, PEFEID, DATA_REGISTO),
        CONSTRAINT CK_COLAB_FORFAIT_JOURS_FRACAO CHECK (FRACAO_TRABALHADA IN (0, 0.5, 1)),
        CONSTRAINT CK_COLAB_FORFAIT_JOURS_TIPO CHECK (TIPO_AUSENCIA IN ('', 'WEEKLY_REST', 'PAID_LEAVE', 'CONVENTIONAL_LEAVE', 'SICK_LEAVE', 'PUBLIC_HOLIDAY', 'UNEXCUSED_ABSENCE')),
        CONSTRAINT CK_COLAB_FORFAIT_JOURS_DIA CHECK ((FRACAO_TRABALHADA IN (0.5, 1) AND TIPO_AUSENCIA = '') OR (FRACAO_TRABALHADA = 0 AND TIPO_AUSENCIA <> ''))
    );
    CREATE INDEX IX_COLAB_FORFAIT_JOURS_DIA ON dbo.COLAB_FORFAIT_JOURS_REGISTO (PEFEID, DATA_REGISTO, PENO);
END;
COMMIT TRANSACTION;
GO
