IF COL_LENGTH('dbo.COLAB_DESPESA_LINHA', 'DEVOLUCAO_OBS') IS NULL
BEGIN
    ALTER TABLE dbo.COLAB_DESPESA_LINHA
    ADD DEVOLUCAO_OBS nvarchar(500) NOT NULL
        CONSTRAINT DF_COLAB_DESPESA_LINHA_DEVOLUCAO_OBS DEFAULT N'';
END
GO
