IF OBJECT_ID('dbo.DBW', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DBW (
        DBWSTAMP VARCHAR(25) NOT NULL CONSTRAINT DF_DBW_STAMP DEFAULT (LEFT(REPLACE(CONVERT(VARCHAR(36), NEWID()), '-', ''), 25)),
        NOME VARCHAR(100) NOT NULL CONSTRAINT DF_DBW_NOME DEFAULT (''),
        ATIVO BIT NOT NULL CONSTRAINT DF_DBW_ATIVO DEFAULT (1),
        COLUNA INT NOT NULL CONSTRAINT DF_DBW_COLUNA DEFAULT (1),
        ORDEM_COLUNA INT NOT NULL CONSTRAINT DF_DBW_ORDEM_COLUNA DEFAULT (0),
        LARGURA INT NULL,
        ALTURA INT NULL,
        TITULO VARCHAR(100) NOT NULL CONSTRAINT DF_DBW_TITULO DEFAULT (''),
        BACKGROUND VARCHAR(30) NOT NULL CONSTRAINT DF_DBW_BACKGROUND DEFAULT (''),
        BORDER_COLOR VARCHAR(30) NOT NULL CONSTRAINT DF_DBW_BORDER_COLOR DEFAULT (''),
        TEXT_COLOR VARCHAR(30) NOT NULL CONSTRAINT DF_DBW_TEXT_COLOR DEFAULT (''),
        FEID VARCHAR(25) NOT NULL CONSTRAINT DF_DBW_FEID DEFAULT (''),
        OUSRDATA DATETIME NOT NULL CONSTRAINT DF_DBW_OUSRDATA DEFAULT (GETDATE()),
        OUSRHORA VARCHAR(8) NOT NULL CONSTRAINT DF_DBW_OUSRHORA DEFAULT (CONVERT(VARCHAR(8), GETDATE(), 108)),
        USRCRIACAO VARCHAR(25) NOT NULL CONSTRAINT DF_DBW_USRCRIACAO DEFAULT (''),
        CONSTRAINT PK_DBW PRIMARY KEY CLUSTERED (DBWSTAMP)
    );
END;

IF OBJECT_ID('dbo.DBWL', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DBWL (
        DBWLSTAMP VARCHAR(25) NOT NULL CONSTRAINT DF_DBWL_STAMP DEFAULT (LEFT(REPLACE(CONVERT(VARCHAR(36), NEWID()), '-', ''), 25)),
        DBWSTAMP VARCHAR(25) NOT NULL CONSTRAINT DF_DBWL_DBWSTAMP DEFAULT (''),
        ORDEM INT NOT NULL CONSTRAINT DF_DBWL_ORDEM DEFAULT (0),
        TEXTO VARCHAR(100) NOT NULL CONSTRAINT DF_DBWL_TEXTO DEFAULT (''),
        URL VARCHAR(500) NOT NULL CONSTRAINT DF_DBWL_URL DEFAULT (''),
        ABRIR_NOVA_TAB BIT NOT NULL CONSTRAINT DF_DBWL_ABRIR_NOVA_TAB DEFAULT (1),
        ATIVO BIT NOT NULL CONSTRAINT DF_DBWL_ATIVO DEFAULT (1),
        COR_BACKGROUND VARCHAR(30) NOT NULL CONSTRAINT DF_DBWL_COR_BACKGROUND DEFAULT (''),
        COR_BORDER VARCHAR(30) NOT NULL CONSTRAINT DF_DBWL_COR_BORDER DEFAULT (''),
        COR_TEXTO VARCHAR(30) NOT NULL CONSTRAINT DF_DBWL_COR_TEXTO DEFAULT (''),
        CONSTRAINT PK_DBWL PRIMARY KEY CLUSTERED (DBWLSTAMP)
    );
END;

IF OBJECT_ID('dbo.DBWU', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DBWU (
        DBWUSTAMP VARCHAR(25) NOT NULL CONSTRAINT DF_DBWU_STAMP DEFAULT (LEFT(REPLACE(CONVERT(VARCHAR(36), NEWID()), '-', ''), 25)),
        DBWSTAMP VARCHAR(25) NOT NULL CONSTRAINT DF_DBWU_DBWSTAMP DEFAULT (''),
        USRSTAMP VARCHAR(25) NOT NULL CONSTRAINT DF_DBWU_USRSTAMP DEFAULT (''),
        CONSTRAINT PK_DBWU PRIMARY KEY CLUSTERED (DBWUSTAMP)
    );
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_DBWL_DBWSTAMP_ORDEM' AND object_id = OBJECT_ID('dbo.DBWL'))
    CREATE INDEX IX_DBWL_DBWSTAMP_ORDEM ON dbo.DBWL (DBWSTAMP, ATIVO, ORDEM, TEXTO);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_DBWU_USRSTAMP' AND object_id = OBJECT_ID('dbo.DBWU'))
    CREATE INDEX IX_DBWU_USRSTAMP ON dbo.DBWU (USRSTAMP, DBWSTAMP);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_DBWU_DBW_USER' AND object_id = OBJECT_ID('dbo.DBWU'))
    CREATE UNIQUE INDEX UX_DBWU_DBW_USER ON dbo.DBWU (DBWSTAMP, USRSTAMP);

