IF OBJECT_ID('dbo.DBM_TABLE_MAPPING', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DBM_TABLE_MAPPING
    (
        MAPPINGSTAMP varchar(25) NOT NULL,
        SOURCE_SCHEMA nvarchar(128) NOT NULL,
        SOURCE_TABLE nvarchar(128) NOT NULL,
        SOURCE_TABLE_KEY nvarchar(260) NOT NULL,
        ENABLED bit NOT NULL CONSTRAINT DF_DBM_TABLE_MAPPING_ENABLED DEFAULT 0,
        TARGET_SCOPE varchar(20) NOT NULL CONSTRAINT DF_DBM_TABLE_MAPPING_SCOPE DEFAULT 'FE',
        TARGET_DATABASE nvarchar(128) NOT NULL CONSTRAINT DF_DBM_TABLE_MAPPING_TARGET_DB DEFAULT '',
        TARGET_SCHEMA nvarchar(128) NOT NULL CONSTRAINT DF_DBM_TABLE_MAPPING_TARGET_SCHEMA DEFAULT 'dbo',
        TARGET_TABLE nvarchar(128) NOT NULL CONSTRAINT DF_DBM_TABLE_MAPPING_TARGET_TABLE DEFAULT '',
        NOTES nvarchar(max) NULL,
        CREATED_AT datetime2(0) NOT NULL CONSTRAINT DF_DBM_TABLE_MAPPING_CREATED DEFAULT SYSDATETIME(),
        CREATED_BY nvarchar(100) NOT NULL CONSTRAINT DF_DBM_TABLE_MAPPING_CREATED_BY DEFAULT '',
        UPDATED_AT datetime2(0) NULL,
        UPDATED_BY nvarchar(100) NOT NULL CONSTRAINT DF_DBM_TABLE_MAPPING_UPDATED_BY DEFAULT '',
        CONSTRAINT PK_DBM_TABLE_MAPPING PRIMARY KEY CLUSTERED (MAPPINGSTAMP),
        CONSTRAINT UQ_DBM_TABLE_MAPPING_SOURCE UNIQUE (SOURCE_TABLE_KEY),
        CONSTRAINT CK_DBM_TABLE_MAPPING_SCOPE CHECK (TARGET_SCOPE IN ('FE', 'FIXED'))
    );
END;

IF OBJECT_ID('dbo.DBM_FIELD_MAPPING', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DBM_FIELD_MAPPING
    (
        FIELDSTAMP varchar(25) NOT NULL,
        MAPPINGSTAMP varchar(25) NOT NULL,
        SOURCE_COLUMN nvarchar(128) NOT NULL,
        TARGET_REF varchar(10) NOT NULL CONSTRAINT DF_DBM_FIELD_MAPPING_TARGET_REF DEFAULT 'T1',
        TARGET_COLUMN nvarchar(128) NOT NULL CONSTRAINT DF_DBM_FIELD_MAPPING_TARGET DEFAULT '',
        SYNC_DIRECTION varchar(20) NOT NULL CONSTRAINT DF_DBM_FIELD_MAPPING_DIRECTION DEFAULT 'BIDIRECTIONAL',
        IS_KEY bit NOT NULL CONSTRAINT DF_DBM_FIELD_MAPPING_KEY DEFAULT 0,
        IS_REQUIRED bit NOT NULL CONSTRAINT DF_DBM_FIELD_MAPPING_REQUIRED DEFAULT 0,
        TRANSFORM_EXPR nvarchar(max) NULL,
        ORDEN int NOT NULL CONSTRAINT DF_DBM_FIELD_MAPPING_ORDEN DEFAULT 0,
        CONSTRAINT PK_DBM_FIELD_MAPPING PRIMARY KEY CLUSTERED (FIELDSTAMP),
        CONSTRAINT FK_DBM_FIELD_MAPPING_TABLE FOREIGN KEY (MAPPINGSTAMP)
            REFERENCES dbo.DBM_TABLE_MAPPING(MAPPINGSTAMP)
            ON DELETE CASCADE,
        CONSTRAINT UQ_DBM_FIELD_MAPPING_SOURCE UNIQUE (MAPPINGSTAMP, SOURCE_COLUMN),
        CONSTRAINT CK_DBM_FIELD_MAPPING_DIRECTION CHECK (SYNC_DIRECTION IN ('APP_TO_TARGET', 'TARGET_TO_APP', 'BIDIRECTIONAL'))
    );

    CREATE INDEX IX_DBM_FIELD_MAPPING_MAPPING
        ON dbo.DBM_FIELD_MAPPING (MAPPINGSTAMP, ORDEN);
END;

IF OBJECT_ID('dbo.DBM_TARGET_TABLE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DBM_TARGET_TABLE
    (
        TARGETSTAMP varchar(25) NOT NULL,
        MAPPINGSTAMP varchar(25) NOT NULL,
        TARGET_REF varchar(10) NOT NULL,
        TARGET_SCHEMA nvarchar(128) NOT NULL CONSTRAINT DF_DBM_TARGET_TABLE_SCHEMA DEFAULT 'dbo',
        TARGET_TABLE nvarchar(128) NOT NULL CONSTRAINT DF_DBM_TARGET_TABLE_TABLE DEFAULT '',
        JOIN_CONDITION nvarchar(1000) NOT NULL CONSTRAINT DF_DBM_TARGET_TABLE_JOIN DEFAULT '',
        ORDEN int NOT NULL CONSTRAINT DF_DBM_TARGET_TABLE_ORDEN DEFAULT 1,
        CREATED_AT datetime2(0) NOT NULL CONSTRAINT DF_DBM_TARGET_TABLE_CREATED DEFAULT SYSDATETIME(),
        CONSTRAINT PK_DBM_TARGET_TABLE PRIMARY KEY CLUSTERED (TARGETSTAMP),
        CONSTRAINT FK_DBM_TARGET_TABLE_MAPPING FOREIGN KEY (MAPPINGSTAMP)
            REFERENCES dbo.DBM_TABLE_MAPPING(MAPPINGSTAMP)
            ON DELETE CASCADE,
        CONSTRAINT UQ_DBM_TARGET_TABLE_REF UNIQUE (MAPPINGSTAMP, TARGET_REF)
    );

    CREATE INDEX IX_DBM_TARGET_TABLE_MAPPING
        ON dbo.DBM_TARGET_TABLE (MAPPINGSTAMP, ORDEN);
END;

IF COL_LENGTH('dbo.DBM_FIELD_MAPPING', 'TARGET_REF') IS NULL
BEGIN
    ALTER TABLE dbo.DBM_FIELD_MAPPING
    ADD TARGET_REF varchar(10) NOT NULL
        CONSTRAINT DF_DBM_FIELD_MAPPING_TARGET_REF DEFAULT 'T1';
END;

IF OBJECT_ID('dbo.DBM_TARGET_TABLE', 'U') IS NOT NULL
BEGIN
    INSERT INTO dbo.DBM_TARGET_TABLE
    (
        TARGETSTAMP,
        MAPPINGSTAMP,
        TARGET_REF,
        TARGET_SCHEMA,
        TARGET_TABLE,
        JOIN_CONDITION,
        ORDEN
    )
    SELECT
        LEFT(REPLACE(CONVERT(varchar(36), NEWID()), '-', ''), 25),
        TM.MAPPINGSTAMP,
        'T1',
        ISNULL(NULLIF(TM.TARGET_SCHEMA, ''), 'dbo'),
        ISNULL(TM.TARGET_TABLE, ''),
        '',
        1
    FROM dbo.DBM_TABLE_MAPPING TM
    WHERE NOT EXISTS (
        SELECT 1
        FROM dbo.DBM_TARGET_TABLE TT
        WHERE TT.MAPPINGSTAMP = TM.MAPPINGSTAMP
          AND TT.TARGET_REF = 'T1'
    );
END;

IF OBJECT_ID('dbo.DBM_FIELD_MAPPING', 'U') IS NOT NULL
   AND EXISTS (
       SELECT 1
       FROM sys.default_constraints
       WHERE name = 'DF_DBM_FIELD_MAPPING_DIRECTION'
         AND parent_object_id = OBJECT_ID('dbo.DBM_FIELD_MAPPING')
         AND ISNULL(definition, '') NOT LIKE '%BIDIRECTIONAL%'
   )
BEGIN
    ALTER TABLE dbo.DBM_FIELD_MAPPING
    DROP CONSTRAINT DF_DBM_FIELD_MAPPING_DIRECTION;
END;

IF OBJECT_ID('dbo.DBM_FIELD_MAPPING', 'U') IS NOT NULL
   AND NOT EXISTS (
       SELECT 1
       FROM sys.default_constraints
       WHERE name = 'DF_DBM_FIELD_MAPPING_DIRECTION'
         AND parent_object_id = OBJECT_ID('dbo.DBM_FIELD_MAPPING')
   )
BEGIN
    ALTER TABLE dbo.DBM_FIELD_MAPPING
    ADD CONSTRAINT DF_DBM_FIELD_MAPPING_DIRECTION DEFAULT 'BIDIRECTIONAL' FOR SYNC_DIRECTION;
END;
