IF OBJECT_ID('dbo.DOC_PARSER', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOC_PARSER (
        DOCPARSERSTAMP varchar(25) NOT NULL
            CONSTRAINT PK_DOC_PARSER PRIMARY KEY,
        CODIGO varchar(60) NOT NULL,
        NOME varchar(100) NOT NULL,
        DESCRICAO nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_PARSER_DESCRICAO DEFAULT N'',
        FAMILIA varchar(40) NOT NULL
            CONSTRAINT DF_DOC_PARSER_FAMILIA DEFAULT 'text_rules',
        VERSAO varchar(20) NOT NULL
            CONSTRAINT DF_DOC_PARSER_VERSAO DEFAULT '1.0',
        SCHEMA_OUTPUT_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_PARSER_SCHEMA DEFAULT N'{}',
        ATIVO bit NOT NULL
            CONSTRAINT DF_DOC_PARSER_ATIVO DEFAULT 1,
        DTCRI datetime NOT NULL
            CONSTRAINT DF_DOC_PARSER_DTCRI DEFAULT GETDATE(),
        DTALT datetime NULL,
        USERCRIACAO varchar(50) NOT NULL
            CONSTRAINT DF_DOC_PARSER_USERCRI DEFAULT '',
        USERALTERACAO varchar(50) NOT NULL
            CONSTRAINT DF_DOC_PARSER_USERALT DEFAULT ''
    );

    CREATE UNIQUE INDEX UX_DOC_PARSER_CODIGO
        ON dbo.DOC_PARSER (CODIGO);
END
GO

IF OBJECT_ID('dbo.DOC_TEMPLATE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOC_TEMPLATE (
        DOCTEMPLATESTAMP varchar(25) NOT NULL
            CONSTRAINT PK_DOC_TEMPLATE PRIMARY KEY,
        NOME varchar(120) NOT NULL,
        DESCRICAO nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_DESCRICAO DEFAULT N'',
        FORNECEDOR_NO int NULL,
        DOC_TYPE varchar(30) NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_DOC_TYPE DEFAULT 'unknown',
        IDIOMA varchar(20) NULL,
        FINGERPRINT varchar(255) NULL,
        SCORE_MINIMO_MATCH decimal(8,4) NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_SCORE DEFAULT 0.5500,
        REGRAS_IDENTIFICACAO_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_MATCH DEFAULT N'{}',
        DEFINITION_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_DEFINITION DEFAULT N'{}',
        DOCPARSERSTAMP varchar(25) NULL,
        PARSER_VERSION varchar(20) NULL,
        ATIVO bit NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_ATIVO DEFAULT 1,
        DTCRI datetime NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_DTCRI DEFAULT GETDATE(),
        DTALT datetime NULL,
        USERCRIACAO varchar(50) NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_USERCRI DEFAULT '',
        USERALTERACAO varchar(50) NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_USERALT DEFAULT ''
    );

    CREATE INDEX IX_DOC_TEMPLATE_SUPPLIER
        ON dbo.DOC_TEMPLATE (FORNECEDOR_NO, DOC_TYPE, ATIVO);
END
GO

IF OBJECT_ID('dbo.DOC_TEMPLATE_FIELD', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOC_TEMPLATE_FIELD (
        DOCTEMPLATEFIELDSTAMP varchar(25) NOT NULL
            CONSTRAINT PK_DOC_TEMPLATE_FIELD PRIMARY KEY,
        DOCTEMPLATESTAMP varchar(25) NOT NULL,
        FIELD_KEY varchar(60) NOT NULL,
        LABEL varchar(100) NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_FIELD_LABEL DEFAULT '',
        ORDEM int NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_FIELD_ORDEM DEFAULT 0,
        REQUIRED bit NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_FIELD_REQUIRED DEFAULT 0,
        MATCH_MODE varchar(30) NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_FIELD_MODE DEFAULT 'anchor_regex',
        ANCHORS_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_FIELD_ANCHORS DEFAULT N'[]',
        REGEX_PATTERN nvarchar(max) NULL,
        ALIASES_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_FIELD_ALIASES DEFAULT N'[]',
        POSTPROCESS varchar(40) NULL,
        CONFIG_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_FIELD_CONFIG DEFAULT N'{}',
        ATIVO bit NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_FIELD_ATIVO DEFAULT 1,
        DTCRI datetime NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_FIELD_DTCRI DEFAULT GETDATE(),
        DTALT datetime NULL,
        USERCRIACAO varchar(50) NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_FIELD_USERCRI DEFAULT '',
        USERALTERACAO varchar(50) NOT NULL
            CONSTRAINT DF_DOC_TEMPLATE_FIELD_USERALT DEFAULT ''
    );

    CREATE UNIQUE INDEX UX_DOC_TEMPLATE_FIELD_TEMPLATE_KEY
        ON dbo.DOC_TEMPLATE_FIELD (DOCTEMPLATESTAMP, FIELD_KEY);

    CREATE INDEX IX_DOC_TEMPLATE_FIELD_TEMPLATE
        ON dbo.DOC_TEMPLATE_FIELD (DOCTEMPLATESTAMP, ORDEM);
END
GO

IF OBJECT_ID('dbo.DOC_INBOX', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOC_INBOX (
        DOCINSTAMP varchar(25) NOT NULL
            CONSTRAINT PK_DOC_INBOX PRIMARY KEY,
        FEID int NULL,
        ANEXOSSTAMP varchar(25) NULL,
        SOURCE_TABLE varchar(50) NULL,
        SOURCE_RECSTAMP varchar(50) NULL,
        FILE_NAME varchar(260) NOT NULL
            CONSTRAINT DF_DOC_INBOX_FILE_NAME DEFAULT '',
        FILE_PATH varchar(400) NOT NULL
            CONSTRAINT DF_DOC_INBOX_FILE_PATH DEFAULT '',
        FILE_EXT varchar(20) NOT NULL
            CONSTRAINT DF_DOC_INBOX_FILE_EXT DEFAULT '',
        MIME_TYPE varchar(100) NOT NULL
            CONSTRAINT DF_DOC_INBOX_MIME DEFAULT '',
        FILE_HASH varchar(128) NULL,
        FILE_SIZE bigint NOT NULL
            CONSTRAINT DF_DOC_INBOX_FILE_SIZE DEFAULT 0,
        EXTRACTED_TEXT nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_INBOX_TEXT DEFAULT N'',
        EXTRACTION_METHOD varchar(40) NOT NULL
            CONSTRAINT DF_DOC_INBOX_EX_METHOD DEFAULT 'failed',
        EXTRACTION_QUALITY_SCORE decimal(8,4) NOT NULL
            CONSTRAINT DF_DOC_INBOX_EX_QUALITY DEFAULT 0,
        EXTRACTION_NOTES_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_INBOX_EX_NOTES DEFAULT N'{}',
        PREPROCESSED_IMAGE_PATH varchar(400) NULL,
        OCR_RAW_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_INBOX_OCR DEFAULT N'{}',
        TEXT_BLOCKS_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_INBOX_BLOCKS DEFAULT N'[]',
        PROCESSING_STAGE varchar(40) NOT NULL
            CONSTRAINT DF_DOC_INBOX_STAGE DEFAULT 'new',
        LAST_PROCESSING_ERROR nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_INBOX_LAST_ERROR DEFAULT N'',
        DOC_TYPE_DETECTED varchar(30) NOT NULL
            CONSTRAINT DF_DOC_INBOX_DOC_TYPE DEFAULT 'unknown',
        FORNECEDOR_NO int NULL,
        FORNECEDOR_NIF_DETETADO varchar(40) NULL,
        FORNECEDOR_NOME_DETETADO varchar(120) NULL,
        DOCTEMPLATESTAMP varchar(25) NULL,
        DOCPARSERSTAMP varchar(25) NULL,
        PARSER_VERSION varchar(20) NULL,
        CONFIDENCE_SCORE decimal(8,4) NOT NULL
            CONSTRAINT DF_DOC_INBOX_CONFIDENCE DEFAULT 0,
        PROCESSING_STATUS varchar(30) NOT NULL
            CONSTRAINT DF_DOC_INBOX_STATUS DEFAULT 'new',
        JSON_RESULTADO nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_INBOX_RESULT DEFAULT N'{}',
        WARNINGS_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_INBOX_WARNINGS DEFAULT N'[]',
        ERRORS_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_INBOX_ERRORS DEFAULT N'[]',
        PROCESSING_META_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_INBOX_META DEFAULT N'{}',
        DTPROC datetime NULL,
        DTCRI datetime NOT NULL
            CONSTRAINT DF_DOC_INBOX_DTCRI DEFAULT GETDATE(),
        DTALT datetime NULL,
        USERCRIACAO varchar(50) NOT NULL
            CONSTRAINT DF_DOC_INBOX_USERCRI DEFAULT '',
        USERALTERACAO varchar(50) NOT NULL
            CONSTRAINT DF_DOC_INBOX_USERALT DEFAULT ''
    );

    CREATE UNIQUE INDEX UX_DOC_INBOX_FILE_HASH
        ON dbo.DOC_INBOX (FILE_HASH)
        WHERE FILE_HASH IS NOT NULL;

    CREATE INDEX IX_DOC_INBOX_STATUS
        ON dbo.DOC_INBOX (PROCESSING_STATUS, DTCRI DESC);

    CREATE INDEX IX_DOC_INBOX_SUPPLIER
        ON dbo.DOC_INBOX (FORNECEDOR_NO, DOC_TYPE_DETECTED, DTCRI DESC);

    CREATE INDEX IX_DOC_INBOX_TEMPLATE
        ON dbo.DOC_INBOX (DOCTEMPLATESTAMP, DTCRI DESC);

    CREATE INDEX IX_DOC_INBOX_EXTRACTION_METHOD
        ON dbo.DOC_INBOX (EXTRACTION_METHOD, DTCRI DESC);
END
GO

IF COL_LENGTH('dbo.DOC_INBOX', 'EXTRACTION_METHOD') IS NULL
BEGIN
    ALTER TABLE dbo.DOC_INBOX
        ADD EXTRACTION_METHOD varchar(40) NOT NULL
            CONSTRAINT DF_DOC_INBOX_EX_METHOD DEFAULT 'failed';
END
GO

IF COL_LENGTH('dbo.DOC_INBOX', 'EXTRACTION_QUALITY_SCORE') IS NULL
BEGIN
    ALTER TABLE dbo.DOC_INBOX
        ADD EXTRACTION_QUALITY_SCORE decimal(8,4) NOT NULL
            CONSTRAINT DF_DOC_INBOX_EX_QUALITY DEFAULT 0;
END
GO

IF COL_LENGTH('dbo.DOC_INBOX', 'EXTRACTION_NOTES_JSON') IS NULL
BEGIN
    ALTER TABLE dbo.DOC_INBOX
        ADD EXTRACTION_NOTES_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_INBOX_EX_NOTES DEFAULT N'{}';
END
GO

IF COL_LENGTH('dbo.DOC_INBOX', 'PREPROCESSED_IMAGE_PATH') IS NULL
BEGIN
    ALTER TABLE dbo.DOC_INBOX
        ADD PREPROCESSED_IMAGE_PATH varchar(400) NULL;
END
GO

IF COL_LENGTH('dbo.DOC_INBOX', 'PROCESSING_STAGE') IS NULL
BEGIN
    ALTER TABLE dbo.DOC_INBOX
        ADD PROCESSING_STAGE varchar(40) NOT NULL
            CONSTRAINT DF_DOC_INBOX_STAGE DEFAULT 'new';
END
GO

IF COL_LENGTH('dbo.DOC_INBOX', 'LAST_PROCESSING_ERROR') IS NULL
BEGIN
    ALTER TABLE dbo.DOC_INBOX
        ADD LAST_PROCESSING_ERROR nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_INBOX_LAST_ERROR DEFAULT N'';
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_DOC_INBOX_EXTRACTION_METHOD'
      AND object_id = OBJECT_ID('dbo.DOC_INBOX')
)
BEGIN
    CREATE INDEX IX_DOC_INBOX_EXTRACTION_METHOD
        ON dbo.DOC_INBOX (EXTRACTION_METHOD, DTCRI DESC);
END
GO

IF OBJECT_ID('dbo.DOC_PROCESS_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOC_PROCESS_LOG (
        DOCPROCESSLOGSTAMP varchar(25) NOT NULL
            CONSTRAINT PK_DOC_PROCESS_LOG PRIMARY KEY,
        DOCINSTAMP varchar(25) NOT NULL,
        FASE varchar(40) NOT NULL,
        STATUS varchar(20) NOT NULL
            CONSTRAINT DF_DOC_PROCESS_LOG_STATUS DEFAULT 'info',
        MENSAGEM varchar(255) NOT NULL
            CONSTRAINT DF_DOC_PROCESS_LOG_MSG DEFAULT '',
        DETALHE_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_PROCESS_LOG_DETALHE DEFAULT N'{}',
        DTCRI datetime NOT NULL
            CONSTRAINT DF_DOC_PROCESS_LOG_DTCRI DEFAULT GETDATE()
    );

    CREATE INDEX IX_DOC_PROCESS_LOG_DOC
        ON dbo.DOC_PROCESS_LOG (DOCINSTAMP, DTCRI DESC);
END
GO

IF NOT EXISTS (SELECT 1 FROM dbo.DOC_PARSER WHERE CODIGO = 'TEXT_RULES_V1')
BEGIN
    INSERT INTO dbo.DOC_PARSER (
        DOCPARSERSTAMP, CODIGO, NOME, DESCRICAO, FAMILIA, VERSAO,
        SCHEMA_OUTPUT_JSON, ATIVO, DTCRI, USERCRIACAO, USERALTERACAO
    )
    VALUES (
        LEFT(CONVERT(varchar(36), NEWID()), 25),
        'TEXT_RULES_V1',
        'Text Rules Parser',
        N'Parser textual base para documentos de compra com anchors, regex e regras.',
        'text_rules',
        '1.0',
        N'{
  "document_type": "invoice|credit_note|purchase_order|delivery_note|unknown",
  "supplier": {"supplier_no": null, "tax_id": "", "name": ""},
  "customer": {"tax_id": "", "name": ""},
  "document_number": "",
  "document_date": "",
  "currency": "",
  "totals": {"net_total": 0, "tax_total": 0, "gross_total": 0},
  "taxes": [],
  "lines": [],
  "warnings": []
}',
        1,
        GETDATE(),
        'system',
        'system'
    );
END
