IF OBJECT_ID('dbo.DOC_AI_REQUIRED_FIELD', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOC_AI_REQUIRED_FIELD (
        DOC_AI_REQUIRED_FIELD_STAMP varchar(25) NOT NULL
            CONSTRAINT PK_DOC_AI_REQUIRED_FIELD PRIMARY KEY,
        DOC_CLASS varchar(30) NOT NULL,
        VIEW_CODE varchar(30) NOT NULL,
        FIELD_CODE varchar(40) NOT NULL,
        DTCRI datetime NOT NULL CONSTRAINT DF_DOC_AI_REQUIRED_DTCRI DEFAULT GETDATE(),
        DTALT datetime NULL,
        USERCRIACAO varchar(60) NOT NULL CONSTRAINT DF_DOC_AI_REQUIRED_USERCRI DEFAULT '',
        USERALTERACAO varchar(60) NOT NULL CONSTRAINT DF_DOC_AI_REQUIRED_USERALT DEFAULT ''
    );

    CREATE UNIQUE INDEX UX_DOC_AI_REQUIRED_FIELD
        ON dbo.DOC_AI_REQUIRED_FIELD (DOC_CLASS, VIEW_CODE, FIELD_CODE);
END
GO

IF OBJECT_ID('dbo.DOC_AI_REQUIRED_FIELD_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOC_AI_REQUIRED_FIELD_LOG (
        DOC_AI_REQUIRED_FIELD_LOG_STAMP varchar(25) NOT NULL
            CONSTRAINT PK_DOC_AI_REQUIRED_FIELD_LOG PRIMARY KEY,
        ACTOR_LOGIN varchar(60) NOT NULL,
        ACTION_CODE varchar(30) NOT NULL,
        RULE_STAMP varchar(25) NULL,
        BEFORE_JSON nvarchar(max) NOT NULL CONSTRAINT DF_DOC_AI_REQUIRED_LOG_BEFORE DEFAULT N'{}',
        AFTER_JSON nvarchar(max) NOT NULL CONSTRAINT DF_DOC_AI_REQUIRED_LOG_AFTER DEFAULT N'{}',
        DTCRI datetime NOT NULL CONSTRAINT DF_DOC_AI_REQUIRED_LOG_DTCRI DEFAULT GETDATE()
    );
END
GO
