IF OBJECT_ID('dbo.DOC_AI_DISTRIBUTION_RULE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOC_AI_DISTRIBUTION_RULE (
        DOC_AI_DISTRIBUTION_RULE_STAMP varchar(25) NOT NULL
            CONSTRAINT PK_DOC_AI_DISTRIBUTION_RULE PRIMARY KEY,
        DOC_CLASS varchar(30) NOT NULL,
        SOURCE_VIEW varchar(30) NOT NULL,
        DESTINATION_VIEW varchar(30) NULL,
        DESTINATION_STATE varchar(20) NOT NULL
            CONSTRAINT DF_DOC_AI_DIST_STATE DEFAULT 'none',
        TERMINAL bit NOT NULL
            CONSTRAINT DF_DOC_AI_DIST_TERMINAL DEFAULT 0,
        DTCRI datetime NOT NULL
            CONSTRAINT DF_DOC_AI_DIST_DTCRI DEFAULT GETDATE(),
        DTALT datetime NULL,
        USERCRIACAO varchar(60) NOT NULL
            CONSTRAINT DF_DOC_AI_DIST_USERCRI DEFAULT '',
        USERALTERACAO varchar(60) NOT NULL
            CONSTRAINT DF_DOC_AI_DIST_USERALT DEFAULT ''
    );

    CREATE UNIQUE INDEX UX_DOC_AI_DISTRIBUTION_RULE
        ON dbo.DOC_AI_DISTRIBUTION_RULE (DOC_CLASS, SOURCE_VIEW, DESTINATION_VIEW)
        WHERE DESTINATION_VIEW IS NOT NULL;

    CREATE UNIQUE INDEX UX_DOC_AI_DISTRIBUTION_TERMINAL
        ON dbo.DOC_AI_DISTRIBUTION_RULE (DOC_CLASS, SOURCE_VIEW)
        WHERE TERMINAL = 1;
END
GO

IF OBJECT_ID('dbo.DOC_AI_DISTRIBUTION_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOC_AI_DISTRIBUTION_LOG (
        DOC_AI_DISTRIBUTION_LOG_STAMP varchar(25) NOT NULL
            CONSTRAINT PK_DOC_AI_DISTRIBUTION_LOG PRIMARY KEY,
        ACTOR_LOGIN varchar(60) NOT NULL,
        ACTION_CODE varchar(40) NOT NULL,
        RULE_STAMP varchar(25) NULL,
        BEFORE_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_AI_DIST_LOG_BEFORE DEFAULT N'{}',
        AFTER_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_AI_DIST_LOG_AFTER DEFAULT N'{}',
        RESULT_JSON nvarchar(max) NOT NULL
            CONSTRAINT DF_DOC_AI_DIST_LOG_RESULT DEFAULT N'{}',
        DTCRI datetime NOT NULL
            CONSTRAINT DF_DOC_AI_DIST_LOG_DTCRI DEFAULT GETDATE()
    );
END
GO

IF OBJECT_ID('dbo.DOC_AI_WORKFLOW_ASSIGNMENT', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOC_AI_WORKFLOW_ASSIGNMENT (
        DOC_AI_WORKFLOW_ASSIGNMENT_STAMP varchar(25) NOT NULL
            CONSTRAINT PK_DOC_AI_WORKFLOW_ASSIGNMENT PRIMARY KEY,
        DOCINSTAMP varchar(25) NOT NULL,
        VIEW_CODE varchar(30) NOT NULL,
        STATE_CODE varchar(20) NOT NULL
            CONSTRAINT DF_DOC_AI_WORKFLOW_STATE DEFAULT 'none',
        SOURCE_VIEW varchar(30) NOT NULL
            CONSTRAINT DF_DOC_AI_WORKFLOW_SOURCE DEFAULT '',
        RULE_STAMP varchar(25) NULL,
        ATIVO bit NOT NULL
            CONSTRAINT DF_DOC_AI_WORKFLOW_ACTIVE DEFAULT 1,
        VALIDADO bit NOT NULL
            CONSTRAINT DF_DOC_AI_WORKFLOW_VALIDATED DEFAULT 0,
        DTCRI datetime NOT NULL
            CONSTRAINT DF_DOC_AI_WORKFLOW_DTCRI DEFAULT GETDATE(),
        DTALT datetime NULL,
        USERCRIACAO varchar(60) NOT NULL
            CONSTRAINT DF_DOC_AI_WORKFLOW_USERCRI DEFAULT '',
        USERALTERACAO varchar(60) NOT NULL
            CONSTRAINT DF_DOC_AI_WORKFLOW_USERALT DEFAULT ''
    );

    CREATE UNIQUE INDEX UX_DOC_AI_WORKFLOW_DOCUMENT_VIEW
        ON dbo.DOC_AI_WORKFLOW_ASSIGNMENT (DOCINSTAMP, VIEW_CODE);

    CREATE INDEX IX_DOC_AI_WORKFLOW_VIEW_ACTIVE
        ON dbo.DOC_AI_WORKFLOW_ASSIGNMENT (VIEW_CODE, ATIVO, VALIDADO)
        INCLUDE (DOCINSTAMP, STATE_CODE);
END
GO
