IF OBJECT_ID('dbo.DOC_AI_ACCESS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOC_AI_ACCESS (
        DOC_AI_ACCESS_STAMP varchar(25) NOT NULL CONSTRAINT PK_DOC_AI_ACCESS PRIMARY KEY,
        LOGIN varchar(100) NOT NULL,
        VIEW_CODE varchar(20) NOT NULL,
        ALL_ENTITIES bit NOT NULL CONSTRAINT DF_DOC_AI_VIEW_ACCESS_ALL_ENTITIES DEFAULT 1,
        CAN_CONSULT bit NOT NULL CONSTRAINT DF_DOC_AI_VIEW_ACCESS_CONSULT DEFAULT 0,
        CAN_CREATE bit NOT NULL CONSTRAINT DF_DOC_AI_VIEW_ACCESS_CREATE DEFAULT 0,
        CAN_ANALYZE bit NOT NULL CONSTRAINT DF_DOC_AI_VIEW_ACCESS_ANALYZE DEFAULT 0,
        CAN_DELETE bit NOT NULL CONSTRAINT DF_DOC_AI_VIEW_ACCESS_DELETE DEFAULT 0,
        CAN_AI bit NOT NULL CONSTRAINT DF_DOC_AI_VIEW_ACCESS_AI DEFAULT 0,
        CAN_ASSOCIATE bit NOT NULL CONSTRAINT DF_DOC_AI_VIEW_ACCESS_ASSOCIATE DEFAULT 0,
        CAN_VALIDATE bit NOT NULL CONSTRAINT DF_DOC_AI_VIEW_ACCESS_VALIDATE DEFAULT 0,
        DTCRI datetime2 NOT NULL CONSTRAINT DF_DOC_AI_VIEW_ACCESS_DTCRI DEFAULT SYSUTCDATETIME(),
        DTALT datetime2 NULL,
        USERCRIACAO varchar(100) NOT NULL CONSTRAINT DF_DOC_AI_VIEW_ACCESS_USERCRI DEFAULT '',
        USERALTERACAO varchar(100) NOT NULL CONSTRAINT DF_DOC_AI_VIEW_ACCESS_USERALT DEFAULT '',
        CONSTRAINT CK_DOC_AI_ACCESS_VIEW CHECK (VIEW_CODE IN ('home', 'management', 'accounting'))
    );

    CREATE UNIQUE INDEX UX_DOC_AI_ACCESS_LOGIN_VIEW ON dbo.DOC_AI_ACCESS (LOGIN, VIEW_CODE);
    CREATE INDEX IX_DOC_AI_ACCESS_LOGIN ON dbo.DOC_AI_ACCESS (LOGIN);

    DECLARE @InitialAccess TABLE (LOGIN varchar(100), VIEW_CODE varchar(20));
    INSERT INTO @InitialAccess (LOGIN, VIEW_CODE) VALUES
        ('sa', 'home'), ('sa', 'management'), ('sa', 'accounting'),
        ('msilva', 'home'), ('msilva', 'management'), ('msilva', 'accounting'),
        ('ldias', 'home'), ('arocha', 'management'),
        ('aelhaj', 'accounting'), ('aguimaraes', 'accounting'), ('anorinho', 'accounting'),
        ('sferreira', 'accounting'), ('srferreira', 'accounting'), ('ssampaio', 'accounting');

    INSERT INTO dbo.DOC_AI_ACCESS (
        DOC_AI_ACCESS_STAMP, LOGIN, VIEW_CODE, ALL_ENTITIES,
        CAN_CONSULT, CAN_CREATE, CAN_ANALYZE, CAN_DELETE, CAN_AI, CAN_ASSOCIATE, CAN_VALIDATE,
        USERCRIACAO
    )
    SELECT LEFT(REPLACE(CONVERT(varchar(36), NEWID()), '-', ''), 25), LOGIN, VIEW_CODE, 1,
           1, 1, 1, 1, 1, 1, 1, 'SYSTEM'
    FROM @InitialAccess;
END;
GO

IF OBJECT_ID('dbo.DOC_AI_ACCESS_ENTITY', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOC_AI_ACCESS_ENTITY (
        DOC_AI_ACCESS_ENTITY_STAMP varchar(25) NOT NULL CONSTRAINT PK_DOC_AI_ACCESS_ENTITY PRIMARY KEY,
        DOC_AI_ACCESS_STAMP varchar(25) NOT NULL,
        FEID int NOT NULL,
        DTCRI datetime2 NOT NULL CONSTRAINT DF_DOC_AI_ACCESS_ENTITY_DTCRI DEFAULT SYSUTCDATETIME(),
        USERCRIACAO varchar(100) NOT NULL CONSTRAINT DF_DOC_AI_ACCESS_ENTITY_USERCRI DEFAULT '',
        CONSTRAINT FK_DOC_AI_ACCESS_ENTITY_ACCESS FOREIGN KEY (DOC_AI_ACCESS_STAMP)
            REFERENCES dbo.DOC_AI_ACCESS (DOC_AI_ACCESS_STAMP) ON DELETE CASCADE
    );
    CREATE UNIQUE INDEX UX_DOC_AI_ACCESS_ENTITY ON dbo.DOC_AI_ACCESS_ENTITY (DOC_AI_ACCESS_STAMP, FEID);
END;
GO

IF OBJECT_ID('dbo.DOC_AI_ACCESS_ADMIN', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOC_AI_ACCESS_ADMIN (
        DOC_AI_ACCESS_ADMIN_STAMP varchar(25) NOT NULL CONSTRAINT PK_DOC_AI_ACCESS_ADMIN PRIMARY KEY,
        LOGIN varchar(100) NOT NULL,
        ATIVO bit NOT NULL CONSTRAINT DF_DOC_AI_ACCESS_ADMIN_ACTIVE DEFAULT 1,
        DTCRI datetime2 NOT NULL CONSTRAINT DF_DOC_AI_ACCESS_ADMIN_DTCRI DEFAULT SYSUTCDATETIME(),
        DTALT datetime2 NULL,
        USERCRIACAO varchar(100) NOT NULL CONSTRAINT DF_DOC_AI_ACCESS_ADMIN_USERCRI DEFAULT '',
        USERALTERACAO varchar(100) NOT NULL CONSTRAINT DF_DOC_AI_ACCESS_ADMIN_USERALT DEFAULT ''
    );
    CREATE UNIQUE INDEX UX_DOC_AI_ACCESS_ADMIN_LOGIN ON dbo.DOC_AI_ACCESS_ADMIN (LOGIN);
    INSERT INTO dbo.DOC_AI_ACCESS_ADMIN (DOC_AI_ACCESS_ADMIN_STAMP, LOGIN, ATIVO, USERCRIACAO)
    VALUES
        (LEFT(REPLACE(CONVERT(varchar(36), NEWID()), '-', ''), 25), 'msilva', 1, 'SYSTEM'),
        (LEFT(REPLACE(CONVERT(varchar(36), NEWID()), '-', ''), 25), 'sa', 1, 'SYSTEM');
END;
GO

IF OBJECT_ID('dbo.DOC_AI_ACCESS_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOC_AI_ACCESS_LOG (
        DOC_AI_ACCESS_LOG_STAMP varchar(25) NOT NULL CONSTRAINT PK_DOC_AI_ACCESS_LOG PRIMARY KEY,
        ACTOR_LOGIN varchar(100) NOT NULL,
        TARGET_LOGIN varchar(100) NOT NULL,
        VIEW_CODE varchar(20) NOT NULL CONSTRAINT DF_DOC_AI_ACCESS_LOG_VIEW DEFAULT '',
        ACTION_CODE varchar(30) NOT NULL,
        BEFORE_JSON nvarchar(max) NOT NULL CONSTRAINT DF_DOC_AI_ACCESS_LOG_BEFORE DEFAULT N'{}',
        AFTER_JSON nvarchar(max) NOT NULL CONSTRAINT DF_DOC_AI_ACCESS_LOG_AFTER DEFAULT N'{}',
        DTUTC datetime2 NOT NULL CONSTRAINT DF_DOC_AI_ACCESS_LOG_DTUTC DEFAULT SYSUTCDATETIME()
    );
    CREATE INDEX IX_DOC_AI_ACCESS_LOG_TARGET ON dbo.DOC_AI_ACCESS_LOG (TARGET_LOGIN, DTUTC DESC);
END;
GO
