IF OBJECT_ID('dbo.EMAIL_PROFILES', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.EMAIL_PROFILES
    (
        ID int IDENTITY(1,1) NOT NULL,
        NOME_PERFIL varchar(100) NOT NULL,
        DESCRICAO varchar(255) NULL,
        EMAIL_FROM varchar(255) NOT NULL,
        NOME_FROM varchar(255) NULL,
        SMTP_HOST varchar(255) NOT NULL,
        SMTP_PORT int NOT NULL,
        SMTP_USER varchar(255) NULL,
        SMTP_PASSWORD_ENC varchar(max) NULL,
        USA_TLS bit NOT NULL CONSTRAINT DF_EMAIL_PROFILES_TLS DEFAULT 1,
        USA_SSL bit NOT NULL CONSTRAINT DF_EMAIL_PROFILES_SSL DEFAULT 0,
        ATIVO bit NOT NULL CONSTRAINT DF_EMAIL_PROFILES_ATIVO DEFAULT 1,
        DEFAULT_PROFILE bit NOT NULL CONSTRAINT DF_EMAIL_PROFILES_DEFAULT DEFAULT 0,
        DATA_CRIACAO datetime NOT NULL CONSTRAINT DF_EMAIL_PROFILES_DCRI DEFAULT GETDATE(),
        DATA_ALTERACAO datetime NULL,
        CONSTRAINT PK_EMAIL_PROFILES PRIMARY KEY CLUSTERED (ID),
        CONSTRAINT UQ_EMAIL_PROFILES_NOME UNIQUE (NOME_PERFIL)
    );
END;

IF OBJECT_ID('dbo.EMAIL_QUEUE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.EMAIL_QUEUE
    (
        ID bigint IDENTITY(1,1) NOT NULL,
        PROFILE_ID int NOT NULL,
        FROM_EMAIL varchar(255) NULL,
        FROM_NAME varchar(255) NULL,
        TO_EMAILS varchar(max) NOT NULL,
        CC_EMAILS varchar(max) NULL,
        BCC_EMAILS varchar(max) NULL,
        SUBJECT varchar(500) NOT NULL,
        BODY_HTML varchar(max) NULL,
        BODY_TEXT varchar(max) NULL,
        PRIORIDADE int NOT NULL CONSTRAINT DF_EMAIL_QUEUE_PRIORIDADE DEFAULT 5,
        ESTADO varchar(30) NOT NULL CONSTRAINT DF_EMAIL_QUEUE_ESTADO DEFAULT 'PENDENTE',
        TENTATIVAS int NOT NULL CONSTRAINT DF_EMAIL_QUEUE_TENTATIVAS DEFAULT 0,
        MAX_TENTATIVAS int NOT NULL CONSTRAINT DF_EMAIL_QUEUE_MAXTENT DEFAULT 3,
        ERRO_ULTIMA_TENTATIVA varchar(max) NULL,
        DATA_AGENDADA datetime NULL,
        DATA_CRIACAO datetime NOT NULL CONSTRAINT DF_EMAIL_QUEUE_DCRI DEFAULT GETDATE(),
        DATA_ULTIMA_TENTATIVA datetime NULL,
        DATA_ENVIO datetime NULL,
        CRIADO_POR varchar(100) NULL,
        CONTEXTO varchar(100) NULL,
        CONTEXTO_ID varchar(100) NULL,
        CONSTRAINT PK_EMAIL_QUEUE PRIMARY KEY CLUSTERED (ID),
        CONSTRAINT FK_EMAIL_QUEUE_PROFILE FOREIGN KEY (PROFILE_ID)
            REFERENCES dbo.EMAIL_PROFILES(ID),
        CONSTRAINT CK_EMAIL_QUEUE_ESTADO CHECK (ESTADO IN ('PENDENTE', 'A_ENVIAR', 'ENVIADO', 'ERRO', 'CANCELADO'))
    );
END;

IF OBJECT_ID('dbo.EMAIL_ATTACHMENTS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.EMAIL_ATTACHMENTS
    (
        ID bigint IDENTITY(1,1) NOT NULL,
        EMAIL_ID bigint NOT NULL,
        FILE_NAME varchar(255) NOT NULL,
        FILE_PATH varchar(1000) NULL,
        FILE_CONTENT varbinary(max) NULL,
        MIME_TYPE varchar(255) NULL,
        TAMANHO_BYTES bigint NULL,
        DATA_CRIACAO datetime NOT NULL CONSTRAINT DF_EMAIL_ATTACHMENTS_DCRI DEFAULT GETDATE(),
        CONSTRAINT PK_EMAIL_ATTACHMENTS PRIMARY KEY CLUSTERED (ID),
        CONSTRAINT FK_EMAIL_ATTACHMENTS_EMAIL FOREIGN KEY (EMAIL_ID)
            REFERENCES dbo.EMAIL_QUEUE(ID)
            ON DELETE CASCADE
    );
END;

IF OBJECT_ID('dbo.EMAIL_LOG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.EMAIL_LOG
    (
        ID bigint IDENTITY(1,1) NOT NULL,
        EMAIL_ID bigint NOT NULL,
        DATA_TENTATIVA datetime NOT NULL CONSTRAINT DF_EMAIL_LOG_DTENT DEFAULT GETDATE(),
        RESULTADO varchar(30) NOT NULL,
        MENSAGEM varchar(max) NULL,
        SMTP_RESPONSE varchar(max) NULL,
        CONSTRAINT PK_EMAIL_LOG PRIMARY KEY CLUSTERED (ID),
        CONSTRAINT FK_EMAIL_LOG_EMAIL FOREIGN KEY (EMAIL_ID)
            REFERENCES dbo.EMAIL_QUEUE(ID)
            ON DELETE CASCADE
    );
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_EMAIL_QUEUE_PROCESS' AND object_id = OBJECT_ID('dbo.EMAIL_QUEUE'))
BEGIN
    CREATE INDEX IX_EMAIL_QUEUE_PROCESS
        ON dbo.EMAIL_QUEUE (ESTADO, DATA_AGENDADA, PRIORIDADE, DATA_CRIACAO);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_EMAIL_QUEUE_PROFILE' AND object_id = OBJECT_ID('dbo.EMAIL_QUEUE'))
BEGIN
    CREATE INDEX IX_EMAIL_QUEUE_PROFILE
        ON dbo.EMAIL_QUEUE (PROFILE_ID);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_EMAIL_ATTACHMENTS_EMAIL' AND object_id = OBJECT_ID('dbo.EMAIL_ATTACHMENTS'))
BEGIN
    CREATE INDEX IX_EMAIL_ATTACHMENTS_EMAIL
        ON dbo.EMAIL_ATTACHMENTS (EMAIL_ID);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_EMAIL_LOG_EMAIL' AND object_id = OBJECT_ID('dbo.EMAIL_LOG'))
BEGIN
    CREATE INDEX IX_EMAIL_LOG_EMAIL
        ON dbo.EMAIL_LOG (EMAIL_ID);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_EMAIL_PROFILES_DEFAULT' AND object_id = OBJECT_ID('dbo.EMAIL_PROFILES'))
BEGIN
    CREATE UNIQUE INDEX UX_EMAIL_PROFILES_DEFAULT
        ON dbo.EMAIL_PROFILES (DEFAULT_PROFILE)
        WHERE DEFAULT_PROFILE = 1;
END;
