IF COL_LENGTH('dbo.FE', 'E_CLUSTER') IS NULL
BEGIN
    ALTER TABLE dbo.FE
    ADD E_CLUSTER bit NOT NULL
        CONSTRAINT DF_FE_E_CLUSTER DEFAULT 0;
END

IF OBJECT_ID('dbo.FE_CLUSTER_ENTIDADES', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.FE_CLUSTER_ENTIDADES
    (
        FECLUSTERENTSTAMP varchar(25) NOT NULL,
        FESTAMP_CLUSTER   varchar(25) NOT NULL,
        FESTAMP_ENTIDADE  varchar(25) NOT NULL,
        DTCRI             datetime2(0) NOT NULL
            CONSTRAINT DF_FE_CLUSTER_ENTIDADES_DTCRI DEFAULT GETDATE(),
        DTALT             datetime2(0) NULL,
        USERCRIACAO       varchar(50) NOT NULL
            CONSTRAINT DF_FE_CLUSTER_ENTIDADES_USERCRIACAO DEFAULT '',
        USERALTERACAO     varchar(50) NOT NULL
            CONSTRAINT DF_FE_CLUSTER_ENTIDADES_USERALTERACAO DEFAULT '',
        CONSTRAINT PK_FE_CLUSTER_ENTIDADES PRIMARY KEY (FECLUSTERENTSTAMP),
        CONSTRAINT CK_FE_CLUSTER_ENTIDADES_SELF CHECK (FESTAMP_CLUSTER <> FESTAMP_ENTIDADE)
    );
END

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.FE_CLUSTER_ENTIDADES')
      AND name = 'UX_FE_CLUSTER_ENTIDADES_CLUSTER_ENTIDADE'
)
BEGIN
    ALTER TABLE dbo.FE_CLUSTER_ENTIDADES
    ADD CONSTRAINT UX_FE_CLUSTER_ENTIDADES_CLUSTER_ENTIDADE
        UNIQUE (FESTAMP_CLUSTER, FESTAMP_ENTIDADE);
END

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.FE_CLUSTER_ENTIDADES')
      AND name = 'IX_FE_CLUSTER_ENTIDADES_CLUSTER'
)
BEGIN
    CREATE INDEX IX_FE_CLUSTER_ENTIDADES_CLUSTER
    ON dbo.FE_CLUSTER_ENTIDADES (FESTAMP_CLUSTER);
END

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.FE_CLUSTER_ENTIDADES')
      AND name = 'IX_FE_CLUSTER_ENTIDADES_ENTIDADE'
)
BEGIN
    CREATE INDEX IX_FE_CLUSTER_ENTIDADES_ENTIDADE
    ON dbo.FE_CLUSTER_ENTIDADES (FESTAMP_ENTIDADE);
END

IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE parent_object_id = OBJECT_ID('dbo.FE_CLUSTER_ENTIDADES')
      AND name = 'FK_FE_CLUSTER_ENTIDADES_CLUSTER'
)
BEGIN
    ALTER TABLE dbo.FE_CLUSTER_ENTIDADES
    ADD CONSTRAINT FK_FE_CLUSTER_ENTIDADES_CLUSTER
        FOREIGN KEY (FESTAMP_CLUSTER) REFERENCES dbo.FE(FESTAMP);
END

IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE parent_object_id = OBJECT_ID('dbo.FE_CLUSTER_ENTIDADES')
      AND name = 'FK_FE_CLUSTER_ENTIDADES_ENTIDADE'
)
BEGIN
    ALTER TABLE dbo.FE_CLUSTER_ENTIDADES
    ADD CONSTRAINT FK_FE_CLUSTER_ENTIDADES_ENTIDADE
        FOREIGN KEY (FESTAMP_ENTIDADE) REFERENCES dbo.FE(FESTAMP);
END

IF OBJECT_ID('dbo.TR_FE_CLUSTER_ENTIDADES_VALIDATE', 'TR') IS NULL
EXEC('CREATE TRIGGER dbo.TR_FE_CLUSTER_ENTIDADES_VALIDATE ON dbo.FE_CLUSTER_ENTIDADES
      AFTER INSERT, UPDATE
      AS
      BEGIN
          SET NOCOUNT ON;
      END');

ALTER TRIGGER dbo.TR_FE_CLUSTER_ENTIDADES_VALIDATE
ON dbo.FE_CLUSTER_ENTIDADES
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1
        FROM inserted I
        LEFT JOIN dbo.FE CL ON CL.FESTAMP = I.FESTAMP_CLUSTER
        LEFT JOIN dbo.FE EN ON EN.FESTAMP = I.FESTAMP_ENTIDADE
        WHERE CL.FESTAMP IS NULL
           OR EN.FESTAMP IS NULL
           OR ISNULL(CL.E_CLUSTER, 0) <> 1
           OR ISNULL(EN.E_CLUSTER, 0) = 1
           OR I.FESTAMP_CLUSTER = I.FESTAMP_ENTIDADE
    )
    BEGIN
        RAISERROR('Associacao de cluster FE invalida.', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END
END
