IF COL_LENGTH('dbo.FTS', 'IS_DOC_TRANSPORTE') IS NULL
BEGIN
    ALTER TABLE dbo.FTS
    ADD IS_DOC_TRANSPORTE BIT NOT NULL
        CONSTRAINT DF_FTS_IS_DOC_TRANSPORTE DEFAULT 0;
END
GO

IF COL_LENGTH('dbo.FT', 'IS_DOC_TRANSPORTE') IS NULL
BEGIN
    ALTER TABLE dbo.FT
    ADD IS_DOC_TRANSPORTE BIT NOT NULL
        CONSTRAINT DF_FT_IS_DOC_TRANSPORTE DEFAULT 0;
END
GO

IF COL_LENGTH('dbo.FT', 'LOCAL_CARGA_ID') IS NULL
BEGIN
    ALTER TABLE dbo.FT
    ADD LOCAL_CARGA_ID VARCHAR(25) NOT NULL
        CONSTRAINT DF_FT_LOCAL_CARGA_ID DEFAULT '';
END
GO

IF COL_LENGTH('dbo.FT', 'LOCAL_DESCARGA_ID') IS NULL
BEGIN
    ALTER TABLE dbo.FT
    ADD LOCAL_DESCARGA_ID VARCHAR(25) NOT NULL
        CONSTRAINT DF_FT_LOCAL_DESCARGA_ID DEFAULT '';
END
GO

IF COL_LENGTH('dbo.FT', 'DATA_HORA_INICIO_TRANSPORTE') IS NULL
BEGIN
    ALTER TABLE dbo.FT
    ADD DATA_HORA_INICIO_TRANSPORTE DATETIME NULL;
END
GO

IF COL_LENGTH('dbo.FT', 'MATRICULA') IS NULL
BEGIN
    ALTER TABLE dbo.FT
    ADD MATRICULA VARCHAR(20) NOT NULL
        CONSTRAINT DF_FT_MATRICULA DEFAULT '';
END
GO

IF COL_LENGTH('dbo.FT', 'CODIGO_AT') IS NULL
BEGIN
    ALTER TABLE dbo.FT
    ADD CODIGO_AT VARCHAR(50) NOT NULL
        CONSTRAINT DF_FT_CODIGO_AT DEFAULT '';
END
GO

IF COL_LENGTH('dbo.FT', 'DOC_TRANSPORTE_ESTADO') IS NULL
BEGIN
    ALTER TABLE dbo.FT
    ADD DOC_TRANSPORTE_ESTADO VARCHAR(20) NOT NULL
        CONSTRAINT DF_FT_DOC_TRANSPORTE_ESTADO DEFAULT 'RASCUNHO';
END
GO

IF COL_LENGTH('dbo.FT', 'DATA_IMPRESSAO_FINAL') IS NULL
BEGIN
    ALTER TABLE dbo.FT
    ADD DATA_IMPRESSAO_FINAL DATETIME NULL;
END
GO

IF COL_LENGTH('dbo.FT', 'USER_IMPRESSAO_FINAL') IS NULL
BEGIN
    ALTER TABLE dbo.FT
    ADD USER_IMPRESSAO_FINAL VARCHAR(50) NOT NULL
        CONSTRAINT DF_FT_USER_IMPRESSAO_FINAL DEFAULT '';
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_FT_DOC_TRANSPORTE_ESTADO'
      AND parent_object_id = OBJECT_ID('dbo.FT')
)
BEGIN
    ALTER TABLE dbo.FT
    ADD CONSTRAINT CK_FT_DOC_TRANSPORTE_ESTADO
    CHECK (DOC_TRANSPORTE_ESTADO IN ('RASCUNHO', 'EMITIDO', 'PRONTO', 'IMPRESSO'));
END
GO

IF OBJECT_ID('dbo.LOCAIS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.LOCAIS (
        LOCALSTAMP VARCHAR(25) NOT NULL
            CONSTRAINT DF_LOCAIS_LOCALSTAMP DEFAULT LEFT(CONVERT(VARCHAR(36), NEWID()), 25),
        NO INT NOT NULL
            CONSTRAINT DF_LOCAIS_NO DEFAULT 0,
        FEID INT NOT NULL
            CONSTRAINT DF_LOCAIS_FEID DEFAULT 0,
        DESIGNACAO VARCHAR(100) NOT NULL
            CONSTRAINT DF_LOCAIS_DESIGNACAO DEFAULT '',
        MORADA VARCHAR(200) NOT NULL
            CONSTRAINT DF_LOCAIS_MORADA DEFAULT '',
        MORADA2 VARCHAR(200) NOT NULL
            CONSTRAINT DF_LOCAIS_MORADA2 DEFAULT '',
        CP VARCHAR(20) NOT NULL
            CONSTRAINT DF_LOCAIS_CP DEFAULT '',
        LOCALIDADE VARCHAR(100) NOT NULL
            CONSTRAINT DF_LOCAIS_LOCALIDADE DEFAULT '',
        PAIS VARCHAR(50) NOT NULL
            CONSTRAINT DF_LOCAIS_PAIS DEFAULT '',
        ATIVO BIT NOT NULL
            CONSTRAINT DF_LOCAIS_ATIVO DEFAULT 1,
        CONSTRAINT PK_LOCAIS PRIMARY KEY (LOCALSTAMP)
    );
END
GO

IF EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_LOCAIS_OWNER'
      AND parent_object_id = OBJECT_ID('dbo.LOCAIS')
)
BEGIN
    ALTER TABLE dbo.LOCAIS
    DROP CONSTRAINT CK_LOCAIS_OWNER;
END
GO

IF OBJECT_ID('dbo.LOCAIS', 'U') IS NOT NULL
BEGIN
    ALTER TABLE dbo.LOCAIS
    ADD CONSTRAINT CK_LOCAIS_OWNER
    CHECK (
        FEID > 0
        AND NO >= 0
    );
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_LOCAIS_NO'
      AND object_id = OBJECT_ID('dbo.LOCAIS')
)
BEGIN
    CREATE INDEX IX_LOCAIS_NO
    ON dbo.LOCAIS (NO, ATIVO, DESIGNACAO);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_LOCAIS_FEID'
      AND object_id = OBJECT_ID('dbo.LOCAIS')
)
BEGIN
    CREATE INDEX IX_LOCAIS_FEID
    ON dbo.LOCAIS (FEID, ATIVO, DESIGNACAO);
END
GO
