IF COL_LENGTH('dbo.FT', 'MOTIVO_REFERENCIA') IS NULL
BEGIN
    ALTER TABLE dbo.FT
    ADD MOTIVO_REFERENCIA NVARCHAR(200) NOT NULL
        CONSTRAINT DF_FT_MOTIVO_REFERENCIA DEFAULT N'';
END
GO

IF COL_LENGTH('dbo.FT', 'FTSTAMP_ORIGEM') IS NULL
BEGIN
    ALTER TABLE dbo.FT
    ADD FTSTAMP_ORIGEM VARCHAR(25) NOT NULL
        CONSTRAINT DF_FT_FTSTAMP_ORIGEM_NC DEFAULT '';
END
GO

IF COL_LENGTH('dbo.FT', 'TIPODOC_ORIGEM') IS NULL
BEGIN
    ALTER TABLE dbo.FT
    ADD TIPODOC_ORIGEM VARCHAR(10) NOT NULL
        CONSTRAINT DF_FT_TIPODOC_ORIGEM_NC DEFAULT '';
END
GO

IF COL_LENGTH('dbo.FT', 'NUMDOC_ORIGEM') IS NULL
BEGIN
    ALTER TABLE dbo.FT
    ADD NUMDOC_ORIGEM VARCHAR(30) NOT NULL
        CONSTRAINT DF_FT_NUMDOC_ORIGEM_NC DEFAULT '';
END
GO

IF COL_LENGTH('dbo.FT', 'DATA_ORIGEM') IS NULL
BEGIN
    ALTER TABLE dbo.FT
    ADD DATA_ORIGEM DATE NULL;
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_FT_FTSTAMP_ORIGEM'
      AND object_id = OBJECT_ID('dbo.FT')
)
BEGIN
    CREATE INDEX IX_FT_FTSTAMP_ORIGEM
    ON dbo.FT (FTSTAMP_ORIGEM);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_FT_ORIGEM_SELF'
      AND parent_object_id = OBJECT_ID('dbo.FT')
)
BEGIN
    ALTER TABLE dbo.FT
    ADD CONSTRAINT CK_FT_ORIGEM_SELF
    CHECK (FTSTAMP_ORIGEM = '' OR FTSTAMP_ORIGEM <> FTSTAMP);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.check_constraints
    WHERE name = 'CK_FT_ORIGEM_CAMPOS'
      AND parent_object_id = OBJECT_ID('dbo.FT')
)
BEGIN
    ALTER TABLE dbo.FT
    ADD CONSTRAINT CK_FT_ORIGEM_CAMPOS
    CHECK (
        (FTSTAMP_ORIGEM = '' AND TIPODOC_ORIGEM = '' AND NUMDOC_ORIGEM = '' AND DATA_ORIGEM IS NULL)
        OR
        (FTSTAMP_ORIGEM <> '' AND TIPODOC_ORIGEM <> '' AND NUMDOC_ORIGEM <> '' AND DATA_ORIGEM IS NOT NULL)
    );
END
GO

IF COL_LENGTH('dbo.FI', 'FISTAMP_ORIGEM') IS NULL
BEGIN
    ALTER TABLE dbo.FI
    ADD FISTAMP_ORIGEM VARCHAR(25) NOT NULL
        CONSTRAINT DF_FI_FISTAMP_ORIGEM DEFAULT '';
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_FI_FISTAMP_ORIGEM'
      AND object_id = OBJECT_ID('dbo.FI')
)
BEGIN
    CREATE INDEX IX_FI_FISTAMP_ORIGEM
    ON dbo.FI (FISTAMP_ORIGEM);
END
GO
