IF COL_LENGTH('dbo.FT', 'SYSTEM_ENTRY_DATE') IS NULL
BEGIN
    ALTER TABLE dbo.FT
    ADD SYSTEM_ENTRY_DATE DATETIME NULL;
END
GO

UPDATE dbo.FT
SET SYSTEM_ENTRY_DATE = ISNULL(SYSTEM_ENTRY_DATE, ISNULL(DTAlteracao, DTCriacao))
WHERE SYSTEM_ENTRY_DATE IS NULL;
GO
