IF COL_LENGTH('dbo.FTS', 'CODIGO_VALIDACAO_AT') IS NULL
BEGIN
    ALTER TABLE dbo.FTS
    ADD CODIGO_VALIDACAO_AT VARCHAR(50) NOT NULL
        CONSTRAINT DF_FTS_CODIGO_VALIDACAO_AT DEFAULT '';
END
GO
