SET NOCOUNT ON;

IF OBJECT_ID('dbo.GR_TICKET_API_CLIENT', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.GR_TICKET_API_CLIENT
    (
        CLIENTSTAMP       varchar(25)  NOT NULL,
        CLIENT_ID         varchar(50)  NOT NULL,
        NOME              varchar(100) NOT NULL CONSTRAINT DF_GR_TICKET_API_CLIENT_NOME DEFAULT (''),
        TOKEN_HASH        char(64)     NOT NULL,
        ATIVO             bit          NOT NULL CONSTRAINT DF_GR_TICKET_API_CLIENT_ATIVO DEFAULT (1),
        PODE_CRIAR        bit          NOT NULL CONSTRAINT DF_GR_TICKET_API_CLIENT_CRIAR DEFAULT (1),
        PODE_LER          bit          NOT NULL CONSTRAINT DF_GR_TICKET_API_CLIENT_LER DEFAULT (1),
        PODE_LER_TODOS    bit          NOT NULL CONSTRAINT DF_GR_TICKET_API_CLIENT_LER_TODOS DEFAULT (0),
        PODE_ATUALIZAR    bit          NOT NULL CONSTRAINT DF_GR_TICKET_API_CLIENT_ATUALIZAR DEFAULT (0),
        CRIADO_UTC        datetime2(3) NOT NULL CONSTRAINT DF_GR_TICKET_API_CLIENT_CRIADO DEFAULT (SYSUTCDATETIME()),
        ULTIMO_USO_UTC    datetime2(3) NULL,
        CONSTRAINT PK_GR_TICKET_API_CLIENT PRIMARY KEY (CLIENTSTAMP),
        CONSTRAINT UQ_GR_TICKET_API_CLIENT_ID UNIQUE (CLIENT_ID),
        CONSTRAINT UQ_GR_TICKET_API_TOKEN_HASH UNIQUE (TOKEN_HASH)
    );
END;

IF COL_LENGTH('dbo.GR_TICKET_API_CLIENT', 'PODE_ATUALIZAR') IS NULL
BEGIN
    ALTER TABLE dbo.GR_TICKET_API_CLIENT
        ADD PODE_ATUALIZAR bit NOT NULL
            CONSTRAINT DF_GR_TICKET_API_CLIENT_ATUALIZAR DEFAULT (0);
END;

IF COL_LENGTH('dbo.TK', 'ORIGEM_API') IS NULL
    ALTER TABLE dbo.TK ADD ORIGEM_API varchar(50) NULL;

IF COL_LENGTH('dbo.TK', 'REFERENCIA_EXTERNA') IS NULL
    ALTER TABLE dbo.TK ADD REFERENCIA_EXTERNA varchar(100) NULL;

UPDATE dbo.TK
SET FEID = 1
WHERE ISNULL(FEID, 0) <> 1;

UPDATE dbo.GR_TICKET_API_CLIENT
SET PODE_ATUALIZAR = 1
WHERE CLIENT_ID = 'mickael-codex';

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.TK')
      AND name = 'IX_TK_ORIGEM_REFERENCIA'
)
BEGIN
    EXEC(N'
        CREATE INDEX IX_TK_ORIGEM_REFERENCIA
            ON dbo.TK (ORIGEM_API, REFERENCIA_EXTERNA)
            WHERE ORIGEM_API IS NOT NULL AND REFERENCIA_EXTERNA IS NOT NULL
    ');
END;
