/*
  GR360_LOG — registo central de atividade da aplicação e sincronizações.
  Executar no SQL Server da GR360 (10.0.1.12). Pode ser repetido em segurança.
*/

USE master;
GO

IF DB_ID(N'GR360_LOG') IS NULL
BEGIN
    CREATE DATABASE GR360_LOG;
END
GO

USE GR360_LOG;
GO

IF OBJECT_ID(N'dbo.LOGAPP', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LOGAPP
    (
        LOGAPP_ID bigint IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_LOGAPP PRIMARY KEY,
        LOGAPPSTAMP varchar(25) NOT NULL
            CONSTRAINT UQ_LOGAPP_STAMP UNIQUE,
        OCCURRED_AT_UTC datetime2(3) NOT NULL
            CONSTRAINT DF_LOGAPP_OCCURRED DEFAULT SYSUTCDATETIME(),
        CORRELATION_ID uniqueidentifier NULL,
        APP_NAME varchar(80) NOT NULL
            CONSTRAINT DF_LOGAPP_APP DEFAULT 'APP_WEB',
        ENVIRONMENT varchar(30) NOT NULL
            CONSTRAINT DF_LOGAPP_ENVIRONMENT DEFAULT 'production',
        ACTOR_LOGIN varchar(100) NULL,
        ACTOR_USSTAMP varchar(25) NULL,
        REQUEST_METHOD varchar(10) NULL,
        REQUEST_PATH nvarchar(500) NULL,
        CLIENT_IP varchar(64) NULL,
        DATABASE_NAME sysname NOT NULL,
        SCHEMA_NAME sysname NOT NULL
            CONSTRAINT DF_LOGAPP_SCHEMA DEFAULT 'dbo',
        TABLE_NAME sysname NOT NULL,
        ACTION varchar(10) NOT NULL,
        RECORD_KEY nvarchar(max) NOT NULL
            CONSTRAINT DF_LOGAPP_RECORD_KEY DEFAULT N'{}',
        BEFORE_DATA nvarchar(max) NULL,
        AFTER_DATA nvarchar(max) NULL,
        CHANGED_DATA nvarchar(max) NULL,
        QUERY_TEXT nvarchar(max) NULL,
        STATUS varchar(20) NOT NULL
            CONSTRAINT DF_LOGAPP_STATUS DEFAULT 'success',
        ERROR_MESSAGE nvarchar(2000) NULL,
        METADATA nvarchar(max) NULL,
        CONSTRAINT CK_LOGAPP_ACTION CHECK (ACTION IN ('INSERT', 'UPDATE', 'DELETE', 'SELECT')),
        CONSTRAINT CK_LOGAPP_STATUS CHECK (STATUS IN ('started', 'success', 'failed', 'skipped')),
        CONSTRAINT CK_LOGAPP_RECORD_KEY_JSON CHECK (ISJSON(RECORD_KEY) = 1),
        CONSTRAINT CK_LOGAPP_BEFORE_JSON CHECK (BEFORE_DATA IS NULL OR ISJSON(BEFORE_DATA) = 1),
        CONSTRAINT CK_LOGAPP_AFTER_JSON CHECK (AFTER_DATA IS NULL OR ISJSON(AFTER_DATA) = 1),
        CONSTRAINT CK_LOGAPP_CHANGED_JSON CHECK (CHANGED_DATA IS NULL OR ISJSON(CHANGED_DATA) = 1),
        CONSTRAINT CK_LOGAPP_METADATA_JSON CHECK (METADATA IS NULL OR ISJSON(METADATA) = 1)
    );

    CREATE INDEX IX_LOGAPP_OCCURRED
        ON dbo.LOGAPP (OCCURRED_AT_UTC DESC, LOGAPP_ID DESC);
    CREATE INDEX IX_LOGAPP_RECORD
        ON dbo.LOGAPP (DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, OCCURRED_AT_UTC DESC);
    CREATE INDEX IX_LOGAPP_CORRELATION
        ON dbo.LOGAPP (CORRELATION_ID, OCCURRED_AT_UTC DESC)
        WHERE CORRELATION_ID IS NOT NULL;
END
GO

IF OBJECT_ID(N'dbo.LOGSYNC', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.LOGSYNC
    (
        LOGSYNC_ID bigint IDENTITY(1,1) NOT NULL
            CONSTRAINT PK_LOGSYNC PRIMARY KEY,
        LOGSYNCSTAMP varchar(25) NOT NULL
            CONSTRAINT UQ_LOGSYNC_STAMP UNIQUE,
        OCCURRED_AT_UTC datetime2(3) NOT NULL
            CONSTRAINT DF_LOGSYNC_OCCURRED DEFAULT SYSUTCDATETIME(),
        RUN_ID uniqueidentifier NOT NULL,
        CORRELATION_ID uniqueidentifier NULL,
        WORKER_CODE varchar(100) NOT NULL,
        WORKER_HOST varchar(255) NULL,
        MAPPINGSTAMP varchar(25) NULL,
        MAPPING_SNAPSHOT nvarchar(max) NULL,
        FEID int NULL,
        SOURCE_DATABASE sysname NOT NULL,
        SOURCE_SCHEMA sysname NOT NULL
            CONSTRAINT DF_LOGSYNC_SOURCE_SCHEMA DEFAULT 'dbo',
        SOURCE_TABLE sysname NOT NULL,
        TARGET_DATABASE sysname NOT NULL,
        TARGET_SCHEMA sysname NOT NULL
            CONSTRAINT DF_LOGSYNC_TARGET_SCHEMA DEFAULT 'dbo',
        TARGET_TABLE sysname NOT NULL,
        ACTION varchar(10) NOT NULL,
        SOURCE_KEY nvarchar(max) NOT NULL
            CONSTRAINT DF_LOGSYNC_SOURCE_KEY DEFAULT N'{}',
        TARGET_KEY nvarchar(max) NULL,
        SOURCE_DATA nvarchar(max) NULL,
        TARGET_BEFORE_DATA nvarchar(max) NULL,
        TARGET_AFTER_DATA nvarchar(max) NULL,
        CHANGED_DATA nvarchar(max) NULL,
        QUEUE_ID bigint NULL,
        STATUS varchar(20) NOT NULL
            CONSTRAINT DF_LOGSYNC_STATUS DEFAULT 'success',
        ERROR_MESSAGE nvarchar(2000) NULL,
        METADATA nvarchar(max) NULL,
        CONSTRAINT CK_LOGSYNC_ACTION CHECK (ACTION IN ('INSERT', 'UPDATE', 'DELETE', 'SELECT')),
        CONSTRAINT CK_LOGSYNC_STATUS CHECK (STATUS IN ('started', 'success', 'failed', 'skipped')),
        CONSTRAINT CK_LOGSYNC_SOURCE_KEY_JSON CHECK (ISJSON(SOURCE_KEY) = 1),
        CONSTRAINT CK_LOGSYNC_TARGET_KEY_JSON CHECK (TARGET_KEY IS NULL OR ISJSON(TARGET_KEY) = 1),
        CONSTRAINT CK_LOGSYNC_SOURCE_DATA_JSON CHECK (SOURCE_DATA IS NULL OR ISJSON(SOURCE_DATA) = 1),
        CONSTRAINT CK_LOGSYNC_TARGET_BEFORE_JSON CHECK (TARGET_BEFORE_DATA IS NULL OR ISJSON(TARGET_BEFORE_DATA) = 1),
        CONSTRAINT CK_LOGSYNC_TARGET_AFTER_JSON CHECK (TARGET_AFTER_DATA IS NULL OR ISJSON(TARGET_AFTER_DATA) = 1),
        CONSTRAINT CK_LOGSYNC_CHANGED_JSON CHECK (CHANGED_DATA IS NULL OR ISJSON(CHANGED_DATA) = 1),
        CONSTRAINT CK_LOGSYNC_MAPPING_JSON CHECK (MAPPING_SNAPSHOT IS NULL OR ISJSON(MAPPING_SNAPSHOT) = 1),
        CONSTRAINT CK_LOGSYNC_METADATA_JSON CHECK (METADATA IS NULL OR ISJSON(METADATA) = 1)
    );

    CREATE INDEX IX_LOGSYNC_RUN
        ON dbo.LOGSYNC (RUN_ID, LOGSYNC_ID);
    CREATE INDEX IX_LOGSYNC_MAPPING
        ON dbo.LOGSYNC (MAPPINGSTAMP, FEID, OCCURRED_AT_UTC DESC);
    CREATE INDEX IX_LOGSYNC_ROUTE
        ON dbo.LOGSYNC (SOURCE_DATABASE, SOURCE_TABLE, TARGET_DATABASE, TARGET_TABLE, OCCURRED_AT_UTC DESC);
    CREATE INDEX IX_LOGSYNC_QUEUE
        ON dbo.LOGSYNC (QUEUE_ID, OCCURRED_AT_UTC DESC)
        WHERE QUEUE_ID IS NOT NULL;
END
GO
