IF OBJECT_ID('dbo.GR_MAPA_GESTAO_ACESSOS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.GR_MAPA_GESTAO_ACESSOS
    (
        GRMAPACESSOSTAMP varchar(25) NOT NULL
            CONSTRAINT PK_GR_MAPA_GESTAO_ACESSOS PRIMARY KEY,
        USSTAMP varchar(25) NOT NULL,
        LOGIN varchar(60) NOT NULL,
        ORIGEM varchar(80) NOT NULL,
        ATIVO bit NOT NULL
            CONSTRAINT DF_GR_MAPA_GESTAO_ACESSOS_ATIVO DEFAULT (1),
        DTCRI datetime NOT NULL
            CONSTRAINT DF_GR_MAPA_GESTAO_ACESSOS_DTCRI DEFAULT (GETDATE()),
        USERCRIACAO varchar(60) NOT NULL
            CONSTRAINT DF_GR_MAPA_GESTAO_ACESSOS_USERCRIACAO DEFAULT ('')
    );
END;

IF OBJECT_ID('dbo.GR_MAPA_GESTAO_ACESSOS', 'U') IS NOT NULL
   AND NOT EXISTS (
        SELECT 1
        FROM sys.indexes
        WHERE object_id = OBJECT_ID('dbo.GR_MAPA_GESTAO_ACESSOS')
          AND name = 'UX_GR_MAPA_GESTAO_ACESSOS_USER_ORIGEM'
   )
BEGIN
    CREATE UNIQUE INDEX UX_GR_MAPA_GESTAO_ACESSOS_USER_ORIGEM
    ON dbo.GR_MAPA_GESTAO_ACESSOS (USSTAMP, ORIGEM);
END;
