SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID('dbo.OFICINA_TRAB', 'U') IS NULL
    BEGIN
        CREATE TABLE dbo.OFICINA_TRAB
        (
            OFICINA_TRABSTAMP varchar(25) NOT NULL
                CONSTRAINT DF_OFICINA_TRAB_STAMP DEFAULT LEFT(CONVERT(varchar(36), NEWID()), 25),
            FEID int NOT NULL,
            CODIGO varchar(20) NOT NULL,
            DESCRICAO nvarchar(255) NOT NULL,
            ATIVO bit NOT NULL
                CONSTRAINT DF_OFICINA_TRAB_ATIVO DEFAULT (1),
            ORDEM int NOT NULL
                CONSTRAINT DF_OFICINA_TRAB_ORDEM DEFAULT (0),
            DTCRI datetime2(0) NOT NULL
                CONSTRAINT DF_OFICINA_TRAB_DTCRI DEFAULT (SYSDATETIME()),
            DTALT datetime2(0) NULL,
            USERCRIACAO varchar(60) NOT NULL
                CONSTRAINT DF_OFICINA_TRAB_USERCRIACAO DEFAULT (''),
            USERALTERACAO varchar(60) NOT NULL
                CONSTRAINT DF_OFICINA_TRAB_USERALTERACAO DEFAULT (''),
            CONSTRAINT PK_OFICINA_TRAB PRIMARY KEY CLUSTERED (OFICINA_TRABSTAMP),
            CONSTRAINT UX_OFICINA_TRAB_FEID_CODIGO UNIQUE (FEID, CODIGO),
            CONSTRAINT CK_OFICINA_TRAB_CODIGO CHECK (LEN(LTRIM(RTRIM(CODIGO))) > 0),
            CONSTRAINT CK_OFICINA_TRAB_DESCRICAO CHECK (LEN(LTRIM(RTRIM(DESCRICAO))) > 0)
        );
    END;

    IF OBJECT_ID('dbo.OFICINA_MEC', 'U') IS NULL
    BEGIN
        CREATE TABLE dbo.OFICINA_MEC
        (
            OFICINA_MECSTAMP varchar(25) NOT NULL
                CONSTRAINT DF_OFICINA_MEC_STAMP DEFAULT LEFT(CONVERT(varchar(36), NEWID()), 25),
            NOME varchar(60) NOT NULL,
            COR varchar(18) NOT NULL
                CONSTRAINT DF_OFICINA_MEC_COR DEFAULT ('#60A5FA'),
            CONSTRAINT PK_OFICINA_MEC PRIMARY KEY CLUSTERED (OFICINA_MECSTAMP),
            CONSTRAINT CK_OFICINA_MEC_NOME CHECK (LEN(LTRIM(RTRIM(NOME))) > 0),
            CONSTRAINT CK_OFICINA_MEC_COR CHECK (LEN(LTRIM(RTRIM(COR))) > 0)
        );
    END;

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NULL
    BEGIN
        CREATE TABLE dbo.OFICINA_FOLHA
        (
            OFICINA_FOLHASTAMP varchar(25) NOT NULL
                CONSTRAINT DF_OFICINA_FOLHA_STAMP DEFAULT LEFT(CONVERT(varchar(36), NEWID()), 25),
            FEID int NOT NULL,
            NO int NOT NULL,
            VASTAMP varchar(25) NOT NULL,
            MATRICULA varchar(12) NOT NULL,
            OFICINA_TRABSTAMP varchar(25) NULL,
            TRABALHO nvarchar(1000) NOT NULL
                CONSTRAINT DF_OFICINA_FOLHA_TRABALHO DEFAULT (''),
            DATA date NOT NULL
                CONSTRAINT DF_OFICINA_FOLHA_DATA DEFAULT (CONVERT(date, GETDATE())),
            HORAINI varchar(5) NOT NULL
                CONSTRAINT DF_OFICINA_FOLHA_HORAINI DEFAULT (''),
            HORAFIM varchar(5) NOT NULL
                CONSTRAINT DF_OFICINA_FOLHA_HORAFIM DEFAULT (''),
            TEMPO int NOT NULL
                CONSTRAINT DF_OFICINA_FOLHA_TEMPO DEFAULT (0),
            OFICINA_MECSTAMP varchar(25) NULL,
            PLAN_DATA date NULL,
            PLAN_HORAINI varchar(5) NOT NULL
                CONSTRAINT DF_OFICINA_FOLHA_PLAN_HORAINI DEFAULT (''),
            PLAN_HORAFIM varchar(5) NOT NULL
                CONSTRAINT DF_OFICINA_FOLHA_PLAN_HORAFIM DEFAULT (''),
            ESTADO varchar(20) NOT NULL
                CONSTRAINT DF_OFICINA_FOLHA_ESTADO DEFAULT ('ABERTA'),
            OBS nvarchar(4000) NOT NULL
                CONSTRAINT DF_OFICINA_FOLHA_OBS DEFAULT (''),
            TOTAL decimal(19,4) NOT NULL
                CONSTRAINT DF_OFICINA_FOLHA_TOTAL DEFAULT (0),
            DTCRI datetime2(0) NOT NULL
                CONSTRAINT DF_OFICINA_FOLHA_DTCRI DEFAULT (SYSDATETIME()),
            DTALT datetime2(0) NULL,
            USERCRIACAO varchar(60) NOT NULL
                CONSTRAINT DF_OFICINA_FOLHA_USERCRIACAO DEFAULT (''),
            USERALTERACAO varchar(60) NOT NULL
                CONSTRAINT DF_OFICINA_FOLHA_USERALTERACAO DEFAULT (''),
            CONSTRAINT PK_OFICINA_FOLHA PRIMARY KEY CLUSTERED (OFICINA_FOLHASTAMP),
            CONSTRAINT UX_OFICINA_FOLHA_FEID_NO UNIQUE (FEID, NO),
            CONSTRAINT FK_OFICINA_FOLHA_VA FOREIGN KEY (VASTAMP) REFERENCES dbo.VA (VASTAMP),
            CONSTRAINT FK_OFICINA_FOLHA_TRAB FOREIGN KEY (OFICINA_TRABSTAMP)
                REFERENCES dbo.OFICINA_TRAB (OFICINA_TRABSTAMP),
            CONSTRAINT FK_OFICINA_FOLHA_MEC FOREIGN KEY (OFICINA_MECSTAMP)
                REFERENCES dbo.OFICINA_MEC (OFICINA_MECSTAMP),
            CONSTRAINT CK_OFICINA_FOLHA_ESTADO
                CHECK (ESTADO IN ('ABERTA', 'EXECUCAO', 'CONCLUIDA', 'ANULADA')),
            CONSTRAINT CK_OFICINA_FOLHA_HORAINI
                CHECK (HORAINI = ''
                   OR (HORAINI LIKE '[0-2][0-9]:[0-5][0-9]'
                   AND TRY_CONVERT(int, LEFT(HORAINI, 2)) BETWEEN 0 AND 23)),
            CONSTRAINT CK_OFICINA_FOLHA_HORAFIM
                CHECK (HORAFIM = ''
                   OR (HORAFIM LIKE '[0-2][0-9]:[0-5][0-9]'
                   AND TRY_CONVERT(int, LEFT(HORAFIM, 2)) BETWEEN 0 AND 23)),
            CONSTRAINT CK_OFICINA_FOLHA_TEMPO CHECK (TEMPO >= 0),
            CONSTRAINT CK_OFICINA_FOLHA_PLAN_HORAINI
                CHECK (PLAN_HORAINI = ''
                   OR (PLAN_HORAINI LIKE '[0-2][0-9]:[0-5][0-9]'
                   AND TRY_CONVERT(int, LEFT(PLAN_HORAINI, 2)) BETWEEN 0 AND 23)),
            CONSTRAINT CK_OFICINA_FOLHA_PLAN_HORAFIM
                CHECK (PLAN_HORAFIM = ''
                   OR (PLAN_HORAFIM LIKE '[0-2][0-9]:[0-5][0-9]'
                   AND TRY_CONVERT(int, LEFT(PLAN_HORAFIM, 2)) BETWEEN 0 AND 23))
        );
    END;

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND COL_LENGTH('dbo.OFICINA_FOLHA', 'DATA') IS NULL
    BEGIN
        ALTER TABLE dbo.OFICINA_FOLHA ADD DATA date NULL;
        EXEC('UPDATE dbo.OFICINA_FOLHA SET DATA = CONVERT(date, ISNULL(DTINICIO, GETDATE())) WHERE DATA IS NULL');
        ALTER TABLE dbo.OFICINA_FOLHA ALTER COLUMN DATA date NOT NULL;
    END;

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND COL_LENGTH('dbo.OFICINA_FOLHA', 'HORAINI') IS NULL
    BEGIN
        ALTER TABLE dbo.OFICINA_FOLHA ADD HORAINI varchar(5) NULL;
        EXEC('UPDATE dbo.OFICINA_FOLHA SET HORAINI = LEFT(CONVERT(varchar(8), ISNULL(DTINICIO, GETDATE()), 108), 5) WHERE HORAINI IS NULL OR HORAINI = ''''');
        ALTER TABLE dbo.OFICINA_FOLHA ALTER COLUMN HORAINI varchar(5) NOT NULL;
    END;

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND COL_LENGTH('dbo.OFICINA_FOLHA', 'HORAFIM') IS NULL
    BEGIN
        ALTER TABLE dbo.OFICINA_FOLHA ADD HORAFIM varchar(5) NULL;
        EXEC('UPDATE dbo.OFICINA_FOLHA SET HORAFIM = CASE WHEN DTFIM IS NULL THEN '''' ELSE LEFT(CONVERT(varchar(8), DTFIM, 108), 5) END WHERE HORAFIM IS NULL');
        ALTER TABLE dbo.OFICINA_FOLHA ALTER COLUMN HORAFIM varchar(5) NOT NULL;
    END;

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND COL_LENGTH('dbo.OFICINA_FOLHA', 'TEMPO') IS NULL
    BEGIN
        ALTER TABLE dbo.OFICINA_FOLHA ADD TEMPO int NULL;
        EXEC('UPDATE dbo.OFICINA_FOLHA SET TEMPO = 0 WHERE TEMPO IS NULL');
        ALTER TABLE dbo.OFICINA_FOLHA ALTER COLUMN TEMPO int NOT NULL;
    END;

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND COL_LENGTH('dbo.OFICINA_FOLHA', 'OBS') < 8000
        ALTER TABLE dbo.OFICINA_FOLHA ALTER COLUMN OBS nvarchar(4000) NOT NULL;

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND COL_LENGTH('dbo.OFICINA_FOLHA', 'OFICINA_MECSTAMP') IS NULL
        ALTER TABLE dbo.OFICINA_FOLHA ADD OFICINA_MECSTAMP varchar(25) NULL;

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND COL_LENGTH('dbo.OFICINA_FOLHA', 'PLAN_DATA') IS NULL
        ALTER TABLE dbo.OFICINA_FOLHA ADD PLAN_DATA date NULL;

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND COL_LENGTH('dbo.OFICINA_FOLHA', 'PLAN_HORAINI') IS NULL
    BEGIN
        ALTER TABLE dbo.OFICINA_FOLHA ADD PLAN_HORAINI varchar(5) NULL;
        EXEC('UPDATE dbo.OFICINA_FOLHA SET PLAN_HORAINI = '''' WHERE PLAN_HORAINI IS NULL');
        ALTER TABLE dbo.OFICINA_FOLHA ALTER COLUMN PLAN_HORAINI varchar(5) NOT NULL;
    END;

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND COL_LENGTH('dbo.OFICINA_FOLHA', 'PLAN_HORAFIM') IS NULL
    BEGIN
        ALTER TABLE dbo.OFICINA_FOLHA ADD PLAN_HORAFIM varchar(5) NULL;
        EXEC('UPDATE dbo.OFICINA_FOLHA SET PLAN_HORAFIM = '''' WHERE PLAN_HORAFIM IS NULL');
        ALTER TABLE dbo.OFICINA_FOLHA ALTER COLUMN PLAN_HORAFIM varchar(5) NOT NULL;
    END;

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND COL_LENGTH('dbo.OFICINA_FOLHA', 'DTINICIO') IS NOT NULL
        EXEC('ALTER TABLE dbo.OFICINA_FOLHA ALTER COLUMN DTINICIO datetime2(0) NULL');

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID('dbo.OFICINA_FOLHA') AND name = 'DF_OFICINA_FOLHA_DATA')
        EXEC('ALTER TABLE dbo.OFICINA_FOLHA ADD CONSTRAINT DF_OFICINA_FOLHA_DATA DEFAULT (CONVERT(date, GETDATE())) FOR DATA');

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID('dbo.OFICINA_FOLHA') AND name = 'DF_OFICINA_FOLHA_HORAINI')
        EXEC('ALTER TABLE dbo.OFICINA_FOLHA ADD CONSTRAINT DF_OFICINA_FOLHA_HORAINI DEFAULT ('''') FOR HORAINI');

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID('dbo.OFICINA_FOLHA') AND name = 'DF_OFICINA_FOLHA_HORAFIM')
        EXEC('ALTER TABLE dbo.OFICINA_FOLHA ADD CONSTRAINT DF_OFICINA_FOLHA_HORAFIM DEFAULT ('''') FOR HORAFIM');

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID('dbo.OFICINA_FOLHA') AND name = 'DF_OFICINA_FOLHA_TEMPO')
        EXEC('ALTER TABLE dbo.OFICINA_FOLHA ADD CONSTRAINT DF_OFICINA_FOLHA_TEMPO DEFAULT (0) FOR TEMPO');

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID('dbo.OFICINA_FOLHA') AND name = 'DF_OFICINA_FOLHA_PLAN_HORAINI')
        EXEC('ALTER TABLE dbo.OFICINA_FOLHA ADD CONSTRAINT DF_OFICINA_FOLHA_PLAN_HORAINI DEFAULT ('''') FOR PLAN_HORAINI');

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID('dbo.OFICINA_FOLHA') AND name = 'DF_OFICINA_FOLHA_PLAN_HORAFIM')
        EXEC('ALTER TABLE dbo.OFICINA_FOLHA ADD CONSTRAINT DF_OFICINA_FOLHA_PLAN_HORAFIM DEFAULT ('''') FOR PLAN_HORAFIM');

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND EXISTS (SELECT 1 FROM sys.check_constraints WHERE parent_object_id = OBJECT_ID('dbo.OFICINA_FOLHA') AND name = 'CK_OFICINA_FOLHA_HORAINI')
        EXEC('ALTER TABLE dbo.OFICINA_FOLHA DROP CONSTRAINT CK_OFICINA_FOLHA_HORAINI');

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE parent_object_id = OBJECT_ID('dbo.OFICINA_FOLHA') AND name = 'CK_OFICINA_FOLHA_HORAINI')
        EXEC('ALTER TABLE dbo.OFICINA_FOLHA ADD CONSTRAINT CK_OFICINA_FOLHA_HORAINI
            CHECK (HORAINI = ''''
               OR (HORAINI LIKE ''[0-2][0-9]:[0-5][0-9]''
               AND TRY_CONVERT(int, LEFT(HORAINI, 2)) BETWEEN 0 AND 23))');

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE parent_object_id = OBJECT_ID('dbo.OFICINA_FOLHA') AND name = 'CK_OFICINA_FOLHA_HORAFIM')
        EXEC('ALTER TABLE dbo.OFICINA_FOLHA ADD CONSTRAINT CK_OFICINA_FOLHA_HORAFIM
            CHECK (HORAFIM = ''''
               OR (HORAFIM LIKE ''[0-2][0-9]:[0-5][0-9]''
               AND TRY_CONVERT(int, LEFT(HORAFIM, 2)) BETWEEN 0 AND 23))');

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE parent_object_id = OBJECT_ID('dbo.OFICINA_FOLHA') AND name = 'CK_OFICINA_FOLHA_TEMPO')
        EXEC('ALTER TABLE dbo.OFICINA_FOLHA ADD CONSTRAINT CK_OFICINA_FOLHA_TEMPO CHECK (TEMPO >= 0)');

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE parent_object_id = OBJECT_ID('dbo.OFICINA_FOLHA') AND name = 'CK_OFICINA_FOLHA_PLAN_HORAINI')
        EXEC('ALTER TABLE dbo.OFICINA_FOLHA ADD CONSTRAINT CK_OFICINA_FOLHA_PLAN_HORAINI
            CHECK (PLAN_HORAINI = ''''
               OR (PLAN_HORAINI LIKE ''[0-2][0-9]:[0-5][0-9]''
               AND TRY_CONVERT(int, LEFT(PLAN_HORAINI, 2)) BETWEEN 0 AND 23))');

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE parent_object_id = OBJECT_ID('dbo.OFICINA_FOLHA') AND name = 'CK_OFICINA_FOLHA_PLAN_HORAFIM')
        EXEC('ALTER TABLE dbo.OFICINA_FOLHA ADD CONSTRAINT CK_OFICINA_FOLHA_PLAN_HORAFIM
            CHECK (PLAN_HORAFIM = ''''
               OR (PLAN_HORAFIM LIKE ''[0-2][0-9]:[0-5][0-9]''
               AND TRY_CONVERT(int, LEFT(PLAN_HORAFIM, 2)) BETWEEN 0 AND 23))');

    IF OBJECT_ID('dbo.OFICINA_FOLHA', 'U') IS NOT NULL
       AND OBJECT_ID('dbo.OFICINA_MEC', 'U') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_OFICINA_FOLHA_MEC')
        EXEC('ALTER TABLE dbo.OFICINA_FOLHA ADD CONSTRAINT FK_OFICINA_FOLHA_MEC
            FOREIGN KEY (OFICINA_MECSTAMP) REFERENCES dbo.OFICINA_MEC (OFICINA_MECSTAMP)');

    IF OBJECT_ID('dbo.OFICINA_LINHA', 'U') IS NULL
    BEGIN
        CREATE TABLE dbo.OFICINA_LINHA
        (
            OFICINA_LINHASTAMP varchar(25) NOT NULL
                CONSTRAINT DF_OFICINA_LINHA_STAMP DEFAULT LEFT(CONVERT(varchar(36), NEWID()), 25),
            OFICINA_FOLHASTAMP varchar(25) NOT NULL,
            ORDEM int NOT NULL
                CONSTRAINT DF_OFICINA_LINHA_ORDEM DEFAULT (0),
            STSTAMP char(25) NULL,
            REF varchar(18) NOT NULL,
            DESIGN nvarchar(120) NOT NULL,
            UNIDADE varchar(10) NOT NULL
                CONSTRAINT DF_OFICINA_LINHA_UNIDADE DEFAULT (''),
            QTT decimal(18,3) NOT NULL,
            PUNIT decimal(19,6) NOT NULL,
            TOTAL decimal(19,4) NOT NULL,
            OBS nvarchar(500) NOT NULL
                CONSTRAINT DF_OFICINA_LINHA_OBS DEFAULT (''),
            CONSTRAINT PK_OFICINA_LINHA PRIMARY KEY CLUSTERED (OFICINA_LINHASTAMP),
            CONSTRAINT FK_OFICINA_LINHA_FOLHA FOREIGN KEY (OFICINA_FOLHASTAMP)
                REFERENCES dbo.OFICINA_FOLHA (OFICINA_FOLHASTAMP) ON DELETE CASCADE,
            CONSTRAINT CK_OFICINA_LINHA_REF CHECK (LEN(LTRIM(RTRIM(REF))) > 0),
            CONSTRAINT CK_OFICINA_LINHA_DESIGN CHECK (LEN(LTRIM(RTRIM(DESIGN))) > 0),
            CONSTRAINT CK_OFICINA_LINHA_QTT CHECK (QTT > 0),
            CONSTRAINT CK_OFICINA_LINHA_VALORES CHECK (PUNIT >= 0 AND TOTAL >= 0)
        );
    END;

    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.OFICINA_TRAB') AND name = 'IX_OFICINA_TRAB_FEID_ATIVO_ORDEM')
        CREATE INDEX IX_OFICINA_TRAB_FEID_ATIVO_ORDEM
            ON dbo.OFICINA_TRAB (FEID, ATIVO, ORDEM, DESCRICAO);

    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.OFICINA_FOLHA') AND name = 'IX_OFICINA_FOLHA_FEID_ESTADO_DATA')
        EXEC('CREATE INDEX IX_OFICINA_FOLHA_FEID_ESTADO_DATA
            ON dbo.OFICINA_FOLHA (FEID, ESTADO, DATA DESC, HORAINI DESC)');

    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.OFICINA_FOLHA') AND name = 'IX_OFICINA_FOLHA_VASTAMP_DATA')
        EXEC('CREATE INDEX IX_OFICINA_FOLHA_VASTAMP_DATA
            ON dbo.OFICINA_FOLHA (VASTAMP, DATA DESC, HORAINI DESC)');

    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.OFICINA_FOLHA') AND name = 'IX_OFICINA_FOLHA_MATRICULA')
        CREATE INDEX IX_OFICINA_FOLHA_MATRICULA
            ON dbo.OFICINA_FOLHA (MATRICULA);

    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.OFICINA_FOLHA') AND name = 'IX_OFICINA_FOLHA_MEC_PLAN')
        CREATE INDEX IX_OFICINA_FOLHA_MEC_PLAN
            ON dbo.OFICINA_FOLHA (OFICINA_MECSTAMP, PLAN_DATA, PLAN_HORAINI);

    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.OFICINA_MEC') AND name = 'IX_OFICINA_MEC_NOME')
        CREATE INDEX IX_OFICINA_MEC_NOME
            ON dbo.OFICINA_MEC (NOME);

    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.OFICINA_LINHA') AND name = 'IX_OFICINA_LINHA_FOLHA_ORDEM')
        CREATE INDEX IX_OFICINA_LINHA_FOLHA_ORDEM
            ON dbo.OFICINA_LINHA (OFICINA_FOLHASTAMP, ORDEM);

    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.OFICINA_LINHA') AND name = 'IX_OFICINA_LINHA_REF')
        CREATE INDEX IX_OFICINA_LINHA_REF
            ON dbo.OFICINA_LINHA (REF);

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
