/* GuestSpaTur tickets: compatible with the GR360 dbo.TK contract. */
IF OBJECT_ID('dbo.TK', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TK (
        TKSTAMP             varchar(25) NOT NULL,
        TICKET              int IDENTITY(1,1) NOT NULL,
        DATA                date NOT NULL CONSTRAINT DF_GS_TK_DATA DEFAULT (CONVERT(date, SYSUTCDATETIME())),
        UTILIZADOR          varchar(100) NOT NULL CONSTRAINT DF_GS_TK_UTILIZADOR DEFAULT (''),
        PEDIDO              varchar(250) NOT NULL CONSTRAINT DF_GS_TK_PEDIDO DEFAULT (''),
        DESCRICAO           varchar(500) NOT NULL CONSTRAINT DF_GS_TK_DESCRICAO DEFAULT (''),
        TRATADO             bit NOT NULL CONSTRAINT DF_GS_TK_TRATADO DEFAULT (0),
        DTTRATADO           date NULL,
        NMTRATADO           varchar(100) NULL,
        PRIORIDADE          varchar(30) NOT NULL CONSTRAINT DF_GS_TK_PRIORIDADE DEFAULT ('Normal'),
        FEID                int NULL,
        PROMPT_HUGO         nvarchar(max) NOT NULL CONSTRAINT DF_GS_TK_PROMPT DEFAULT (N''),
        SEGUIMENTO_CLIENTE  nvarchar(max) NULL,
        SEGUIMENTO_ESTADO   varchar(50) NULL,
        SEGUIMENTO_DATA     datetime2(3) NULL,
        SEGUIMENTO_POR      varchar(100) NULL,
        ORIGEM_API          varchar(50) NULL,
        REFERENCIA_EXTERNA  varchar(100) NULL,
        TK_VERSION          rowversion NOT NULL,
        DTCRIACAO_UTC       datetime2(3) NOT NULL CONSTRAINT DF_GS_TK_CRIACAO DEFAULT (SYSUTCDATETIME()),
        DTALTERACAO_UTC     datetime2(3) NOT NULL CONSTRAINT DF_GS_TK_ALTERACAO DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_GS_TK PRIMARY KEY (TKSTAMP),
        CONSTRAINT UQ_GS_TK_TICKET UNIQUE (TICKET)
    );
END;
GO

/* Add the GR360-compatible fields to an existing GuestSpaTur table. */
IF COL_LENGTH('dbo.TK', 'FEID') IS NULL ALTER TABLE dbo.TK ADD FEID int NULL;
IF COL_LENGTH('dbo.TK', 'PROMPT_HUGO') IS NULL ALTER TABLE dbo.TK ADD PROMPT_HUGO nvarchar(max) NULL;
IF COL_LENGTH('dbo.TK', 'SEGUIMENTO_CLIENTE') IS NULL ALTER TABLE dbo.TK ADD SEGUIMENTO_CLIENTE nvarchar(max) NULL;
IF COL_LENGTH('dbo.TK', 'SEGUIMENTO_ESTADO') IS NULL ALTER TABLE dbo.TK ADD SEGUIMENTO_ESTADO varchar(50) NULL;
IF COL_LENGTH('dbo.TK', 'SEGUIMENTO_DATA') IS NULL ALTER TABLE dbo.TK ADD SEGUIMENTO_DATA datetime2(3) NULL;
IF COL_LENGTH('dbo.TK', 'SEGUIMENTO_POR') IS NULL ALTER TABLE dbo.TK ADD SEGUIMENTO_POR varchar(100) NULL;
IF COL_LENGTH('dbo.TK', 'ORIGEM_API') IS NULL ALTER TABLE dbo.TK ADD ORIGEM_API varchar(50) NULL;
IF COL_LENGTH('dbo.TK', 'REFERENCIA_EXTERNA') IS NULL ALTER TABLE dbo.TK ADD REFERENCIA_EXTERNA varchar(100) NULL;
IF COL_LENGTH('dbo.TK', 'TK_VERSION') IS NULL ALTER TABLE dbo.TK ADD TK_VERSION rowversion;
IF COL_LENGTH('dbo.TK', 'DTCRIACAO_UTC') IS NULL ALTER TABLE dbo.TK ADD DTCRIACAO_UTC datetime2(3) NULL;
IF COL_LENGTH('dbo.TK', 'DTALTERACAO_UTC') IS NULL ALTER TABLE dbo.TK ADD DTALTERACAO_UTC datetime2(3) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE parent_object_id = OBJECT_ID('dbo.TK') AND type = 'PK')
    ALTER TABLE dbo.TK ADD CONSTRAINT PK_GS_TK PRIMARY KEY (TKSTAMP);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UQ_GS_TK_TICKET' AND object_id = OBJECT_ID('dbo.TK'))
    ALTER TABLE dbo.TK ADD CONSTRAINT UQ_GS_TK_TICKET UNIQUE (TICKET);
GO

IF OBJECT_ID('dbo.TK_ANEXO', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TK_ANEXO (
        TK_ANEXO_STAMP      varchar(25) NOT NULL,
        TKSTAMP             varchar(25) NOT NULL,
        NOME                nvarchar(260) NOT NULL,
        CAMINHO             nvarchar(1000) NULL,
        MIME_TYPE           varchar(150) NULL,
        TAMANHO             bigint NULL,
        HASH_SHA256         varchar(64) NULL,
        DTCRIACAO_UTC       datetime2(3) NOT NULL CONSTRAINT DF_GS_TK_ANEXO_CRIACAO DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_GS_TK_ANEXO PRIMARY KEY (TK_ANEXO_STAMP),
        CONSTRAINT FK_GS_TK_ANEXO_TK FOREIGN KEY (TKSTAMP) REFERENCES dbo.TK(TKSTAMP)
    );
END;
GO

IF OBJECT_ID('dbo.TK_AUDIT', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TK_AUDIT (
        TK_AUDIT_STAMP     varchar(25) NOT NULL,
        TKSTAMP            varchar(25) NULL,
        ACAO               varchar(30) NOT NULL,
        UTILIZADOR         varchar(100) NULL,
        ANTES_JSON         nvarchar(max) NULL,
        DEPOIS_JSON        nvarchar(max) NULL,
        DTCRIACAO_UTC      datetime2(3) NOT NULL CONSTRAINT DF_GS_TK_AUDIT_CRIACAO DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_GS_TK_AUDIT PRIMARY KEY (TK_AUDIT_STAMP)
    );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_GS_TK_PENDING' AND object_id = OBJECT_ID('dbo.TK'))
    CREATE INDEX IX_GS_TK_PENDING ON dbo.TK (TRATADO, PRIORIDADE, DATA, TICKET);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_GS_TK_API_REF' AND object_id = OBJECT_ID('dbo.TK'))
    CREATE UNIQUE INDEX UX_GS_TK_API_REF ON dbo.TK (ORIGEM_API, REFERENCIA_EXTERNA)
    WHERE ORIGEM_API IS NOT NULL AND REFERENCIA_EXTERNA IS NOT NULL;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_GS_TK_ANEXO_TK' AND object_id = OBJECT_ID('dbo.TK_ANEXO'))
    CREATE INDEX IX_GS_TK_ANEXO_TK ON dbo.TK_ANEXO (TKSTAMP);
GO
