IF OBJECT_ID('dbo.MENU_EVENTOS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MENU_EVENTOS
    (
        MENUEVENTOSTAMP  varchar(25)   NOT NULL
            CONSTRAINT DF_MENU_EVENTOS_STAMP DEFAULT LEFT(CONVERT(varchar(36), NEWID()), 25),
        MENUSTAMP        varchar(25)   NOT NULL,
        EVENTO           varchar(40)   NOT NULL,
        FLUXO            nvarchar(max) NOT NULL
            CONSTRAINT DF_MENU_EVENTOS_FLUXO DEFAULT N'{}',
        ATIVO            bit           NOT NULL
            CONSTRAINT DF_MENU_EVENTOS_ATIVO DEFAULT 1,
        DTCRI            datetime2(0)  NOT NULL
            CONSTRAINT DF_MENU_EVENTOS_DTCRI DEFAULT GETDATE(),
        DTALT            datetime2(0)  NULL,
        USERCRIACAO      varchar(50)   NOT NULL
            CONSTRAINT DF_MENU_EVENTOS_USERCRIACAO DEFAULT '',
        USERALTERACAO    varchar(50)   NOT NULL
            CONSTRAINT DF_MENU_EVENTOS_USERALTERACAO DEFAULT '',
        CONSTRAINT PK_MENU_EVENTOS PRIMARY KEY CLUSTERED (MENUEVENTOSTAMP),
        CONSTRAINT FK_MENU_EVENTOS_MENU FOREIGN KEY (MENUSTAMP) REFERENCES dbo.MENU(MENUSTAMP),
        CONSTRAINT UQ_MENU_EVENTOS_MENU_EVENTO UNIQUE (MENUSTAMP, EVENTO)
    );

    CREATE INDEX IX_MENU_EVENTOS_MENU_EVENTO
        ON dbo.MENU_EVENTOS (MENUSTAMP, EVENTO);
END
