IF COL_LENGTH('dbo.MENU', 'LARGURAS_EXATAS_LISTA') IS NULL
BEGIN
    ALTER TABLE dbo.MENU
    ADD LARGURAS_EXATAS_LISTA BIT NOT NULL
        CONSTRAINT DF_MENU_LARGURAS_EXATAS_LISTA DEFAULT 0;
END
GO
