SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET XACT_ABORT ON
GO

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID('dbo.MENU_VARIAVEIS', 'U') IS NULL
    BEGIN
        CREATE TABLE dbo.MENU_VARIAVEIS
        (
            MENUVARSTAMP      varchar(25)   NOT NULL
                CONSTRAINT DF_MENU_VARIAVEIS_STAMP DEFAULT LEFT(CONVERT(varchar(36), NEWID()), 25),
            MENUSTAMP         varchar(25)   NOT NULL,
            NOME              varchar(60)   NOT NULL,
            DESCRICAO         varchar(100)  NOT NULL
                CONSTRAINT DF_MENU_VARIAVEIS_DESCRICAO DEFAULT '',
            TIPO              varchar(20)   NOT NULL
                CONSTRAINT DF_MENU_VARIAVEIS_TIPO DEFAULT 'TEXT',
            VALOR_DEFAULT     nvarchar(max) NOT NULL
                CONSTRAINT DF_MENU_VARIAVEIS_VALOR_DEFAULT DEFAULT N'',
            ORDEM             int           NOT NULL
                CONSTRAINT DF_MENU_VARIAVEIS_ORDEM DEFAULT 0,
            PROPRIEDADES      nvarchar(max) NOT NULL
                CONSTRAINT DF_MENU_VARIAVEIS_PROPRIEDADES DEFAULT N'{}',
            ATIVO             bit           NOT NULL
                CONSTRAINT DF_MENU_VARIAVEIS_ATIVO DEFAULT 1,
            DTCRI             datetime2(0)  NOT NULL
                CONSTRAINT DF_MENU_VARIAVEIS_DTCRI DEFAULT GETDATE(),
            DTALT             datetime2(0)  NULL,
            USERCRIACAO       varchar(50)   NOT NULL
                CONSTRAINT DF_MENU_VARIAVEIS_USERCRIACAO DEFAULT '',
            USERALTERACAO     varchar(50)   NOT NULL
                CONSTRAINT DF_MENU_VARIAVEIS_USERALTERACAO DEFAULT '',

            CONSTRAINT PK_MENU_VARIAVEIS PRIMARY KEY CLUSTERED (MENUVARSTAMP),
            CONSTRAINT FK_MENU_VARIAVEIS_MENU FOREIGN KEY (MENUSTAMP) REFERENCES dbo.MENU(MENUSTAMP),
            CONSTRAINT UQ_MENU_VARIAVEIS_MENU_NOME UNIQUE (MENUSTAMP, NOME)
        );

        CREATE INDEX IX_MENU_VARIAVEIS_MENU_ORDEM
            ON dbo.MENU_VARIAVEIS (MENUSTAMP, ORDEM, NOME);
    END

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    THROW;
END CATCH
GO
