SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET XACT_ABORT ON
GO

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID('dbo.MOD_OBJETOS', 'U') IS NULL
    BEGIN
        CREATE TABLE dbo.MOD_OBJETOS
        (
            MODOBJSTAMP      varchar(25)  NOT NULL
                CONSTRAINT DF_MOD_OBJETOS_MODOBJSTAMP DEFAULT LEFT(CONVERT(varchar(36), NEWID()), 25),
            MODSTAMP         varchar(25)  NOT NULL,
            TIPO             varchar(20)  NOT NULL,
            OBJKEY           varchar(150) NOT NULL,
            OBJNOME          varchar(150) NOT NULL,
            OBJROTA          varchar(255) NOT NULL
                CONSTRAINT DF_MOD_OBJETOS_OBJROTA DEFAULT '',
            MENUSTAMP        varchar(25)  NOT NULL
                CONSTRAINT DF_MOD_OBJETOS_MENUSTAMP DEFAULT '',
            ORDEM            int          NOT NULL
                CONSTRAINT DF_MOD_OBJETOS_ORDEM DEFAULT 0,
            ATIVO            bit          NOT NULL
                CONSTRAINT DF_MOD_OBJETOS_ATIVO DEFAULT 1,
            DTCRI            datetime2(0) NOT NULL
                CONSTRAINT DF_MOD_OBJETOS_DTCRI DEFAULT GETDATE(),
            DTALT            datetime2(0) NULL,
            USERCRIACAO      varchar(50)  NOT NULL
                CONSTRAINT DF_MOD_OBJETOS_USERCRIACAO DEFAULT '',
            USERALTERACAO    varchar(50)  NOT NULL
                CONSTRAINT DF_MOD_OBJETOS_USERALTERACAO DEFAULT '',

            CONSTRAINT PK_MOD_OBJETOS PRIMARY KEY CLUSTERED (MODOBJSTAMP),
            CONSTRAINT FK_MOD_OBJETOS_MODULOS FOREIGN KEY (MODSTAMP) REFERENCES dbo.MODULOS(MODSTAMP),
            CONSTRAINT UQ_MOD_OBJETOS UNIQUE (MODSTAMP, OBJKEY)
        );

        CREATE INDEX IX_MOD_OBJETOS_MODSTAMP ON dbo.MOD_OBJETOS (MODSTAMP);
        CREATE INDEX IX_MOD_OBJETOS_MENUSTAMP ON dbo.MOD_OBJETOS (MENUSTAMP);
    END

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    THROW;
END CATCH
GO
