IF OBJECT_ID('dbo.PR_PROMO', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PR_PROMO (
        PROMO_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        PERFIL_ID INT NOT NULL,
        DATA_INI DATE NOT NULL,
        DATA_FIM DATE NOT NULL,
        DESCONTO_PCT DECIMAL(9,2) NOT NULL,
        NOTA NVARCHAR(200) NULL,
        ATIVO BIT NOT NULL CONSTRAINT DF_PR_PROMO_ATIVO DEFAULT (1),
        CRIADO_EM DATETIME2(0) NOT NULL CONSTRAINT DF_PR_PROMO_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        CRIADO_POR NVARCHAR(60) NULL,
        CONSTRAINT FK_PR_PROMO_PERFIL FOREIGN KEY (PERFIL_ID) REFERENCES dbo.PR_PERFIL (PERFIL_ID),
        CONSTRAINT CK_PR_PROMO_INTERVALO CHECK (DATA_FIM >= DATA_INI),
        CONSTRAINT CK_PR_PROMO_PCT CHECK (DESCONTO_PCT >= 0 AND DESCONTO_PCT <= 100)
    );
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_PR_PROMO_PERFIL_DATA'
      AND object_id = OBJECT_ID('dbo.PR_PROMO')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_PR_PROMO_PERFIL_DATA
        ON dbo.PR_PROMO (PERFIL_ID, DATA_INI, DATA_FIM);
END
GO
