SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID('dbo.PROJ', 'U') IS NULL
    BEGIN
        CREATE TABLE dbo.PROJ
        (
            PROJSTAMP   VARCHAR(25)  NOT NULL,
            CODIGO      VARCHAR(30)  NOT NULL,
            NOME        VARCHAR(120) NOT NULL,
            DESCRICAO   VARCHAR(MAX) NULL,
            RESPONSAVEL VARCHAR(60)  NOT NULL,
            ESTADO      NUMERIC(2,0) NOT NULL CONSTRAINT DF_PROJ_ESTADO DEFAULT (1),
            DATAINICIO  DATE NULL,
            DATAPREVISTA DATE NULL,
            DATAFIM     DATE NULL,
            PRIORIDADE  NUMERIC(2,0) NOT NULL CONSTRAINT DF_PROJ_PRIORIDADE DEFAULT (2),
            CRIADOEM    DATETIME2(0) NOT NULL CONSTRAINT DF_PROJ_CRIADOEM DEFAULT (SYSDATETIME()),
            CRIADOPOR   VARCHAR(60)  NOT NULL CONSTRAINT DF_PROJ_CRIADOPOR DEFAULT (''),
            ALTERADOEM  DATETIME2(0) NOT NULL CONSTRAINT DF_PROJ_ALTERADOEM DEFAULT (SYSDATETIME()),
            ALTERADOPOR VARCHAR(60)  NOT NULL CONSTRAINT DF_PROJ_ALTERADOPOR DEFAULT (''),
            CONSTRAINT PK_PROJ PRIMARY KEY CLUSTERED (PROJSTAMP)
        );

        CREATE UNIQUE INDEX UX_PROJ_CODIGO
            ON dbo.PROJ (CODIGO);

        CREATE INDEX IX_PROJ_ESTADO_RESP
            ON dbo.PROJ (ESTADO, RESPONSAVEL, DATAPREVISTA);
    END;

    IF OBJECT_ID('dbo.PROJEST', 'U') IS NULL
    BEGIN
        CREATE TABLE dbo.PROJEST
        (
            CODIGO NUMERIC(2,0) NOT NULL,
            NOME   VARCHAR(40) NOT NULL,
            ORDEM  INT NOT NULL CONSTRAINT DF_PROJEST_ORDEM DEFAULT (0),
            COR    VARCHAR(20) NOT NULL CONSTRAINT DF_PROJEST_COR DEFAULT ('secondary'),
            FINAL  BIT NOT NULL CONSTRAINT DF_PROJEST_FINAL DEFAULT (0),
            ATIVO  BIT NOT NULL CONSTRAINT DF_PROJEST_ATIVO DEFAULT (1),
            CONSTRAINT PK_PROJEST PRIMARY KEY CLUSTERED (CODIGO)
        );
    END;

    IF OBJECT_ID('dbo.TAREFAEST', 'U') IS NULL
    BEGIN
        CREATE TABLE dbo.TAREFAEST
        (
            CODIGO NUMERIC(2,0) NOT NULL,
            NOME   VARCHAR(40) NOT NULL,
            ORDEM  INT NOT NULL CONSTRAINT DF_TAREFAEST_ORDEM DEFAULT (0),
            COR    VARCHAR(20) NOT NULL CONSTRAINT DF_TAREFAEST_COR DEFAULT ('secondary'),
            FINAL  BIT NOT NULL CONSTRAINT DF_TAREFAEST_FINAL DEFAULT (0),
            ATIVO  BIT NOT NULL CONSTRAINT DF_TAREFAEST_ATIVO DEFAULT (1),
            CONSTRAINT PK_TAREFAEST PRIMARY KEY CLUSTERED (CODIGO)
        );
    END;

    IF COL_LENGTH('dbo.TAREFAS', 'ESTADO') IS NULL
        ALTER TABLE dbo.TAREFAS ADD ESTADO NUMERIC(2,0) NOT NULL CONSTRAINT DF_TAREFAS_ESTADO DEFAULT (1);

    IF COL_LENGTH('dbo.TAREFAS', 'PRIORIDADE') IS NULL
        ALTER TABLE dbo.TAREFAS ADD PRIORIDADE NUMERIC(2,0) NOT NULL CONSTRAINT DF_TAREFAS_PRIORIDADE DEFAULT (2);

    IF COL_LENGTH('dbo.TAREFAS', 'DESCRICAO') IS NULL
        ALTER TABLE dbo.TAREFAS ADD DESCRICAO VARCHAR(MAX) NULL;

    IF COL_LENGTH('dbo.TAREFAS', 'DTCONCLUIDA') IS NULL
        ALTER TABLE dbo.TAREFAS ADD DTCONCLUIDA DATETIME2(0) NULL;

    IF COL_LENGTH('dbo.TAREFAS', 'DTCriacao') IS NULL
        ALTER TABLE dbo.TAREFAS ADD DTCriacao DATETIME2(0) NOT NULL CONSTRAINT DF_TAREFAS_DTCriacao DEFAULT (SYSDATETIME());

    IF COL_LENGTH('dbo.TAREFAS', 'DTAlteracao') IS NULL
        ALTER TABLE dbo.TAREFAS ADD DTAlteracao DATETIME2(0) NOT NULL CONSTRAINT DF_TAREFAS_DTAlteracao DEFAULT (SYSDATETIME());

    IF COL_LENGTH('dbo.TAREFAS', 'USERCRIACAO') IS NULL
        ALTER TABLE dbo.TAREFAS ADD USERCRIACAO VARCHAR(60) NOT NULL CONSTRAINT DF_TAREFAS_USERCRIACAO DEFAULT ('');

    IF COL_LENGTH('dbo.TAREFAS', 'USERALTERACAO') IS NULL
        ALTER TABLE dbo.TAREFAS ADD USERALTERACAO VARCHAR(60) NOT NULL CONSTRAINT DF_TAREFAS_USERALTERACAO DEFAULT ('');

    IF NOT EXISTS (
        SELECT 1
        FROM sys.indexes
        WHERE name = 'IX_TAREFAS_PROJ_ORIGEM'
          AND object_id = OBJECT_ID('dbo.TAREFAS')
    )
    BEGIN
        CREATE INDEX IX_TAREFAS_PROJ_ORIGEM
            ON dbo.TAREFAS (ORIGEM, ORISTAMP, ESTADO, DATA, HORA);
    END;

    MERGE dbo.PROJEST AS T
    USING (VALUES
        (CONVERT(NUMERIC(2,0), 1), 'Planeado', 10, 'secondary', 0, 1),
        (CONVERT(NUMERIC(2,0), 2), 'Em curso', 20, 'primary', 0, 1),
        (CONVERT(NUMERIC(2,0), 3), 'Em espera', 30, 'warning', 0, 1),
        (CONVERT(NUMERIC(2,0), 4), 'Concluido', 40, 'success', 1, 1),
        (CONVERT(NUMERIC(2,0), 5), 'Cancelado', 50, 'danger', 1, 1)
    ) AS S (CODIGO, NOME, ORDEM, COR, FINAL, ATIVO)
       ON T.CODIGO = S.CODIGO
    WHEN MATCHED THEN
        UPDATE SET
            T.NOME = S.NOME,
            T.ORDEM = S.ORDEM,
            T.COR = S.COR,
            T.FINAL = S.FINAL,
            T.ATIVO = S.ATIVO
    WHEN NOT MATCHED THEN
        INSERT (CODIGO, NOME, ORDEM, COR, FINAL, ATIVO)
        VALUES (S.CODIGO, S.NOME, S.ORDEM, S.COR, S.FINAL, S.ATIVO);

    MERGE dbo.TAREFAEST AS T
    USING (VALUES
        (CONVERT(NUMERIC(2,0), 1), 'Por fazer', 10, 'secondary', 0, 1),
        (CONVERT(NUMERIC(2,0), 2), 'Em curso', 20, 'primary', 0, 1),
        (CONVERT(NUMERIC(2,0), 3), 'Em espera', 30, 'warning', 0, 1),
        (CONVERT(NUMERIC(2,0), 4), 'Concluida', 40, 'success', 1, 1),
        (CONVERT(NUMERIC(2,0), 5), 'Cancelada', 50, 'danger', 1, 1)
    ) AS S (CODIGO, NOME, ORDEM, COR, FINAL, ATIVO)
       ON T.CODIGO = S.CODIGO
    WHEN MATCHED THEN
        UPDATE SET
            T.NOME = S.NOME,
            T.ORDEM = S.ORDEM,
            T.COR = S.COR,
            T.FINAL = S.FINAL,
            T.ATIVO = S.ATIVO
    WHEN NOT MATCHED THEN
        INSERT (CODIGO, NOME, ORDEM, COR, FINAL, ATIVO)
        VALUES (S.CODIGO, S.NOME, S.ORDEM, S.COR, S.FINAL, S.ATIVO);

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    THROW;
END CATCH;
