SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID('dbo.TRANSFERS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TRANSFERS (
        TRANSFERSTAMP varchar(25) NOT NULL PRIMARY KEY,
        RSSTAMP varchar(25) NOT NULL,
        RESERVA varchar(60) NOT NULL,
        ALOJAMENTO varchar(120) NULL,
        ORIGEM varchar(20) NOT NULL,
        DATA_CHEGADA date NOT NULL,
        HORA_CHEGADA varchar(5) NOT NULL,
        NUM_VOO varchar(20) NULL,
        TEM_PARTIDA bit NOT NULL CONSTRAINT DF_TRANSFERS_TEM_PARTIDA DEFAULT 0,
        DATA_PARTIDA date NULL,
        HORA_PARTIDA varchar(5) NULL,
        VALOR decimal(10,2) NOT NULL CONSTRAINT DF_TRANSFERS_VALOR DEFAULT 30,
        ESTADO varchar(20) NOT NULL CONSTRAINT DF_TRANSFERS_ESTADO DEFAULT 'PENDENTE',
        EMAIL_ID bigint NULL,
        DTCRI datetime NOT NULL CONSTRAINT DF_TRANSFERS_DTCRI DEFAULT GETDATE(),
        DTALT datetime NULL
    );
    CREATE INDEX IX_TRANSFERS_RESERVA ON dbo.TRANSFERS (RESERVA, DTCRI DESC);
END;

DECLARE @menustamp varchar(25);
SELECT TOP 1 @menustamp = MENUSTAMP FROM dbo.MENU WHERE TABELA = 'TRANSFERS';
IF @menustamp IS NULL
BEGIN
    SET @menustamp = LEFT(REPLACE(CONVERT(varchar(36), NEWID()), '-', ''), 25);
    INSERT INTO dbo.MENU (MENUSTAMP, ORDEM, NOME, TABELA, URL, ADMIN, ICONE, FORM, NOVO, INATIVO)
    VALUES (@menustamp, 206, 'Transfers', 'TRANSFERS', '/generic/view/TRANSFERS', 1, 'fa-taxi', '', 0, 0);
END;

UPDATE dbo.MENU
SET ORDEM = 206,
    NOME = 'Transfers',
    URL = '/generic/view/TRANSFERS',
    ADMIN = 1,
    ICONE = 'fa-taxi',
    INATIVO = 0
WHERE MENUSTAMP = @menustamp;

DECLARE @fields TABLE (NMCAMPO varchar(25), DESCRICAO varchar(60), TIPO varchar(18), ORDEM int, TAM int, LISTA bit, FILTRO bit, RONLY bit, OBRIGATORIO bit);
INSERT INTO @fields VALUES
 ('RESERVA','Reserva','TEXT',10,15,1,1,1,1), ('ALOJAMENTO','Alojamento','TEXT',20,20,1,1,1,0),
 ('ORIGEM','Origem','TEXT',30,15,1,1,0,1), ('DATA_CHEGADA','Data chegada','DATE',40,10,1,1,0,1),
 ('HORA_CHEGADA','Hora chegada','TEXT',50,8,1,0,0,1), ('NUM_VOO','N.º voo','TEXT',60,10,1,0,0,0),
 ('TEM_PARTIDA','Tem partida','BIT',70,8,1,1,0,0), ('DATA_PARTIDA','Data partida','DATE',80,10,1,1,0,0),
 ('HORA_PARTIDA','Hora partida','TEXT',90,8,1,0,0,0), ('VALOR','Valor','DECIMAL',100,8,1,0,1,1),
 ('ESTADO','Estado','TEXT',110,10,1,1,0,1), ('EMAIL_ID','Email','INT',120,10,0,0,1,0);

MERGE dbo.CAMPOS AS T USING @fields AS S ON T.TABELA='TRANSFERS' AND T.NMCAMPO=S.NMCAMPO
WHEN MATCHED THEN UPDATE SET DESCRICAO=S.DESCRICAO,TIPO=S.TIPO,ORDEM=S.ORDEM,TAM=S.TAM,LISTA=S.LISTA,FILTRO=S.FILTRO,RONLY=S.RONLY,OBRIGATORIO=S.OBRIGATORIO,VISIVEL=1
WHEN NOT MATCHED THEN INSERT (CAMPOSSTAMP,ORDEM,NMCAMPO,DESCRICAO,TIPO,TABELA,LISTA,FILTRO,FILTRODEFAULT,ADMIN,RONLY,COMBO,VIRTUAL,VISIVEL,TAM,ORDEM_MOBILE,TAM_MOBILE,CONDICAO_VISIVEL,OBRIGATORIO)
VALUES (LEFT(REPLACE(CONVERT(varchar(36), NEWID()), '-', ''),25),S.ORDEM,S.NMCAMPO,S.DESCRICAO,S.TIPO,'TRANSFERS',S.LISTA,S.FILTRO,'',0,S.RONLY,'','',1,S.TAM,S.ORDEM,S.TAM,'',S.OBRIGATORIO);

COMMIT TRANSACTION;
