SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.RH_KMS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.RH_KMS
    (
        RH_KMSSTAMP VARCHAR(25) NOT NULL
            CONSTRAINT DF_RH_KMS_RH_KMSSTAMP DEFAULT LEFT(CONVERT(varchar(36), NEWID()), 25),
        ANO INT NOT NULL CONSTRAINT DF_RH_KMS_ANO DEFAULT (0),
        MES INT NOT NULL CONSTRAINT DF_RH_KMS_MES DEFAULT (0),
        UTILIZADOR VARCHAR(50) NOT NULL CONSTRAINT DF_RH_KMS_UTILIZADOR DEFAULT (''),
        RESERVA VARCHAR(25) NOT NULL CONSTRAINT DF_RH_KMS_RESERVA DEFAULT (''),
        ORIGEM NVARCHAR(200) NOT NULL CONSTRAINT DF_RH_KMS_ORIGEM DEFAULT (''),
        DESTINO NVARCHAR(200) NOT NULL CONSTRAINT DF_RH_KMS_DESTINO DEFAULT (''),
        KMS DECIMAL(12,2) NOT NULL CONSTRAINT DF_RH_KMS_KMS DEFAULT (0),
        VALOR_KM DECIMAL(12,2) NOT NULL CONSTRAINT DF_RH_KMS_VALOR_KM DEFAULT (0),
        VALOR_TOTAL DECIMAL(12,2) NOT NULL CONSTRAINT DF_RH_KMS_VALOR_TOTAL DEFAULT (0),
        OBS VARCHAR(200) NOT NULL CONSTRAINT DF_RH_KMS_OBS DEFAULT (''),
        CONSTRAINT PK_RH_KMS PRIMARY KEY CLUSTERED (RH_KMSSTAMP)
    );
END
GO

IF OBJECT_ID('dbo.RH_KMS', 'U') IS NOT NULL
   AND NOT EXISTS (
        SELECT 1
        FROM sys.indexes
        WHERE object_id = OBJECT_ID('dbo.RH_KMS')
          AND name = 'UX_RH_KMS_RESERVA'
   )
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX UX_RH_KMS_RESERVA
        ON dbo.RH_KMS (RESERVA);
END
GO
