SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    /* =========================================================
       CREATE TABLE
       ========================================================= */

    CREATE TABLE dbo.SHOP_FAMILIAS
    (
        FAMILIA_ID          INT IDENTITY(1,1) NOT NULL,
        CODIGO              NVARCHAR(50) NOT NULL,
        NOME                NVARCHAR(100) NOT NULL,
        TITULO              NVARCHAR(150) NULL,
        DESCRICAO           NVARCHAR(500) NULL,
        ORDEM               INT NOT NULL CONSTRAINT DF_SHOP_FAMILIAS_ORDEM DEFAULT (0),
        ATIVO               BIT NOT NULL CONSTRAINT DF_SHOP_FAMILIAS_ATIVO DEFAULT (1),
        CRIADO_EM           DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_FAMILIAS_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        ALTERADO_EM         DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_FAMILIAS_ALTERADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SHOP_FAMILIAS PRIMARY KEY CLUSTERED (FAMILIA_ID)
    );

    CREATE TABLE dbo.SHOP_PRODUTOS
    (
        PRODUTO_ID          INT IDENTITY(1,1) NOT NULL,
        FAMILIA_ID          INT NOT NULL,
        CODIGO              NVARCHAR(50) NOT NULL,
        NOME                NVARCHAR(150) NOT NULL,
        TITULO              NVARCHAR(200) NULL,
        SUBTITULO           NVARCHAR(200) NULL,
        DESCRICAO_CURTA     NVARCHAR(500) NULL,
        DESCRICAO           NVARCHAR(MAX) NULL,
        PRECO               DECIMAL(19,4) NOT NULL,
        MOEDA               NVARCHAR(3) NOT NULL CONSTRAINT DF_SHOP_PRODUTOS_MOEDA DEFAULT (N'EUR'),
        ORDEM               INT NOT NULL CONSTRAINT DF_SHOP_PRODUTOS_ORDEM DEFAULT (0),
        ATIVO               BIT NOT NULL CONSTRAINT DF_SHOP_PRODUTOS_ATIVO DEFAULT (1),
        CRIADO_EM           DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_PRODUTOS_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        ALTERADO_EM         DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_PRODUTOS_ALTERADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SHOP_PRODUTOS PRIMARY KEY CLUSTERED (PRODUTO_ID)
    );

    CREATE TABLE dbo.SHOP_PRODUTO_IMAGENS
    (
        PRODUTO_IMAGEM_ID   BIGINT IDENTITY(1,1) NOT NULL,
        PRODUTO_ID          INT NOT NULL,
        URL                 NVARCHAR(1000) NOT NULL,
        ALT_TEXT            NVARCHAR(200) NULL,
        ORDEM               INT NOT NULL CONSTRAINT DF_SHOP_PRODUTO_IMAGENS_ORDEM DEFAULT (0),
        E_PRINCIPAL         BIT NOT NULL CONSTRAINT DF_SHOP_PRODUTO_IMAGENS_E_PRINCIPAL DEFAULT (0),
        ATIVO               BIT NOT NULL CONSTRAINT DF_SHOP_PRODUTO_IMAGENS_ATIVO DEFAULT (1),
        CRIADO_EM           DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_PRODUTO_IMAGENS_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        ALTERADO_EM         DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_PRODUTO_IMAGENS_ALTERADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SHOP_PRODUTO_IMAGENS PRIMARY KEY CLUSTERED (PRODUTO_IMAGEM_ID)
    );

    CREATE TABLE dbo.SHOP_PRODUTO_VARIANTES
    (
        PRODUTO_VARIANTE_ID INT IDENTITY(1,1) NOT NULL,
        PRODUTO_ID          INT NOT NULL,
        CODIGO              NVARCHAR(50) NULL,
        TIPO_VARIANTE       NVARCHAR(30) NOT NULL,
        NOME                NVARCHAR(100) NOT NULL,
        VALOR               NVARCHAR(100) NOT NULL,
        DESCRICAO_CURTA     NVARCHAR(300) NULL,
        PRECO               DECIMAL(19,4) NULL,
        ORDEM               INT NOT NULL CONSTRAINT DF_SHOP_PRODUTO_VARIANTES_ORDEM DEFAULT (0),
        PADRAO              BIT NOT NULL CONSTRAINT DF_SHOP_PRODUTO_VARIANTES_PADRAO DEFAULT (0),
        ATIVO               BIT NOT NULL CONSTRAINT DF_SHOP_PRODUTO_VARIANTES_ATIVO DEFAULT (1),
        CRIADO_EM           DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_PRODUTO_VARIANTES_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        ALTERADO_EM         DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_PRODUTO_VARIANTES_ALTERADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SHOP_PRODUTO_VARIANTES PRIMARY KEY CLUSTERED (PRODUTO_VARIANTE_ID)
    );

    CREATE TABLE dbo.SHOP_CARRINHOS
    (
        CARRINHO_ID         BIGINT IDENTITY(1,1) NOT NULL,
        RESERVA             NVARCHAR(50) NOT NULL,
        ESTADO              NVARCHAR(20) NOT NULL CONSTRAINT DF_SHOP_CARRINHOS_ESTADO DEFAULT (N'ABERTO'),
        MOEDA               NVARCHAR(3) NOT NULL CONSTRAINT DF_SHOP_CARRINHOS_MOEDA DEFAULT (N'EUR'),
        SUBTOTAL            DECIMAL(19,4) NOT NULL CONSTRAINT DF_SHOP_CARRINHOS_SUBTOTAL DEFAULT (0),
        TOTAL               DECIMAL(19,4) NOT NULL CONSTRAINT DF_SHOP_CARRINHOS_TOTAL DEFAULT (0),
        ULTIMA_ATIVIDADE_EM DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_CARRINHOS_ULTIMA_ATIVIDADE_EM DEFAULT (SYSUTCDATETIME()),
        CRIADO_EM           DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_CARRINHOS_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        ALTERADO_EM         DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_CARRINHOS_ALTERADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SHOP_CARRINHOS PRIMARY KEY CLUSTERED (CARRINHO_ID)
    );

    CREATE TABLE dbo.SHOP_CARRINHO_LINHAS
    (
        CARRINHO_LINHA_ID   BIGINT IDENTITY(1,1) NOT NULL,
        CARRINHO_ID         BIGINT NOT NULL,
        PRODUTO_ID          INT NOT NULL,
        PRODUTO_VARIANTE_ID INT NULL,
        PRODUTO_NOME        NVARCHAR(150) NOT NULL,
        VARIANTE_NOME       NVARCHAR(100) NULL,
        QUANTIDADE          INT NOT NULL,
        PRECO_UNITARIO      DECIMAL(19,4) NOT NULL,
        SUBTOTAL            DECIMAL(19,4) NOT NULL,
        CRIADO_EM           DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_CARRINHO_LINHAS_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        ALTERADO_EM         DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_CARRINHO_LINHAS_ALTERADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SHOP_CARRINHO_LINHAS PRIMARY KEY CLUSTERED (CARRINHO_LINHA_ID)
    );

    CREATE TABLE dbo.SHOP_ENCOMENDA_ESTADOS
    (
        ENCOMENDA_ESTADO_ID INT IDENTITY(1,1) NOT NULL,
        CODIGO              NVARCHAR(40) NOT NULL,
        NOME                NVARCHAR(100) NOT NULL,
        DESCRICAO           NVARCHAR(300) NULL,
        ORDEM               INT NOT NULL CONSTRAINT DF_SHOP_ENCOMENDA_ESTADOS_ORDEM DEFAULT (0),
        ATIVO               BIT NOT NULL CONSTRAINT DF_SHOP_ENCOMENDA_ESTADOS_ATIVO DEFAULT (1),
        CRIADO_EM           DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_ENCOMENDA_ESTADOS_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        ALTERADO_EM         DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_ENCOMENDA_ESTADOS_ALTERADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SHOP_ENCOMENDA_ESTADOS PRIMARY KEY CLUSTERED (ENCOMENDA_ESTADO_ID)
    );

    CREATE TABLE dbo.SHOP_ENCOMENDAS
    (
        ENCOMENDA_ID        BIGINT IDENTITY(1,1) NOT NULL,
        CARRINHO_ID         BIGINT NULL,
        NUMERO              NVARCHAR(40) NULL,
        RESERVA             NVARCHAR(50) NOT NULL,
        ENCOMENDA_ESTADO_ID INT NOT NULL,
        MOEDA               NVARCHAR(3) NOT NULL CONSTRAINT DF_SHOP_ENCOMENDAS_MOEDA DEFAULT (N'EUR'),
        SUBTOTAL            DECIMAL(19,4) NOT NULL CONSTRAINT DF_SHOP_ENCOMENDAS_SUBTOTAL DEFAULT (0),
        TOTAL               DECIMAL(19,4) NOT NULL CONSTRAINT DF_SHOP_ENCOMENDAS_TOTAL DEFAULT (0),
        TOTAL_PAGO          DECIMAL(19,4) NOT NULL CONSTRAINT DF_SHOP_ENCOMENDAS_TOTAL_PAGO DEFAULT (0),
        TOTAL_REEMBOLSADO   DECIMAL(19,4) NOT NULL CONSTRAINT DF_SHOP_ENCOMENDAS_TOTAL_REEMBOLSADO DEFAULT (0),
        PAGA_EM             DATETIME2(3) NULL,
        CANCELADA_EM        DATETIME2(3) NULL,
        CRIADO_EM           DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_ENCOMENDAS_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        ALTERADO_EM         DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_ENCOMENDAS_ALTERADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SHOP_ENCOMENDAS PRIMARY KEY CLUSTERED (ENCOMENDA_ID)
    );

    CREATE TABLE dbo.SHOP_ENCOMENDA_LINHAS
    (
        ENCOMENDA_LINHA_ID  BIGINT IDENTITY(1,1) NOT NULL,
        ENCOMENDA_ID        BIGINT NOT NULL,
        NUMERO_LINHA        INT NOT NULL,
        PRODUTO_ID          INT NOT NULL,
        PRODUTO_VARIANTE_ID INT NULL,
        PRODUTO_NOME        NVARCHAR(150) NOT NULL,
        VARIANTE_NOME       NVARCHAR(100) NULL,
        QUANTIDADE          INT NOT NULL,
        PRECO_UNITARIO      DECIMAL(19,4) NOT NULL,
        SUBTOTAL            DECIMAL(19,4) NOT NULL,
        TOTAL               DECIMAL(19,4) NOT NULL,
        CRIADO_EM           DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_ENCOMENDA_LINHAS_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        ALTERADO_EM         DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_ENCOMENDA_LINHAS_ALTERADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SHOP_ENCOMENDA_LINHAS PRIMARY KEY CLUSTERED (ENCOMENDA_LINHA_ID)
    );

    CREATE TABLE dbo.SHOP_PAGAMENTOS
    (
        PAGAMENTO_ID        BIGINT IDENTITY(1,1) NOT NULL,
        ENCOMENDA_ID        BIGINT NOT NULL,
        PROVEDOR            NVARCHAR(20) NOT NULL CONSTRAINT DF_SHOP_PAGAMENTOS_PROVEDOR DEFAULT (N'STRIPE'),
        ESTADO              NVARCHAR(30) NOT NULL CONSTRAINT DF_SHOP_PAGAMENTOS_ESTADO DEFAULT (N'PENDENTE'),
        MOEDA               NVARCHAR(3) NOT NULL CONSTRAINT DF_SHOP_PAGAMENTOS_MOEDA DEFAULT (N'EUR'),
        VALOR               DECIMAL(19,4) NOT NULL,
        VALOR_AUTORIZADO    DECIMAL(19,4) NOT NULL CONSTRAINT DF_SHOP_PAGAMENTOS_VALOR_AUTORIZADO DEFAULT (0),
        VALOR_CAPTURADO     DECIMAL(19,4) NOT NULL CONSTRAINT DF_SHOP_PAGAMENTOS_VALOR_CAPTURADO DEFAULT (0),
        VALOR_REEMBOLSADO   DECIMAL(19,4) NOT NULL CONSTRAINT DF_SHOP_PAGAMENTOS_VALOR_REEMBOLSADO DEFAULT (0),
        REFERENCIA_EXTERNA  NVARCHAR(100) NULL,
        PAGO_EM             DATETIME2(3) NULL,
        CRIADO_EM           DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_PAGAMENTOS_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        ALTERADO_EM         DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_PAGAMENTOS_ALTERADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SHOP_PAGAMENTOS PRIMARY KEY CLUSTERED (PAGAMENTO_ID)
    );

    CREATE TABLE dbo.SHOP_TRANSACOES_STRIPE
    (
        TRANSACAO_STRIPE_ID BIGINT IDENTITY(1,1) NOT NULL,
        PAGAMENTO_ID        BIGINT NOT NULL,
        TIPO_TRANSACAO      NVARCHAR(30) NOT NULL,
        EVENT_ID            NVARCHAR(100) NULL,
        EVENT_TYPE          NVARCHAR(100) NULL,
        IDEMPOTENCY_KEY     NVARCHAR(100) NULL,
        PAYMENT_INTENT_ID   NVARCHAR(100) NULL,
        CHECKOUT_SESSION_ID NVARCHAR(100) NULL,
        CHARGE_ID           NVARCHAR(100) NULL,
        REFUND_ID           NVARCHAR(100) NULL,
        EXTERNAL_STATUS     NVARCHAR(50) NULL,
        MOEDA               NVARCHAR(3) NULL,
        VALOR               DECIMAL(19,4) NULL,
        PAYLOAD             NVARCHAR(MAX) NULL,
        CRIADO_EM           DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_TRANSACOES_STRIPE_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SHOP_TRANSACOES_STRIPE PRIMARY KEY CLUSTERED (TRANSACAO_STRIPE_ID)
    );

    CREATE TABLE dbo.SHOP_REEMBOLSOS
    (
        REEMBOLSO_ID        BIGINT IDENTITY(1,1) NOT NULL,
        PAGAMENTO_ID        BIGINT NOT NULL,
        ESTADO              NVARCHAR(30) NOT NULL CONSTRAINT DF_SHOP_REEMBOLSOS_ESTADO DEFAULT (N'PENDENTE'),
        MOEDA               NVARCHAR(3) NOT NULL CONSTRAINT DF_SHOP_REEMBOLSOS_MOEDA DEFAULT (N'EUR'),
        VALOR               DECIMAL(19,4) NOT NULL,
        MOTIVO              NVARCHAR(200) NULL,
        REFUND_ID_EXTERNO   NVARCHAR(100) NULL,
        PROCESSADO_EM       DATETIME2(3) NULL,
        CRIADO_EM           DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_REEMBOLSOS_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        ALTERADO_EM         DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_REEMBOLSOS_ALTERADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SHOP_REEMBOLSOS PRIMARY KEY CLUSTERED (REEMBOLSO_ID)
    );

    CREATE TABLE dbo.SHOP_STOCK_MOVIMENTOS
    (
        STOCK_MOVIMENTO_ID  BIGINT IDENTITY(1,1) NOT NULL,
        PRODUTO_ID          INT NOT NULL,
        PRODUTO_VARIANTE_ID INT NULL,
        ENCOMENDA_LINHA_ID  BIGINT NULL,
        TIPO_MOVIMENTO      NVARCHAR(20) NOT NULL,
        ORIGEM              NVARCHAR(30) NULL,
        QUANTIDADE          DECIMAL(18,3) NOT NULL,
        CRIADO_EM           DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_STOCK_MOVIMENTOS_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SHOP_STOCK_MOVIMENTOS PRIMARY KEY CLUSTERED (STOCK_MOVIMENTO_ID)
    );

    CREATE TABLE dbo.SHOP_CONFIG
    (
        CONFIG_ID           INT IDENTITY(1,1) NOT NULL,
        CHAVE               NVARCHAR(100) NOT NULL,
        VALOR               NVARCHAR(MAX) NULL,
        TIPO_VALOR          NVARCHAR(20) NOT NULL CONSTRAINT DF_SHOP_CONFIG_TIPO_VALOR DEFAULT (N'STRING'),
        DESCRICAO           NVARCHAR(300) NULL,
        ATIVO               BIT NOT NULL CONSTRAINT DF_SHOP_CONFIG_ATIVO DEFAULT (1),
        CRIADO_EM           DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_CONFIG_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        ALTERADO_EM         DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_CONFIG_ALTERADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SHOP_CONFIG PRIMARY KEY CLUSTERED (CONFIG_ID)
    );

    CREATE TABLE dbo.SHOP_LOGS
    (
        LOG_ID              BIGINT IDENTITY(1,1) NOT NULL,
        NIVEL               NVARCHAR(10) NOT NULL,
        CATEGORIA           NVARCHAR(50) NOT NULL,
        EVENTO              NVARCHAR(100) NULL,
        ENTIDADE            NVARCHAR(50) NULL,
        ENTIDADE_ID         NVARCHAR(100) NULL,
        RESERVA             NVARCHAR(50) NULL,
        ENCOMENDA_ID        BIGINT NULL,
        PAGAMENTO_ID        BIGINT NULL,
        TRANSACAO_STRIPE_ID BIGINT NULL,
        MENSAGEM            NVARCHAR(1000) NOT NULL,
        DETALHE             NVARCHAR(MAX) NULL,
        CRIADO_EM           DATETIME2(3) NOT NULL CONSTRAINT DF_SHOP_LOGS_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_SHOP_LOGS PRIMARY KEY CLUSTERED (LOG_ID)
    );

    /* =========================================================
       CONSTRAINTS
       ========================================================= */

    ALTER TABLE dbo.SHOP_FAMILIAS
        ADD CONSTRAINT UQ_SHOP_FAMILIAS_CODIGO UNIQUE (CODIGO),
            CONSTRAINT CK_SHOP_FAMILIAS_CODIGO CHECK (LEN(LTRIM(RTRIM(CODIGO))) > 0),
            CONSTRAINT CK_SHOP_FAMILIAS_NOME CHECK (LEN(LTRIM(RTRIM(NOME))) > 0),
            CONSTRAINT CK_SHOP_FAMILIAS_ORDEM CHECK (ORDEM >= 0);

    ALTER TABLE dbo.SHOP_PRODUTOS
        ADD CONSTRAINT UQ_SHOP_PRODUTOS_CODIGO UNIQUE (CODIGO),
            CONSTRAINT CK_SHOP_PRODUTOS_CODIGO CHECK (LEN(LTRIM(RTRIM(CODIGO))) > 0),
            CONSTRAINT CK_SHOP_PRODUTOS_NOME CHECK (LEN(LTRIM(RTRIM(NOME))) > 0),
            CONSTRAINT CK_SHOP_PRODUTOS_PRECO CHECK (PRECO >= 0),
            CONSTRAINT CK_SHOP_PRODUTOS_MOEDA CHECK (LEN(MOEDA) = 3),
            CONSTRAINT CK_SHOP_PRODUTOS_ORDEM CHECK (ORDEM >= 0);

    ALTER TABLE dbo.SHOP_PRODUTO_IMAGENS
        ADD CONSTRAINT CK_SHOP_PRODUTO_IMAGENS_URL CHECK (LEN(LTRIM(RTRIM(URL))) > 0),
            CONSTRAINT CK_SHOP_PRODUTO_IMAGENS_ORDEM CHECK (ORDEM >= 0);

    ALTER TABLE dbo.SHOP_PRODUTO_VARIANTES
        ADD CONSTRAINT UQ_SHOP_PRODUTO_VARIANTES_ITEM UNIQUE (PRODUTO_ID, TIPO_VARIANTE, VALOR),
            CONSTRAINT UQ_SHOP_PRODUTO_VARIANTES_VARIANTE_PRODUTO UNIQUE (PRODUTO_VARIANTE_ID, PRODUTO_ID),
            CONSTRAINT CK_SHOP_PRODUTO_VARIANTES_TIPO CHECK (TIPO_VARIANTE IN (N'TAMANHO', N'CAPACIDADE', N'FORMATO', N'UNIDADE', N'OUTRO')),
            CONSTRAINT CK_SHOP_PRODUTO_VARIANTES_NOME CHECK (LEN(LTRIM(RTRIM(NOME))) > 0),
            CONSTRAINT CK_SHOP_PRODUTO_VARIANTES_VALOR CHECK (LEN(LTRIM(RTRIM(VALOR))) > 0),
            CONSTRAINT CK_SHOP_PRODUTO_VARIANTES_PRECO CHECK (PRECO IS NULL OR PRECO >= 0),
            CONSTRAINT CK_SHOP_PRODUTO_VARIANTES_ORDEM CHECK (ORDEM >= 0);

    ALTER TABLE dbo.SHOP_CARRINHOS
        ADD CONSTRAINT CK_SHOP_CARRINHOS_RESERVA CHECK (LEN(LTRIM(RTRIM(RESERVA))) > 0),
            CONSTRAINT CK_SHOP_CARRINHOS_ESTADO CHECK (ESTADO IN (N'ABERTO', N'CONVERTIDO', N'EXPIRADO', N'CANCELADO')),
            CONSTRAINT CK_SHOP_CARRINHOS_MOEDA CHECK (LEN(MOEDA) = 3),
            CONSTRAINT CK_SHOP_CARRINHOS_TOTALS CHECK (SUBTOTAL >= 0 AND TOTAL >= SUBTOTAL);

    ALTER TABLE dbo.SHOP_CARRINHO_LINHAS
        ADD CONSTRAINT CK_SHOP_CARRINHO_LINHAS_PRODUTO_NOME CHECK (LEN(LTRIM(RTRIM(PRODUTO_NOME))) > 0),
            CONSTRAINT CK_SHOP_CARRINHO_LINHAS_QTD CHECK (QUANTIDADE > 0),
            CONSTRAINT CK_SHOP_CARRINHO_LINHAS_PRECO CHECK (PRECO_UNITARIO >= 0),
            CONSTRAINT CK_SHOP_CARRINHO_LINHAS_SUBTOTAL CHECK (SUBTOTAL = ROUND(PRECO_UNITARIO * QUANTIDADE, 4));

    ALTER TABLE dbo.SHOP_ENCOMENDA_ESTADOS
        ADD CONSTRAINT UQ_SHOP_ENCOMENDA_ESTADOS_CODIGO UNIQUE (CODIGO),
            CONSTRAINT CK_SHOP_ENCOMENDA_ESTADOS_CODIGO CHECK (LEN(LTRIM(RTRIM(CODIGO))) > 0),
            CONSTRAINT CK_SHOP_ENCOMENDA_ESTADOS_NOME CHECK (LEN(LTRIM(RTRIM(NOME))) > 0),
            CONSTRAINT CK_SHOP_ENCOMENDA_ESTADOS_ORDEM CHECK (ORDEM >= 0);

    ALTER TABLE dbo.SHOP_ENCOMENDAS
        ADD CONSTRAINT CK_SHOP_ENCOMENDAS_NUMERO CHECK (NUMERO IS NULL OR LEN(LTRIM(RTRIM(NUMERO))) > 0),
            CONSTRAINT CK_SHOP_ENCOMENDAS_RESERVA CHECK (LEN(LTRIM(RTRIM(RESERVA))) > 0),
            CONSTRAINT CK_SHOP_ENCOMENDAS_MOEDA CHECK (LEN(MOEDA) = 3),
            CONSTRAINT CK_SHOP_ENCOMENDAS_TOTALS CHECK (
                SUBTOTAL >= 0
                AND TOTAL >= SUBTOTAL
                AND TOTAL_PAGO >= 0
                AND TOTAL_REEMBOLSADO >= 0
                AND TOTAL_PAGO <= TOTAL
                AND TOTAL_REEMBOLSADO <= TOTAL_PAGO
            );

    ALTER TABLE dbo.SHOP_ENCOMENDA_LINHAS
        ADD CONSTRAINT UQ_SHOP_ENCOMENDA_LINHAS_NUMERO UNIQUE (ENCOMENDA_ID, NUMERO_LINHA),
            CONSTRAINT CK_SHOP_ENCOMENDA_LINHAS_PRODUTO_NOME CHECK (LEN(LTRIM(RTRIM(PRODUTO_NOME))) > 0),
            CONSTRAINT CK_SHOP_ENCOMENDA_LINHAS_QTD CHECK (QUANTIDADE > 0),
            CONSTRAINT CK_SHOP_ENCOMENDA_LINHAS_PRECO CHECK (PRECO_UNITARIO >= 0),
            CONSTRAINT CK_SHOP_ENCOMENDA_LINHAS_SUBTOTAL CHECK (SUBTOTAL = ROUND(PRECO_UNITARIO * QUANTIDADE, 4)),
            CONSTRAINT CK_SHOP_ENCOMENDA_LINHAS_TOTAL CHECK (TOTAL >= SUBTOTAL);

    ALTER TABLE dbo.SHOP_PAGAMENTOS
        ADD CONSTRAINT CK_SHOP_PAGAMENTOS_PROVEDOR CHECK (PROVEDOR = N'STRIPE'),
            CONSTRAINT CK_SHOP_PAGAMENTOS_ESTADO CHECK (ESTADO IN (N'PENDENTE', N'AUTORIZADO', N'PAGO', N'FALHADO', N'CANCELADO', N'PARCIALMENTE_REEMBOLSADO', N'REEMBOLSADO')),
            CONSTRAINT CK_SHOP_PAGAMENTOS_MOEDA CHECK (LEN(MOEDA) = 3),
            CONSTRAINT CK_SHOP_PAGAMENTOS_VALORES CHECK (
                VALOR >= 0
                AND VALOR_AUTORIZADO >= 0
                AND VALOR_CAPTURADO >= 0
                AND VALOR_REEMBOLSADO >= 0
                AND VALOR_AUTORIZADO <= VALOR
                AND VALOR_CAPTURADO <= VALOR_AUTORIZADO
                AND VALOR_REEMBOLSADO <= VALOR_CAPTURADO
            );

    ALTER TABLE dbo.SHOP_TRANSACOES_STRIPE
        ADD CONSTRAINT CK_SHOP_TRANSACOES_STRIPE_TIPO CHECK (TIPO_TRANSACAO IN (N'CHECKOUT_SESSION', N'PAYMENT_INTENT', N'CHARGE', N'REFUND', N'WEBHOOK')),
            CONSTRAINT CK_SHOP_TRANSACOES_STRIPE_MOEDA CHECK (MOEDA IS NULL OR LEN(MOEDA) = 3),
            CONSTRAINT CK_SHOP_TRANSACOES_STRIPE_VALOR CHECK (VALOR IS NULL OR VALOR >= 0);

    ALTER TABLE dbo.SHOP_REEMBOLSOS
        ADD CONSTRAINT CK_SHOP_REEMBOLSOS_ESTADO CHECK (ESTADO IN (N'PENDENTE', N'PROCESSADO', N'FALHADO', N'CANCELADO')),
            CONSTRAINT CK_SHOP_REEMBOLSOS_MOEDA CHECK (LEN(MOEDA) = 3),
            CONSTRAINT CK_SHOP_REEMBOLSOS_VALOR CHECK (VALOR > 0);

    ALTER TABLE dbo.SHOP_STOCK_MOVIMENTOS
        ADD CONSTRAINT CK_SHOP_STOCK_MOVIMENTOS_TIPO CHECK (TIPO_MOVIMENTO IN (N'ENTRADA', N'SAIDA', N'AJUSTE_ENTRADA', N'AJUSTE_SAIDA')),
            CONSTRAINT CK_SHOP_STOCK_MOVIMENTOS_QUANTIDADE CHECK (QUANTIDADE > 0);

    ALTER TABLE dbo.SHOP_CONFIG
        ADD CONSTRAINT UQ_SHOP_CONFIG_CHAVE UNIQUE (CHAVE),
            CONSTRAINT CK_SHOP_CONFIG_CHAVE CHECK (LEN(LTRIM(RTRIM(CHAVE))) > 0),
            CONSTRAINT CK_SHOP_CONFIG_TIPO_VALOR CHECK (TIPO_VALOR IN (N'STRING', N'INT', N'DECIMAL', N'BIT', N'JSON'));

    ALTER TABLE dbo.SHOP_LOGS
        ADD CONSTRAINT CK_SHOP_LOGS_NIVEL CHECK (NIVEL IN (N'TRACE', N'DEBUG', N'INFO', N'WARN', N'ERROR', N'FATAL')),
            CONSTRAINT CK_SHOP_LOGS_CATEGORIA CHECK (LEN(LTRIM(RTRIM(CATEGORIA))) > 0),
            CONSTRAINT CK_SHOP_LOGS_MENSAGEM CHECK (LEN(LTRIM(RTRIM(MENSAGEM))) > 0);

    /* =========================================================
       FOREIGN KEYS
       ========================================================= */

    ALTER TABLE dbo.SHOP_PRODUTOS
        ADD CONSTRAINT FK_SHOP_PRODUTOS_SHOP_FAMILIAS
            FOREIGN KEY (FAMILIA_ID) REFERENCES dbo.SHOP_FAMILIAS (FAMILIA_ID)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;

    ALTER TABLE dbo.SHOP_PRODUTO_IMAGENS
        ADD CONSTRAINT FK_SHOP_PRODUTO_IMAGENS_SHOP_PRODUTOS
            FOREIGN KEY (PRODUTO_ID) REFERENCES dbo.SHOP_PRODUTOS (PRODUTO_ID)
            ON DELETE CASCADE
            ON UPDATE NO ACTION;

    ALTER TABLE dbo.SHOP_PRODUTO_VARIANTES
        ADD CONSTRAINT FK_SHOP_PRODUTO_VARIANTES_SHOP_PRODUTOS
            FOREIGN KEY (PRODUTO_ID) REFERENCES dbo.SHOP_PRODUTOS (PRODUTO_ID)
            ON DELETE CASCADE
            ON UPDATE NO ACTION;

    ALTER TABLE dbo.SHOP_CARRINHO_LINHAS
        ADD CONSTRAINT FK_SHOP_CARRINHO_LINHAS_SHOP_CARRINHOS
            FOREIGN KEY (CARRINHO_ID) REFERENCES dbo.SHOP_CARRINHOS (CARRINHO_ID)
            ON DELETE CASCADE
            ON UPDATE NO ACTION,
            CONSTRAINT FK_SHOP_CARRINHO_LINHAS_SHOP_PRODUTOS
            FOREIGN KEY (PRODUTO_ID) REFERENCES dbo.SHOP_PRODUTOS (PRODUTO_ID)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
            CONSTRAINT FK_SHOP_CARRINHO_LINHAS_SHOP_PRODUTO_VARIANTES
            FOREIGN KEY (PRODUTO_VARIANTE_ID, PRODUTO_ID) REFERENCES dbo.SHOP_PRODUTO_VARIANTES (PRODUTO_VARIANTE_ID, PRODUTO_ID)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;

    ALTER TABLE dbo.SHOP_ENCOMENDAS
        ADD CONSTRAINT FK_SHOP_ENCOMENDAS_SHOP_CARRINHOS
            FOREIGN KEY (CARRINHO_ID) REFERENCES dbo.SHOP_CARRINHOS (CARRINHO_ID)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
            CONSTRAINT FK_SHOP_ENCOMENDAS_SHOP_ENCOMENDA_ESTADOS
            FOREIGN KEY (ENCOMENDA_ESTADO_ID) REFERENCES dbo.SHOP_ENCOMENDA_ESTADOS (ENCOMENDA_ESTADO_ID)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;

    ALTER TABLE dbo.SHOP_ENCOMENDA_LINHAS
        ADD CONSTRAINT FK_SHOP_ENCOMENDA_LINHAS_SHOP_ENCOMENDAS
            FOREIGN KEY (ENCOMENDA_ID) REFERENCES dbo.SHOP_ENCOMENDAS (ENCOMENDA_ID)
            ON DELETE CASCADE
            ON UPDATE NO ACTION,
            CONSTRAINT FK_SHOP_ENCOMENDA_LINHAS_SHOP_PRODUTOS
            FOREIGN KEY (PRODUTO_ID) REFERENCES dbo.SHOP_PRODUTOS (PRODUTO_ID)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
            CONSTRAINT FK_SHOP_ENCOMENDA_LINHAS_SHOP_PRODUTO_VARIANTES
            FOREIGN KEY (PRODUTO_VARIANTE_ID, PRODUTO_ID) REFERENCES dbo.SHOP_PRODUTO_VARIANTES (PRODUTO_VARIANTE_ID, PRODUTO_ID)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;

    ALTER TABLE dbo.SHOP_PAGAMENTOS
        ADD CONSTRAINT FK_SHOP_PAGAMENTOS_SHOP_ENCOMENDAS
            FOREIGN KEY (ENCOMENDA_ID) REFERENCES dbo.SHOP_ENCOMENDAS (ENCOMENDA_ID)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;

    ALTER TABLE dbo.SHOP_TRANSACOES_STRIPE
        ADD CONSTRAINT FK_SHOP_TRANSACOES_STRIPE_SHOP_PAGAMENTOS
            FOREIGN KEY (PAGAMENTO_ID) REFERENCES dbo.SHOP_PAGAMENTOS (PAGAMENTO_ID)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;

    ALTER TABLE dbo.SHOP_REEMBOLSOS
        ADD CONSTRAINT FK_SHOP_REEMBOLSOS_SHOP_PAGAMENTOS
            FOREIGN KEY (PAGAMENTO_ID) REFERENCES dbo.SHOP_PAGAMENTOS (PAGAMENTO_ID)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;

    ALTER TABLE dbo.SHOP_STOCK_MOVIMENTOS
        ADD CONSTRAINT FK_SHOP_STOCK_MOVIMENTOS_SHOP_PRODUTOS
            FOREIGN KEY (PRODUTO_ID) REFERENCES dbo.SHOP_PRODUTOS (PRODUTO_ID)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
            CONSTRAINT FK_SHOP_STOCK_MOVIMENTOS_SHOP_PRODUTO_VARIANTES
            FOREIGN KEY (PRODUTO_VARIANTE_ID, PRODUTO_ID) REFERENCES dbo.SHOP_PRODUTO_VARIANTES (PRODUTO_VARIANTE_ID, PRODUTO_ID)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
            CONSTRAINT FK_SHOP_STOCK_MOVIMENTOS_SHOP_ENCOMENDA_LINHAS
            FOREIGN KEY (ENCOMENDA_LINHA_ID) REFERENCES dbo.SHOP_ENCOMENDA_LINHAS (ENCOMENDA_LINHA_ID)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;

    ALTER TABLE dbo.SHOP_LOGS
        ADD CONSTRAINT FK_SHOP_LOGS_SHOP_ENCOMENDAS
            FOREIGN KEY (ENCOMENDA_ID) REFERENCES dbo.SHOP_ENCOMENDAS (ENCOMENDA_ID)
            ON DELETE SET NULL
            ON UPDATE NO ACTION,
            CONSTRAINT FK_SHOP_LOGS_SHOP_PAGAMENTOS
            FOREIGN KEY (PAGAMENTO_ID) REFERENCES dbo.SHOP_PAGAMENTOS (PAGAMENTO_ID)
            ON DELETE SET NULL
            ON UPDATE NO ACTION,
            CONSTRAINT FK_SHOP_LOGS_SHOP_TRANSACOES_STRIPE
            FOREIGN KEY (TRANSACAO_STRIPE_ID) REFERENCES dbo.SHOP_TRANSACOES_STRIPE (TRANSACAO_STRIPE_ID)
            ON DELETE SET NULL
            ON UPDATE NO ACTION;

    /* =========================================================
       INDEXES
       ========================================================= */

    CREATE INDEX IX_SHOP_FAMILIAS_ATIVO_ORDEM
        ON dbo.SHOP_FAMILIAS (ATIVO, ORDEM, NOME);

    CREATE INDEX IX_SHOP_PRODUTOS_FAMILIA_ATIVO_ORDEM
        ON dbo.SHOP_PRODUTOS (FAMILIA_ID, ATIVO, ORDEM, NOME)
        INCLUDE (PRECO, TITULO, SUBTITULO, DESCRICAO_CURTA, MOEDA);

    CREATE INDEX IX_SHOP_PRODUTO_IMAGENS_PRODUTO_ORDEM
        ON dbo.SHOP_PRODUTO_IMAGENS (PRODUTO_ID, ORDEM, PRODUTO_IMAGEM_ID);

    CREATE UNIQUE INDEX UX_SHOP_PRODUTO_IMAGENS_PRINCIPAL
        ON dbo.SHOP_PRODUTO_IMAGENS (PRODUTO_ID)
        WHERE E_PRINCIPAL = 1;

    CREATE INDEX IX_SHOP_PRODUTO_VARIANTES_PRODUTO_ATIVO_ORDEM
        ON dbo.SHOP_PRODUTO_VARIANTES (PRODUTO_ID, ATIVO, ORDEM, PRODUTO_VARIANTE_ID)
        INCLUDE (NOME, VALOR, PRECO, PADRAO, TIPO_VARIANTE);

    CREATE UNIQUE INDEX UX_SHOP_PRODUTO_VARIANTES_CODIGO
        ON dbo.SHOP_PRODUTO_VARIANTES (CODIGO)
        WHERE CODIGO IS NOT NULL;

    CREATE UNIQUE INDEX UX_SHOP_PRODUTO_VARIANTES_PADRAO
        ON dbo.SHOP_PRODUTO_VARIANTES (PRODUTO_ID)
        WHERE PADRAO = 1;

    CREATE INDEX IX_SHOP_CARRINHOS_RESERVA_ESTADO
        ON dbo.SHOP_CARRINHOS (RESERVA, ESTADO, ALTERADO_EM DESC)
        INCLUDE (SUBTOTAL, TOTAL, ULTIMA_ATIVIDADE_EM);

    CREATE UNIQUE INDEX UX_SHOP_CARRINHOS_RESERVA_ABERTO
        ON dbo.SHOP_CARRINHOS (RESERVA)
        WHERE ESTADO = N'ABERTO';

    CREATE INDEX IX_SHOP_CARRINHO_LINHAS_CARRINHO
        ON dbo.SHOP_CARRINHO_LINHAS (CARRINHO_ID, CARRINHO_LINHA_ID)
        INCLUDE (PRODUTO_ID, PRODUTO_VARIANTE_ID, QUANTIDADE, PRECO_UNITARIO, SUBTOTAL);

    CREATE INDEX IX_SHOP_CARRINHO_LINHAS_PRODUTO
        ON dbo.SHOP_CARRINHO_LINHAS (PRODUTO_ID, PRODUTO_VARIANTE_ID);

    CREATE UNIQUE INDEX UX_SHOP_CARRINHO_LINHAS_SEM_VARIANTE
        ON dbo.SHOP_CARRINHO_LINHAS (CARRINHO_ID, PRODUTO_ID)
        WHERE PRODUTO_VARIANTE_ID IS NULL;

    CREATE UNIQUE INDEX UX_SHOP_CARRINHO_LINHAS_COM_VARIANTE
        ON dbo.SHOP_CARRINHO_LINHAS (CARRINHO_ID, PRODUTO_ID, PRODUTO_VARIANTE_ID)
        WHERE PRODUTO_VARIANTE_ID IS NOT NULL;

    CREATE INDEX IX_SHOP_ENCOMENDA_ESTADOS_ATIVO_ORDEM
        ON dbo.SHOP_ENCOMENDA_ESTADOS (ATIVO, ORDEM, NOME);

    CREATE INDEX IX_SHOP_ENCOMENDAS_RESERVA_CRIADO
        ON dbo.SHOP_ENCOMENDAS (RESERVA, CRIADO_EM DESC)
        INCLUDE (ENCOMENDA_ESTADO_ID, TOTAL, TOTAL_PAGO, TOTAL_REEMBOLSADO);

    CREATE INDEX IX_SHOP_ENCOMENDAS_ESTADO_CRIADO
        ON dbo.SHOP_ENCOMENDAS (ENCOMENDA_ESTADO_ID, CRIADO_EM DESC);

    CREATE UNIQUE INDEX UX_SHOP_ENCOMENDAS_NUMERO
        ON dbo.SHOP_ENCOMENDAS (NUMERO)
        WHERE NUMERO IS NOT NULL;

    CREATE UNIQUE INDEX UX_SHOP_ENCOMENDAS_CARRINHO
        ON dbo.SHOP_ENCOMENDAS (CARRINHO_ID)
        WHERE CARRINHO_ID IS NOT NULL;

    CREATE INDEX IX_SHOP_ENCOMENDA_LINHAS_ENCOMENDA
        ON dbo.SHOP_ENCOMENDA_LINHAS (ENCOMENDA_ID, NUMERO_LINHA)
        INCLUDE (PRODUTO_ID, PRODUTO_VARIANTE_ID, QUANTIDADE, PRECO_UNITARIO, SUBTOTAL, TOTAL);

    CREATE INDEX IX_SHOP_ENCOMENDA_LINHAS_PRODUTO
        ON dbo.SHOP_ENCOMENDA_LINHAS (PRODUTO_ID, PRODUTO_VARIANTE_ID);

    CREATE INDEX IX_SHOP_PAGAMENTOS_ENCOMENDA_ESTADO
        ON dbo.SHOP_PAGAMENTOS (ENCOMENDA_ID, ESTADO, CRIADO_EM DESC)
        INCLUDE (VALOR, VALOR_CAPTURADO, VALOR_REEMBOLSADO, PAGO_EM);

    CREATE UNIQUE INDEX UX_SHOP_PAGAMENTOS_REFERENCIA_EXTERNA
        ON dbo.SHOP_PAGAMENTOS (REFERENCIA_EXTERNA)
        WHERE REFERENCIA_EXTERNA IS NOT NULL;

    CREATE INDEX IX_SHOP_TRANSACOES_STRIPE_PAGAMENTO_CRIADO
        ON dbo.SHOP_TRANSACOES_STRIPE (PAGAMENTO_ID, CRIADO_EM DESC)
        INCLUDE (TIPO_TRANSACAO, EVENT_TYPE, EXTERNAL_STATUS, VALOR, MOEDA);

    CREATE UNIQUE INDEX UX_SHOP_TRANSACOES_STRIPE_EVENT_ID
        ON dbo.SHOP_TRANSACOES_STRIPE (EVENT_ID)
        WHERE EVENT_ID IS NOT NULL;

    CREATE INDEX IX_SHOP_TRANSACOES_STRIPE_PAYMENT_INTENT_ID
        ON dbo.SHOP_TRANSACOES_STRIPE (PAYMENT_INTENT_ID)
        WHERE PAYMENT_INTENT_ID IS NOT NULL;

    CREATE INDEX IX_SHOP_TRANSACOES_STRIPE_CHECKOUT_SESSION_ID
        ON dbo.SHOP_TRANSACOES_STRIPE (CHECKOUT_SESSION_ID)
        WHERE CHECKOUT_SESSION_ID IS NOT NULL;

    CREATE INDEX IX_SHOP_TRANSACOES_STRIPE_CHARGE_ID
        ON dbo.SHOP_TRANSACOES_STRIPE (CHARGE_ID)
        WHERE CHARGE_ID IS NOT NULL;

    CREATE INDEX IX_SHOP_TRANSACOES_STRIPE_REFUND_ID
        ON dbo.SHOP_TRANSACOES_STRIPE (REFUND_ID)
        WHERE REFUND_ID IS NOT NULL;

    CREATE INDEX IX_SHOP_REEMBOLSOS_PAGAMENTO_ESTADO
        ON dbo.SHOP_REEMBOLSOS (PAGAMENTO_ID, ESTADO, CRIADO_EM DESC)
        INCLUDE (VALOR, PROCESSADO_EM);

    CREATE UNIQUE INDEX UX_SHOP_REEMBOLSOS_REFUND_ID_EXTERNO
        ON dbo.SHOP_REEMBOLSOS (REFUND_ID_EXTERNO)
        WHERE REFUND_ID_EXTERNO IS NOT NULL;

    CREATE INDEX IX_SHOP_STOCK_MOVIMENTOS_PRODUTO_DATA
        ON dbo.SHOP_STOCK_MOVIMENTOS (PRODUTO_ID, PRODUTO_VARIANTE_ID, CRIADO_EM DESC)
        INCLUDE (TIPO_MOVIMENTO, QUANTIDADE, ORIGEM, ENCOMENDA_LINHA_ID);

    CREATE INDEX IX_SHOP_STOCK_MOVIMENTOS_ENCOMENDA_LINHA
        ON dbo.SHOP_STOCK_MOVIMENTOS (ENCOMENDA_LINHA_ID)
        WHERE ENCOMENDA_LINHA_ID IS NOT NULL;

    CREATE INDEX IX_SHOP_LOGS_CRIADO
        ON dbo.SHOP_LOGS (CRIADO_EM DESC)
        INCLUDE (NIVEL, CATEGORIA, EVENTO, RESERVA, ENCOMENDA_ID, PAGAMENTO_ID);

    CREATE INDEX IX_SHOP_LOGS_RESERVA
        ON dbo.SHOP_LOGS (RESERVA, CRIADO_EM DESC)
        WHERE RESERVA IS NOT NULL;

    CREATE INDEX IX_SHOP_LOGS_ENCOMENDA
        ON dbo.SHOP_LOGS (ENCOMENDA_ID, CRIADO_EM DESC)
        WHERE ENCOMENDA_ID IS NOT NULL;

    CREATE INDEX IX_SHOP_LOGS_PAGAMENTO
        ON dbo.SHOP_LOGS (PAGAMENTO_ID, CRIADO_EM DESC)
        WHERE PAGAMENTO_ID IS NOT NULL;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    THROW;
END CATCH;
