SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'TABIVA') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD TABIVA INT NULL;

    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'TAXAIVA') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD TAXAIVA NUMERIC(6,2) NULL;

    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'PCUSTO') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD PCUSTO NUMERIC(12,2) NOT NULL
            CONSTRAINT DF_SHOP_PRODUTOS_PCUSTO DEFAULT (0);

    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'FLNO') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD FLNO INT NULL;

    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'FLNOME') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD FLNOME NVARCHAR(55) NULL;

    IF NOT EXISTS (
        SELECT 1
        FROM sys.check_constraints
        WHERE name = 'CK_SHOP_PRODUTOS_TABIVA'
    )
    BEGIN
        ALTER TABLE dbo.SHOP_PRODUTOS
            ADD CONSTRAINT CK_SHOP_PRODUTOS_TABIVA
            CHECK (TABIVA IS NULL OR TABIVA >= 0);
    END;

    IF NOT EXISTS (
        SELECT 1
        FROM sys.check_constraints
        WHERE name = 'CK_SHOP_PRODUTOS_TAXAIVA'
    )
    BEGIN
        ALTER TABLE dbo.SHOP_PRODUTOS
            ADD CONSTRAINT CK_SHOP_PRODUTOS_TAXAIVA
            CHECK (TAXAIVA IS NULL OR TAXAIVA >= 0);
    END;

    IF NOT EXISTS (
        SELECT 1
        FROM sys.check_constraints
        WHERE name = 'CK_SHOP_PRODUTOS_PCUSTO'
    )
    BEGIN
        ALTER TABLE dbo.SHOP_PRODUTOS
            ADD CONSTRAINT CK_SHOP_PRODUTOS_PCUSTO
            CHECK (PCUSTO >= 0);
    END;

    IF OBJECT_ID('dbo.V_TAXASIVA', 'V') IS NOT NULL
    BEGIN
        UPDATE P
           SET P.TAXAIVA = TRY_CONVERT(NUMERIC(6,2), V.TAXAIVA)
          FROM dbo.SHOP_PRODUTOS AS P
          INNER JOIN dbo.V_TAXASIVA AS V
                  ON V.TABIVA = P.TABIVA
         WHERE P.TABIVA IS NOT NULL
           AND (
                P.TAXAIVA IS NULL
                OR P.TAXAIVA <> TRY_CONVERT(NUMERIC(6,2), V.TAXAIVA)
           );
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    THROW;
END CATCH;
