SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'NOME_EN') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD NOME_EN NVARCHAR(150) NULL;
    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'NOME_ES') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD NOME_ES NVARCHAR(150) NULL;
    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'NOME_FR') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD NOME_FR NVARCHAR(150) NULL;

    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'TITULO_EN') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD TITULO_EN NVARCHAR(200) NULL;
    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'TITULO_ES') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD TITULO_ES NVARCHAR(200) NULL;
    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'TITULO_FR') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD TITULO_FR NVARCHAR(200) NULL;

    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'SUBTITULO_EN') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD SUBTITULO_EN NVARCHAR(200) NULL;
    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'SUBTITULO_ES') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD SUBTITULO_ES NVARCHAR(200) NULL;
    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'SUBTITULO_FR') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD SUBTITULO_FR NVARCHAR(200) NULL;

    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'DESCRICAO_CURTA_EN') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD DESCRICAO_CURTA_EN NVARCHAR(500) NULL;
    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'DESCRICAO_CURTA_ES') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD DESCRICAO_CURTA_ES NVARCHAR(500) NULL;
    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'DESCRICAO_CURTA_FR') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD DESCRICAO_CURTA_FR NVARCHAR(500) NULL;

    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'DESCRICAO_EN') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD DESCRICAO_EN NVARCHAR(MAX) NULL;
    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'DESCRICAO_ES') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD DESCRICAO_ES NVARCHAR(MAX) NULL;
    IF COL_LENGTH('dbo.SHOP_PRODUTOS', 'DESCRICAO_FR') IS NULL
        ALTER TABLE dbo.SHOP_PRODUTOS ADD DESCRICAO_FR NVARCHAR(MAX) NULL;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    THROW;
END CATCH;
