SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF COL_LENGTH('dbo.SHOP_ENCOMENDAS', 'ENTREGA_TIPO') IS NULL
        ALTER TABLE dbo.SHOP_ENCOMENDAS ADD ENTREGA_TIPO NVARCHAR(20) NULL;

    IF COL_LENGTH('dbo.SHOP_ENCOMENDAS', 'ENTREGA_NOME') IS NULL
        ALTER TABLE dbo.SHOP_ENCOMENDAS ADD ENTREGA_NOME NVARCHAR(100) NULL;

    IF COL_LENGTH('dbo.SHOP_ENCOMENDAS', 'ENTREGA_VALOR') IS NULL
        ALTER TABLE dbo.SHOP_ENCOMENDAS ADD ENTREGA_VALOR DECIMAL(19,4) NOT NULL CONSTRAINT DF_SHOP_ENCOMENDAS_ENTREGA_VALOR DEFAULT (0);

    IF COL_LENGTH('dbo.SHOP_ENCOMENDAS', 'ENTREGA_PREVISTA') IS NULL
        ALTER TABLE dbo.SHOP_ENCOMENDAS ADD ENTREGA_PREVISTA NVARCHAR(200) NULL;

    IF COL_LENGTH('dbo.SHOP_ENCOMENDAS', 'ENTREGA_REQUER_PRESENCA') IS NULL
        ALTER TABLE dbo.SHOP_ENCOMENDAS ADD ENTREGA_REQUER_PRESENCA BIT NOT NULL CONSTRAINT DF_SHOP_ENCOMENDAS_ENTREGA_REQUER_PRESENCA DEFAULT (0);

    IF NOT EXISTS (
        SELECT 1
        FROM sys.check_constraints
        WHERE name = 'CK_SHOP_ENCOMENDAS_ENTREGA_TIPO'
    )
        ALTER TABLE dbo.SHOP_ENCOMENDAS
            ADD CONSTRAINT CK_SHOP_ENCOMENDAS_ENTREGA_TIPO
                CHECK (ENTREGA_TIPO IS NULL OR ENTREGA_TIPO IN (N'FREE', N'EXPRESS'));

    IF NOT EXISTS (
        SELECT 1
        FROM sys.check_constraints
        WHERE name = 'CK_SHOP_ENCOMENDAS_ENTREGA_VALOR'
    )
        ALTER TABLE dbo.SHOP_ENCOMENDAS
            ADD CONSTRAINT CK_SHOP_ENCOMENDAS_ENTREGA_VALOR
                CHECK (ENTREGA_VALOR >= 0);

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    THROW;
END CATCH;
