/*
  TP038 - Processamento de despesas
  Compatível com instalações existentes: os campos antigos da primeira linha
  continuam em COLAB_DESPESA_LINHA e são sincronizados pelo serviço.
*/
IF COL_LENGTH('dbo.COLAB_DESPESA_LINHA', 'VERSION') IS NULL
    ALTER TABLE dbo.COLAB_DESPESA_LINHA ADD VERSION int NOT NULL CONSTRAINT DF_COLAB_DESPESA_LINHA_VERSION DEFAULT 1;
IF COL_LENGTH('dbo.COLAB_DESPESA_LINHA', 'MOEDA') IS NULL
    ALTER TABLE dbo.COLAB_DESPESA_LINHA ADD MOEDA varchar(10) NOT NULL CONSTRAINT DF_COLAB_DESPESA_LINHA_MOEDA DEFAULT 'EUR';
IF COL_LENGTH('dbo.COLAB_DESPESA_LINHA', 'REFERENCIA_DOCUMENTO') IS NULL
    ALTER TABLE dbo.COLAB_DESPESA_LINHA ADD REFERENCIA_DOCUMENTO nvarchar(160) NOT NULL CONSTRAINT DF_COLAB_DESPESA_LINHA_REFERENCIA_DOCUMENTO DEFAULT N'';
IF COL_LENGTH('dbo.COLAB_DESPESA_LINHA', 'CAMPO_ORIGEM_JSON') IS NULL
    ALTER TABLE dbo.COLAB_DESPESA_LINHA ADD CAMPO_ORIGEM_JSON nvarchar(max) NOT NULL CONSTRAINT DF_COLAB_DESPESA_LINHA_CAMPO_ORIGEM DEFAULT N'{}';
IF COL_LENGTH('dbo.COLAB_DESPESA_LINHA', 'ARQUIVO_ESTADO') IS NULL
    ALTER TABLE dbo.COLAB_DESPESA_LINHA ADD ARQUIVO_ESTADO varchar(20) NOT NULL CONSTRAINT DF_COLAB_DESPESA_LINHA_ARQUIVO_ESTADO DEFAULT '';
IF COL_LENGTH('dbo.COLAB_DESPESA_LINHA', 'ARQUIVO_DATA') IS NULL
    ALTER TABLE dbo.COLAB_DESPESA_LINHA ADD ARQUIVO_DATA datetime NULL;
IF COL_LENGTH('dbo.COLAB_DESPESA_LINHA', 'ARQUIVO_POR') IS NULL
    ALTER TABLE dbo.COLAB_DESPESA_LINHA ADD ARQUIVO_POR varchar(60) NOT NULL CONSTRAINT DF_COLAB_DESPESA_LINHA_ARQUIVO_POR DEFAULT '';
IF COL_LENGTH('dbo.COLAB_DESPESA_LINHA', 'PHC_OBRANO') IS NULL
    ALTER TABLE dbo.COLAB_DESPESA_LINHA ADD PHC_OBRANO int NOT NULL CONSTRAINT DF_COLAB_DESPESA_LINHA_PHC_OBRANO DEFAULT 0;
IF COL_LENGTH('dbo.COLAB_DESPESA_LINHA', 'PHC_NMDOS') IS NULL
    ALTER TABLE dbo.COLAB_DESPESA_LINHA ADD PHC_NMDOS varchar(80) NOT NULL CONSTRAINT DF_COLAB_DESPESA_LINHA_PHC_NMDOS DEFAULT '';

IF OBJECT_ID('dbo.COLAB_DESPESA_CONTAB_LINHA', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.COLAB_DESPESA_CONTAB_LINHA (
        DESPCONTABSTAMP varchar(25) NOT NULL PRIMARY KEY,
        DESPLINHASTAMP varchar(25) NOT NULL,
        ORDEM int NOT NULL DEFAULT 10,
        ARTIGO_REF varchar(50) NOT NULL DEFAULT '',
        DESIGN nvarchar(200) NOT NULL DEFAULT N'',
        REFERENCIA nvarchar(160) NOT NULL DEFAULT N'',
        CCUSTO varchar(80) NOT NULL DEFAULT '',
        MATRICULA varchar(50) NOT NULL DEFAULT '',
        TABIVA int NOT NULL DEFAULT 0,
        TAXAIVA decimal(9,4) NOT NULL DEFAULT 0,
        TOTAL_SEM_IVA decimal(18,2) NOT NULL DEFAULT 0,
        VALOR_IVA decimal(18,2) NOT NULL DEFAULT 0,
        TOTAL_COM_IVA decimal(18,2) NOT NULL DEFAULT 0,
        CAMPO_ORIGEM_JSON nvarchar(max) NOT NULL DEFAULT N'{}',
        DTCRI datetime NOT NULL DEFAULT GETDATE(),
        DTALT datetime NULL,
        USERCRIACAO varchar(60) NOT NULL DEFAULT '',
        USERALTERACAO varchar(60) NOT NULL DEFAULT '',
        FOREIGN KEY (DESPLINHASTAMP) REFERENCES dbo.COLAB_DESPESA_LINHA (DESPLINHASTAMP)
    );
    CREATE INDEX IX_COLAB_DESPESA_CONTAB_DESPESA ON dbo.COLAB_DESPESA_CONTAB_LINHA (DESPLINHASTAMP, ORDEM, DTCRI);
END;

IF OBJECT_ID('dbo.COLAB_DESPESA_HIST', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.COLAB_DESPESA_HIST (
        DESPHISTSTAMP varchar(25) NOT NULL PRIMARY KEY,
        DESPLINHASTAMP varchar(25) NOT NULL,
        ACAO varchar(30) NOT NULL DEFAULT '',
        DETALHE_JSON nvarchar(max) NOT NULL DEFAULT N'{}',
        UTILIZADOR varchar(60) NOT NULL DEFAULT '',
        DTCRI datetime NOT NULL DEFAULT GETDATE()
    );
END;

IF OBJECT_ID('dbo.COLAB_DESPESA_LANCAMENTO', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.COLAB_DESPESA_LANCAMENTO (
        LANCAMENTO_CHAVE varchar(64) NOT NULL PRIMARY KEY,
        ESTADO varchar(20) NOT NULL DEFAULT 'EM_CURSO',
        PHC_DB varchar(128) NOT NULL DEFAULT '',
        PHC_BOSTAMP varchar(25) NOT NULL DEFAULT '',
        PHC_OBRANO int NOT NULL DEFAULT 0,
        PHC_NMDOS varchar(80) NOT NULL DEFAULT '',
        UTILIZADOR varchar(60) NOT NULL DEFAULT '',
        DTCRI datetime NOT NULL DEFAULT GETDATE(),
        DTALT datetime NULL
    );
END;
