SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
    Migração defensiva para autenticação híbrida em dbo.US.
    Objetivo:
      - adicionar colunas novas sem tocar na password legacy;
      - manter compatibilidade total com produção/local durante a transição;
      - permitir migração progressiva no login.
*/

IF COL_LENGTH('dbo.US', 'PASSWORD_HASH') IS NULL
BEGIN
    ALTER TABLE dbo.US ADD PASSWORD_HASH NVARCHAR(512) NULL;
END
GO

IF COL_LENGTH('dbo.US', 'PASSWORD_ALGO') IS NULL
BEGIN
    ALTER TABLE dbo.US ADD PASSWORD_ALGO NVARCHAR(50) NULL;
END
GO

IF COL_LENGTH('dbo.US', 'PASSWORD_MIGRADA') IS NULL
BEGIN
    ALTER TABLE dbo.US
    ADD PASSWORD_MIGRADA BIT NOT NULL
        CONSTRAINT DF_US_PASSWORD_MIGRADA DEFAULT (0);
END
GO

IF COL_LENGTH('dbo.US', 'PASSWORD_CHANGED_AT') IS NULL
BEGIN
    ALTER TABLE dbo.US ADD PASSWORD_CHANGED_AT DATETIME2(0) NULL;
END
GO

IF COL_LENGTH('dbo.US', 'PASSWORD_RESET_REQUIRED') IS NULL
BEGIN
    ALTER TABLE dbo.US
    ADD PASSWORD_RESET_REQUIRED BIT NOT NULL
        CONSTRAINT DF_US_PASSWORD_RESET_REQUIRED DEFAULT (0);
END
GO

IF COL_LENGTH('dbo.US', 'FAILED_LOGIN_COUNT') IS NULL
BEGIN
    ALTER TABLE dbo.US
    ADD FAILED_LOGIN_COUNT INT NOT NULL
        CONSTRAINT DF_US_FAILED_LOGIN_COUNT DEFAULT (0);
END
GO

IF COL_LENGTH('dbo.US', 'LOCKED_UNTIL') IS NULL
BEGIN
    ALTER TABLE dbo.US ADD LOCKED_UNTIL DATETIME2(0) NULL;
END
GO

IF COL_LENGTH('dbo.US', 'LAST_LOGIN_AT') IS NULL
BEGIN
    ALTER TABLE dbo.US ADD LAST_LOGIN_AT DATETIME2(0) NULL;
END
GO

IF COL_LENGTH('dbo.US', 'IS_ACTIVE') IS NULL
BEGIN
    ALTER TABLE dbo.US
    ADD IS_ACTIVE BIT NOT NULL
        CONSTRAINT DF_US_IS_ACTIVE DEFAULT (1);
END
GO

/*
    Retrocompatibilidade:
    - se existir coluna legacy INATIVO, alinhar IS_ACTIVE sem alterar mais nada;
    - se houver hashes já presentes, refletir PASSWORD_MIGRADA.
*/
IF COL_LENGTH('dbo.US', 'INATIVO') IS NOT NULL
BEGIN
    UPDATE dbo.US
       SET IS_ACTIVE = CASE WHEN ISNULL(INATIVO, 0) = 1 THEN 0 ELSE 1 END
     WHERE IS_ACTIVE <> CASE WHEN ISNULL(INATIVO, 0) = 1 THEN 0 ELSE 1 END;
END
GO

UPDATE dbo.US
   SET PASSWORD_MIGRADA = CASE WHEN NULLIF(LTRIM(RTRIM(ISNULL(PASSWORD_HASH, ''))), '') IS NULL THEN 0 ELSE 1 END
 WHERE PASSWORD_MIGRADA <> CASE WHEN NULLIF(LTRIM(RTRIM(ISNULL(PASSWORD_HASH, ''))), '') IS NULL THEN 0 ELSE 1 END;
GO

/*
    Índices leves para autenticação:
    - LOGIN para lookup rápido;
    - LOCKED_UNTIL para auditoria/diagnóstico.
*/
IF NOT EXISTS (
    SELECT 1
      FROM sys.indexes
     WHERE name = 'IX_US_LOGIN_AUTH'
       AND object_id = OBJECT_ID('dbo.US')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_US_LOGIN_AUTH
        ON dbo.US (LOGIN)
        INCLUDE (USSTAMP, PASSWORD, PASSWORD_HASH, PASSWORD_ALGO, PASSWORD_MIGRADA, FAILED_LOGIN_COUNT, LOCKED_UNTIL, LAST_LOGIN_AT, IS_ACTIVE);
END
GO

IF NOT EXISTS (
    SELECT 1
      FROM sys.indexes
     WHERE name = 'IX_US_LOCKED_UNTIL'
       AND object_id = OBJECT_ID('dbo.US')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_US_LOCKED_UNTIL
        ON dbo.US (LOCKED_UNTIL);
END
GO
