SET XACT_ABORT ON;

BEGIN TRANSACTION;

-- Valores confirmados no certificado de matrícula.
UPDATE dbo.VA
SET CILINDRADA = 2998,
    COMBUSTIVEL = 'GASOLEO',
    DTMATRICULA = CONVERT(date, '20200103', 112),
    VERSAO = 'IS35CI2AA',
    POTENCIAKW = 155,
    PESOBRUTO = 3500,
    NRLUGARES = 7,
    CATEGORIA = 'LIGEIRO/MERCADORIAS',
    CARROCARIA = 'FECHADA',
    COR = 'BRANCO E OUTRAS',
    NORMAEURO = 'EURO VI D'
WHERE MATRICULA = '77-ZR-45'
  AND ISNULL(INATIVO, 0) = 0;

-- O VIN no registo tinha a letra I no lugar do algarismo 1.
UPDATE dbo.VA
SET CILINDRADA = 1950,
    COMBUSTIVEL = 'GASOLEO',
    DTMATRICULA = CONVERT(date, '20210105', 112),
    VERSAO = 'HZAA150B',
    POTENCIAKW = 85,
    PESOBRUTO = 1995,
    NRLUGARES = 5,
    CATEGORIA = 'LIGEIRO/PASSAGEIROS',
    CARROCARIA = 'FECHADA C/ TECTO ABRIR',
    COR = 'CINZENTO E OUTRAS',
    CHASSIS = CASE
        WHEN LTRIM(RTRIM(ISNULL(CHASSIS, ''))) IN ('', 'WIK1770101V091622')
            THEN 'W1K1770101V091622'
        ELSE CHASSIS
    END
WHERE MATRICULA = 'AE-67-UP'
  AND ISNULL(INATIVO, 0) = 0;

-- O documento confirma também a anterior matrícula lituana.
UPDATE dbo.VA
SET CILINDRADA = 999,
    COMBUSTIVEL = 'GASOLINA/GPL',
    DTMATRICULA = CONVERT(date, '20221111', 112),
    VERSAO = 'MT6U8390M0EG',
    POTENCIAKW = 67,
    PESOBRUTO = 1773,
    NRLUGARES = 5,
    CATEGORIA = 'LIGEIRO/PASSAGEIROS',
    CARROCARIA = 'FECHADA C/ TECTO ABRIR',
    COR = 'BRANCO E OUTRAS',
    MATRICULAANTERIOR = 'MJD209',
    PAISPROCEDENCIA = 'LITUANIA',
    DATAMAT = CASE
        WHEN DATAMAT IS NULL OR CONVERT(date, DATAMAT) = CONVERT(date, '20220201', 112)
            THEN CONVERT(date, '20221111', 112)
        ELSE DATAMAT
    END
WHERE MATRICULA = 'AX-57-XP'
  AND ISNULL(INATIVO, 0) = 0;

-- Valores confirmados na DAV e no certificado de matrícula.
UPDATE dbo.VA
SET CILINDRADA = 1598,
    COMBUSTIVEL = 'GASOLEO',
    DTMATRICULA = CONVERT(date, '20150312', 112),
    VERSAO = '2FL11E',
    PESOBRUTO = 2940,
    TARA = 2041,
    NRLUGARES = 6,
    CATEGORIA = 'LIGEIRO/MERCADORIAS',
    CARROCARIA = 'FECH.C/S TECTO ABRIR',
    COR = 'BRANCO E OUTRAS',
    CO2_GKM = 160,
    MATRICULAANTERIOR = 'DP145TF',
    PAISPROCEDENCIA = 'FRANCA',
    DTAQUISICAO = CONVERT(date, '20250421', 112),
    VALORAQUISICAO = 10000,
    MOTOR = CASE
        WHEN LTRIM(RTRIM(ISNULL(MOTOR, ''))) IN ('', 'VF12FL11E52533552')
            THEN 'R9MD4C032672'
        ELSE MOTOR
    END
WHERE MATRICULA = 'BX-72-CL'
  AND ISNULL(INATIVO, 0) = 0;

-- Valores expressos no controlo técnico francês.
UPDATE dbo.VA
SET COMBUSTIVEL = 'GASOLEO',
    DTMATRICULA = CONVERT(date, '20080528', 112),
    CATEGORIA = 'N3G',
    CARROCARIA = 'CAM/BETON'
WHERE MATRICULA = 'CN-108-TZ'
  AND ISNULL(INATIVO, 0) = 0;

-- Semirreboque: cilindrada, combustível, potência e lugares não se aplicam.
UPDATE dbo.VA
SET DTMATRICULA = CONVERT(date, '20061025', 112),
    VERSAO = 'TX34CW1EAK1A',
    PESOBRUTO = 38000,
    TARA = 7040,
    CATEGORIA = 'SREM',
    CARROCARIA = 'PLSC'
WHERE MATRICULA = 'CN-996-GM'
  AND ISNULL(INATIVO, 0) = 0;

-- Valores confirmados no certificat d'immatriculation.
UPDATE dbo.VA
SET CILINDRADA = 2143,
    COMBUSTIVEL = 'GASOLEO',
    DTMATRICULA = CONVERT(date, '20150711', 112),
    VERSAO = '639/4MXA7L280V2SMM1S25XX',
    POTENCIAKW = 100,
    PESOBRUTO = 2800,
    TARA = 1967,
    NRLUGARES = 5,
    CATEGORIA = 'N1',
    CARROCARIA = 'FOURGON',
    CO2_GKM = 173,
    NORMAEURO = 'EURO 5'
WHERE MATRICULA = 'FY-283-XZ'
  AND ISNULL(INATIVO, 0) = 0;

UPDATE dbo.VA
SET CILINDRADA = 1499,
    COMBUSTIVEL = 'GASOLEO',
    DTMATRICULA = CONVERT(date, '20211015', 112),
    VERSAO = 'UBYHTK-J2B400',
    POTENCIAKW = 75,
    PESOBRUTO = 1650,
    TARA = 1090,
    NRLUGARES = 2,
    CATEGORIA = 'M1',
    CARROCARIA = 'DERIV VP',
    CO2_GKM = 106,
    NORMAEURO = 'EURO 6'
WHERE MATRICULA = 'GC-914-KK'
  AND ISNULL(INATIVO, 0) = 0;

-- Certificado alemão e fatura de aquisição.
UPDATE dbo.VA
SET CILINDRADA = 2967,
    COMBUSTIVEL = 'GASOLEO',
    DTMATRICULA = CONVERT(date, '20200618', 112),
    VERSAO = 'A2DCPEQ1',
    POTENCIAKW = 170,
    PESOBRUTO = 2320,
    TARA = 1842,
    NRLUGARES = 5,
    CATEGORIA = 'M1',
    COR = 'PRETO METALIZADO',
    CO2_GKM = 191,
    NORMAEURO = 'EURO 6',
    DTAQUISICAO = CONVERT(date, '20210406', 112),
    VALORAQUISICAO = 47900,
    CILIND = CASE
        WHEN ISNULL(CILIND, 0) IN (0, 1996) THEN 2967
        ELSE CILIND
    END
WHERE MATRICULA = 'OG HS 292'
  AND ISNULL(INATIVO, 0) = 0;

COMMIT TRANSACTION;
