from pathlib import Path
path = Path('templates/index.html')
text = path.read_text()
old = "        {% for day_state in row.days %}\n                                            <td class=\"day-cell {{ 'active' if day_state.active else '' }}\">\n                                                {% if day_state.assignments %}\n                                                    <div class=\"day-assignments\">\n                                                        {% for assignment in day_state.assignments %}\n                                                            {% set chip_label = (assignment.name or assignment.code or \"\") %}\n                                                            <span class=\"assignment-chip\" title=\"{{ chip_label }}\" data-tooltip=\"{{ chip_label }}\" tabindex=\"0\">{{ assignment.code }}</span>\n                                                        {% endfor %}\n                                                    </div>\n                                                {% endif %}\n                                            </td>\n                                        {% endfor %}\n"
new = "        {% for day_state in row.days %}\n                                            <td\n                                                class=\"day-cell {{ 'active' if day_state.active else '' }}\"\n                                                data-project-code=\"{{ row.code }}\"\n                                                data-project-name=\"{{ (row.name or '')|e }}\"\n                                                data-date=\"{{ day_state.date.isoformat() }}\"\n                                                data-date-label=\"{{ day_state.date.strftime('%d/%m/%Y') }}\"\n                                                data-weekday-label=\"{{ day_labels[loop.index0] }}\"\n                                                data-assignments='{{ day_state.assignments | tojson | safe }}'\n                                                tabindex=\"0\"\n                                                role=\"button\"\n                                                aria-label=\"{{ (row.code ~ ' - ' if row.code else '') ~ (row.name or '') ~ ' - ' ~ day_labels[loop.index0] ~ ' ' ~ day_state.date.strftime('%d/%m') }}\"\n                                            >\n                                                {% if day_state.assignments %}\n                                                    <div class=\"day-assignments\">\n                                                        {% for assignment in day_state.assignments %}\n                                                            {% set chip_label = (assignment.name or assignment.code or \"\") %}\n                                                            <span class=\"assignment-chip\" title=\"{{ chip_label }}\" data-tooltip=\"{{ chip_label }}\" tabindex=\"0\">{{ assignment.code or assignment.name }}</span>\n                                                        {% endfor %}\n                                                    </div>\n                                                {% endif %}\n                                            </td>\n                                        {% endfor %}\n"
if old in text:
    text = text.replace(old, new, 1)
    path.write_text(text)
else:
    raise SystemExit('target block not found')
