"""Public copy for the catalog's list/map switch and booking preview."""

MAP_COPY = {
    "pt": {
        "view_map": "Ver no mapa", "view_list": "Ver lista",
        "title": "Encontre a sua estadia no mapa",
        "legend_available": "Disponíveis para a pesquisa",
        "legend_unavailable": "Não correspondem à pesquisa",
        "legend_all": "Alojamentos", "approximate": "Localizações aproximadas. A morada exata é indicada após a confirmação da reserva.",
        "loading": "A carregar alojamentos…", "error": "Não foi possível carregar os alojamentos no mapa.",
        "retry": "Tentar novamente", "empty": "Não existem alojamentos com localização disponível.",
        "no_matches": "Nenhum alojamento no mapa corresponde à pesquisa. Experimente outras datas ou hóspedes.",
        "missing_coordinates": "{count} alojamento(s) sem localização no mapa. Pode encontrá-los na lista.",
        "group_count": "{count} alojamentos nesta zona", "close": "Fechar",
        "view_stay": "Ver alojamento", "book": "Reservar", "choose_dates": "Escolha as datas e os hóspedes para simular a sua reserva.",
        "simulation": "Simulação da reserva", "total": "Total da estadia",
        "airbnb_price": "Preço Airbnb", "direct_booking": "Reserva direta", "you_save": "Poupa {value}",
        "saving_info_open": "Saber porque poupa na reserva direta",
        "unavailable": "Indisponível para as datas selecionadas.", "loading_quote": "A calcular a sua estadia…",
        "quote_error": "Não foi possível obter a simulação. Tente novamente ou abra o alojamento.",
        "from_price": "desde", "per_night": "por noite", "no_price": "Preço sob consulta",
        "match_count": "{count} de {total} alojamentos no mapa correspondem à pesquisa",
        "all_stays": "{count} alojamentos no mapa", "tile_error": "Não foi possível carregar parte do mapa. Verifique a ligação e tente novamente.",
        "guests": "Hóspedes", "nights": "noites", "checkin": "Check-in", "checkout": "Check-out",
        "back_to_group": "Ver alojamentos nesta zona", "estimate": "Disponibilidade e preço sujeitos a confirmação ao reservar.",
        "invalid_search": "Corrija os campos da pesquisa para verificar a disponibilidade.",
    },
    "en": {
        "view_map": "View map", "view_list": "View list",
        "title": "Find your stay on the map",
        "legend_available": "Available for your search", "legend_unavailable": "Do not match your search",
        "legend_all": "Properties", "approximate": "Approximate locations. The exact address is provided after your booking is confirmed.",
        "loading": "Loading properties…", "error": "The properties could not be loaded on the map.",
        "retry": "Try again", "empty": "No properties have a location available.",
        "no_matches": "No properties on the map match your search. Try different dates or guests.",
        "missing_coordinates": "{count} property/properties have no map location. You can find them in the list.",
        "group_count": "{count} properties in this area", "close": "Close",
        "view_stay": "View property", "book": "Book", "choose_dates": "Choose your dates and guests to preview your booking.",
        "simulation": "Booking preview", "total": "Stay total",
        "airbnb_price": "Airbnb price", "direct_booking": "Direct booking", "you_save": "You save {value}",
        "saving_info_open": "Learn why you save by booking direct",
        "unavailable": "Unavailable for the selected dates.", "loading_quote": "Calculating your stay…",
        "quote_error": "The booking preview could not be loaded. Try again or open the property.",
        "from_price": "from", "per_night": "per night", "no_price": "Price on request",
        "match_count": "{count} of {total} properties on the map match your search",
        "all_stays": "{count} properties on the map", "tile_error": "Part of the map could not be loaded. Check your connection and try again.",
        "guests": "Guests", "nights": "nights", "checkin": "Check-in", "checkout": "Check-out",
        "back_to_group": "View properties in this area", "estimate": "Availability and price are reconfirmed when booking.",
        "invalid_search": "Correct the search fields to check availability.",
    },
    "es": {
        "view_map": "Ver en el mapa", "view_list": "Ver lista",
        "title": "Encuentre su estancia en el mapa",
        "legend_available": "Disponibles para su búsqueda", "legend_unavailable": "No coinciden con su búsqueda",
        "legend_all": "Alojamientos", "approximate": "Ubicaciones aproximadas. La dirección exacta se facilita tras confirmar la reserva.",
        "loading": "Cargando alojamientos…", "error": "No se han podido cargar los alojamientos en el mapa.",
        "retry": "Volver a intentar", "empty": "No hay alojamientos con ubicación disponible.",
        "no_matches": "Ningún alojamiento en el mapa coincide con su búsqueda. Pruebe otras fechas o huéspedes.",
        "missing_coordinates": "{count} alojamiento(s) sin ubicación en el mapa. Puede encontrarlos en la lista.",
        "group_count": "{count} alojamientos en esta zona", "close": "Cerrar",
        "view_stay": "Ver alojamiento", "book": "Reservar", "choose_dates": "Elija las fechas y los huéspedes para calcular su reserva.",
        "simulation": "Simulación de la reserva", "total": "Total de la estancia",
        "airbnb_price": "Precio en Airbnb", "direct_booking": "Reserva directa", "you_save": "Ahorras {value}",
        "saving_info_open": "Descubre por qué ahorras al reservar directamente",
        "unavailable": "No disponible para las fechas seleccionadas.", "loading_quote": "Calculando su estancia…",
        "quote_error": "No se ha podido obtener la simulación. Vuelva a intentarlo o abra el alojamiento.",
        "from_price": "desde", "per_night": "por noche", "no_price": "Precio bajo consulta",
        "match_count": "{count} de {total} alojamientos en el mapa coinciden con su búsqueda",
        "all_stays": "{count} alojamientos en el mapa", "tile_error": "No se ha podido cargar parte del mapa. Compruebe la conexión y vuelva a intentarlo.",
        "guests": "Huéspedes", "nights": "noches", "checkin": "Entrada", "checkout": "Salida",
        "back_to_group": "Ver alojamientos en esta zona", "estimate": "La disponibilidad y el precio se confirman al reservar.",
        "invalid_search": "Corrija los campos de búsqueda para comprobar la disponibilidad.",
    },
    "fr": {
        "view_map": "Voir sur la carte", "view_list": "Voir la liste",
        "title": "Trouvez votre séjour sur la carte",
        "legend_available": "Disponibles pour votre recherche", "legend_unavailable": "Ne correspondent pas à votre recherche",
        "legend_all": "Hébergements", "approximate": "Emplacements approximatifs. L’adresse exacte est communiquée après confirmation de la réservation.",
        "loading": "Chargement des hébergements…", "error": "Impossible de charger les hébergements sur la carte.",
        "retry": "Réessayer", "empty": "Aucun hébergement ne dispose d’un emplacement sur la carte.",
        "no_matches": "Aucun hébergement sur la carte ne correspond à votre recherche. Essayez d’autres dates ou voyageurs.",
        "missing_coordinates": "{count} hébergement(s) sans emplacement sur la carte. Vous les trouverez dans la liste.",
        "group_count": "{count} hébergements dans cette zone", "close": "Fermer",
        "view_stay": "Voir l’hébergement", "book": "Réserver", "choose_dates": "Choisissez les dates et les voyageurs pour estimer votre réservation.",
        "simulation": "Simulation de réservation", "total": "Total du séjour",
        "airbnb_price": "Prix Airbnb", "direct_booking": "Réservation directe", "you_save": "Vous économisez {value}",
        "saving_info_open": "Découvrez pourquoi vous économisez en réservant directement",
        "unavailable": "Indisponible aux dates sélectionnées.", "loading_quote": "Calcul de votre séjour…",
        "quote_error": "Impossible de charger la simulation. Réessayez ou ouvrez l’hébergement.",
        "from_price": "à partir de", "per_night": "par nuit", "no_price": "Prix sur demande",
        "match_count": "{count} hébergements sur {total} sur la carte correspondent à votre recherche",
        "all_stays": "{count} hébergements sur la carte", "tile_error": "Impossible de charger une partie de la carte. Vérifiez votre connexion et réessayez.",
        "guests": "Voyageurs", "nights": "nuits", "checkin": "Arrivée", "checkout": "Départ",
        "back_to_group": "Voir les hébergements dans cette zone", "estimate": "La disponibilité et le prix sont confirmés lors de la réservation.",
        "invalid_search": "Corrigez les champs de recherche pour vérifier la disponibilité.",
    },
}


def get_map_copy(lang: str) -> dict:
    return dict(MAP_COPY.get(lang) or MAP_COPY["pt"])
