import re
import unicodedata
from typing import Any


ISO2_TO_ICAO = {
    "AF": "AFG", "AX": "ALA", "AL": "ALB", "DZ": "DZA", "AS": "ASM", "AD": "AND",
    "AO": "AGO", "AI": "AIA", "AQ": "ATA", "AG": "ATG", "AR": "ARG", "AM": "ARM",
    "AW": "ABW", "AU": "AUS", "AT": "AUT", "AZ": "AZE", "BS": "BHS", "BH": "BHR",
    "BD": "BGD", "BB": "BRB", "BY": "BLR", "BE": "BEL", "BZ": "BLZ", "BJ": "BEN",
    "BM": "BMU", "BT": "BTN", "BO": "BOL", "BQ": "BES", "BA": "BIH", "BW": "BWA",
    "BV": "BVT", "BR": "BRA", "IO": "IOT", "BN": "BRN", "BG": "BGR", "BF": "BFA",
    "BI": "BDI", "CV": "CPV", "KH": "KHM", "CM": "CMR", "CA": "CAN", "KY": "CYM",
    "CF": "CAF", "TD": "TCD", "CL": "CHL", "CN": "CHN", "CX": "CXR", "CC": "CCK",
    "CO": "COL", "KM": "COM", "CG": "COG", "CD": "COD", "CK": "COK", "CR": "CRI",
    "CI": "CIV", "HR": "HRV", "CU": "CUB", "CW": "CUW", "CY": "CYP", "CZ": "CZE",
    "DK": "DNK", "DJ": "DJI", "DM": "DMA", "DO": "DOM", "EC": "ECU", "EG": "EGY",
    "SV": "SLV", "GQ": "GNQ", "ER": "ERI", "EE": "EST", "SZ": "SWZ", "ET": "ETH",
    "FK": "FLK", "FO": "FRO", "FJ": "FJI", "FI": "FIN", "FR": "FRA", "GF": "GUF",
    "PF": "PYF", "TF": "ATF", "GA": "GAB", "GM": "GMB", "GE": "GEO", "DE": "DEU",
    "GH": "GHA", "GI": "GIB", "GR": "GRC", "GL": "GRL", "GD": "GRD", "GP": "GLP",
    "GU": "GUM", "GT": "GTM", "GG": "GGY", "GN": "GIN", "GW": "GNB", "GY": "GUY",
    "HT": "HTI", "HM": "HMD", "VA": "VAT", "HN": "HND", "HK": "HKG", "HU": "HUN",
    "IS": "ISL", "IN": "IND", "ID": "IDN", "IR": "IRN", "IQ": "IRQ", "IE": "IRL",
    "IM": "IMN", "IL": "ISR", "IT": "ITA", "JM": "JAM", "JP": "JPN", "JE": "JEY",
    "JO": "JOR", "KZ": "KAZ", "KE": "KEN", "KI": "KIR", "KP": "PRK", "KR": "KOR",
    "KW": "KWT", "KG": "KGZ", "LA": "LAO", "LV": "LVA", "LB": "LBN", "LS": "LSO",
    "LR": "LBR", "LY": "LBY", "LI": "LIE", "LT": "LTU", "LU": "LUX", "MO": "MAC",
    "MG": "MDG", "MW": "MWI", "MY": "MYS", "MV": "MDV", "ML": "MLI", "MT": "MLT",
    "MQ": "MTQ", "MR": "MRT", "MU": "MUS", "YT": "MYT", "MX": "MEX", "FM": "FSM",
    "MD": "MDA", "MC": "MCO", "MN": "MNG", "ME": "MNE", "MS": "MSR", "MA": "MAR",
    "MZ": "MOZ", "MM": "MMR", "NA": "NAM", "NR": "NRU", "NP": "NPL", "NL": "NLD",
    "NC": "NCL", "NZ": "NZL", "NI": "NIC", "NE": "NER", "NG": "NGA", "NU": "NIU",
    "NF": "NFK", "MK": "MKD", "MP": "MNP", "NO": "NOR", "OM": "OMN", "PK": "PAK",
    "PW": "PLW", "PS": "PSE", "PA": "PAN", "PG": "PNG", "PY": "PRY", "PE": "PER",
    "PH": "PHL", "PN": "PCN", "PL": "POL", "PT": "PRT", "PR": "PRI", "QA": "QAT",
    "RE": "REU", "RO": "ROU", "RU": "RUS", "RW": "RWA", "BL": "BLM", "SH": "SHN",
    "KN": "KNA", "LC": "LCA", "MF": "MAF", "PM": "SPM", "VC": "VCT", "WS": "WSM",
    "SM": "SMR", "ST": "STP", "SA": "SAU", "SN": "SEN", "RS": "SRB", "SC": "SYC",
    "SL": "SLE", "SG": "SGP", "SX": "SXM", "SK": "SVK", "SI": "SVN", "SB": "SLB",
    "SO": "SOM", "ZA": "ZAF", "GS": "SGS", "SS": "SSD", "ES": "ESP", "LK": "LKA",
    "SD": "SDN", "SR": "SUR", "SJ": "SJM", "SE": "SWE", "CH": "CHE", "SY": "SYR",
    "TW": "TWN", "TJ": "TJK", "TZ": "TZA", "TH": "THA", "TL": "TLS", "TG": "TGO",
    "TK": "TKL", "TO": "TON", "TT": "TTO", "TN": "TUN", "TR": "TUR", "TM": "TKM",
    "TC": "TCA", "TV": "TUV", "UG": "UGA", "UA": "UKR", "AE": "ARE", "GB": "GBR",
    "US": "USA", "UM": "UMI", "UY": "URY", "UZ": "UZB", "VU": "VUT", "VE": "VEN",
    "VN": "VNM", "VG": "VGB", "VI": "VIR", "WF": "WLF", "EH": "ESH", "YE": "YEM",
    "ZM": "ZMB", "ZW": "ZWE", "XK": "XKX",
}

ICAO_CODES = set(ISO2_TO_ICAO.values())

COUNTRY_NAME_PT_TO_ICAO = {
    "AFEGANISTAO": "AFG",
    "AFRICA DO SUL": "ZAF",
    "ALANDA": "ALA",
    "ALBANIA": "ALB",
    "ALEMANHA": "DEU",
    "ANDORRA": "AND",
    "ANGOLA": "AGO",
    "ANGUILA": "AIA",
    "ANTARTIDA": "ATA",
    "ANTIGUA E BARBUDA": "ATG",
    "ARABIA SAUDITA": "SAU",
    "ARGELIA": "DZA",
    "ARGENTINA": "ARG",
    "ARMENIA": "ARM",
    "ARUBA": "ABW",
    "AUSTRALIA": "AUS",
    "AUSTRIA": "AUT",
    "AZERBAIJAO": "AZE",
    "BAAMAS": "BHS",
    "BANGLADECHE": "BGD",
    "BARBADOS": "BRB",
    "BAREM": "BHR",
    "BELGICA": "BEL",
    "BELIZE": "BLZ",
    "BENIM": "BEN",
    "BERMUDAS": "BMU",
    "BIELORRUSSIA": "BLR",
    "BOLIVIA": "BOL",
    "BOSNIA E HERZEGOVINA": "BIH",
    "BOTSUANA": "BWA",
    "BRASIL": "BRA",
    "BRUNEI": "BRN",
    "BULGARIA": "BGR",
    "BURQUINA FASO": "BFA",
    "BURUNDI": "BDI",
    "BUTAO": "BTN",
    "CABO VERDE": "CPV",
    "CAMAROES": "CMR",
    "CAMBOJA": "KHM",
    "CANADA": "CAN",
    "CATAR": "QAT",
    "CAZAQUISTAO": "KAZ",
    "CHADE": "TCD",
    "CHEQUIA": "CZE",
    "CHILE": "CHL",
    "CHINA": "CHN",
    "CHIPRE": "CYP",
    "CIDADE DO VATICANO": "VAT",
    "COLOMBIA": "COL",
    "COMORES": "COM",
    "CONGO BRAZZAVILLE": "COG",
    "CONGO KINSHASA": "COD",
    "COREIA DO NORTE": "PRK",
    "COREIA DO SUL": "KOR",
    "COSTA RICA": "CRI",
    "COTE D IVOIRE COSTA DO MARFIM": "CIV",
    "CROACIA": "HRV",
    "CUBA": "CUB",
    "CURACAU": "CUW",
    "DINAMARCA": "DNK",
    "DOMINICA": "DMA",
    "EGITO": "EGY",
    "EMIRADOS ARABES UNIDOS": "ARE",
    "EQUADOR": "ECU",
    "ERITREIA": "ERI",
    "ESLOVAQUIA": "SVK",
    "ESLOVENIA": "SVN",
    "ESPANHA": "ESP",
    "ESSUATINI": "SWZ",
    "ESTADOS UNIDOS": "USA",
    "ESTONIA": "EST",
    "ETIOPIA": "ETH",
    "FIJI": "FJI",
    "FILIPINAS": "PHL",
    "FINLANDIA": "FIN",
    "FRANCA": "FRA",
    "GABAO": "GAB",
    "GAMBIA": "GMB",
    "GANA": "GHA",
    "GEORGIA": "GEO",
    "GIBRALTAR": "GIB",
    "GRANADA": "GRD",
    "GRECIA": "GRC",
    "GRONELANDIA": "GRL",
    "GUADALUPE": "GLP",
    "GUAME": "GUM",
    "GUATEMALA": "GTM",
    "GUERNESEY": "GGY",
    "GUIANA": "GUY",
    "GUIANA FRANCESA": "GUF",
    "GUINE": "GIN",
    "GUINE BISSAU": "GNB",
    "GUINE EQUATORIAL": "GNQ",
    "HAITI": "HTI",
    "HONDURAS": "HND",
    "HONG KONG RAE DA CHINA": "HKG",
    "HUNGRIA": "HUN",
    "IEMEN": "YEM",
    "ILHA BOUVET": "BVT",
    "ILHA DE MAN": "IMN",
    "ILHA DO NATAL": "CXR",
    "ILHA NORFOLK": "NFK",
    "ILHAS CAIMAO": "CYM",
    "ILHAS COOK": "COK",
    "ILHAS DOS COCOS KEELING": "CCK",
    "ILHAS FALKLAND": "FLK",
    "ILHAS FAROE": "FRO",
    "ILHAS GEORGIA DO SUL E SANDWICH DO SUL": "SGS",
    "ILHAS HEARD E MCDONALD": "HMD",
    "ILHAS MARIANAS DO NORTE": "MNP",
    "ILHAS MENORES AFASTADAS DOS EUA": "UMI",
    "ILHAS PITCAIRN": "PCN",
    "ILHAS SALOMAO": "SLB",
    "ILHAS TURCAS E CAICOS": "TCA",
    "ILHAS VIRGENS BRITANICAS": "VGB",
    "ILHAS VIRGENS DOS EUA": "VIR",
    "INDIA": "IND",
    "INDONESIA": "IDN",
    "IRAO": "IRN",
    "IRAQUE": "IRQ",
    "IRLANDA": "IRL",
    "ISLANDIA": "ISL",
    "ISRAEL": "ISR",
    "ITALIA": "ITA",
    "JAMAICA": "JAM",
    "JAPAO": "JPN",
    "JERSEY": "JEY",
    "JIBUTI": "DJI",
    "JORDANIA": "JOR",
    "KOSOVO": "XKX",
    "KOWEIT": "KWT",
    "LAOS": "LAO",
    "LESOTO": "LSO",
    "LETONIA": "LVA",
    "LIBANO": "LBN",
    "LIBERIA": "LBR",
    "LIBIA": "LBY",
    "LISTENSTAINE": "LIE",
    "LITUANIA": "LTU",
    "LUXEMBURGO": "LUX",
    "MACAU RAE DA CHINA": "MAC",
    "MACEDONIA DO NORTE": "MKD",
    "MADAGASCAR": "MDG",
    "MAIOTE": "MYT",
    "MALASIA": "MYS",
    "MALAUI": "MWI",
    "MALDIVAS": "MDV",
    "MALI": "MLI",
    "MALTA": "MLT",
    "MARROCOS": "MAR",
    "MARTINICA": "MTQ",
    "MAURICIA": "MUS",
    "MAURITANIA": "MRT",
    "MEXICO": "MEX",
    "MIANMAR BIRMANIA": "MMR",
    "MICRONESIA": "FSM",
    "MOCAMBIQUE": "MOZ",
    "MOLDAVIA": "MDA",
    "MONACO": "MCO",
    "MONGOLIA": "MNG",
    "MONSERRATE": "MSR",
    "MONTENEGRO": "MNE",
    "NAMIBIA": "NAM",
    "NAURU": "NRU",
    "NEPAL": "NPL",
    "NICARAGUA": "NIC",
    "NIGER": "NER",
    "NIGERIA": "NGA",
    "NIUE": "NIU",
    "NORUEGA": "NOR",
    "NOVA CALEDONIA": "NCL",
    "NOVA ZELANDIA": "NZL",
    "OMA": "OMN",
    "PAISES BAIXOS": "NLD",
    "PAISES BAIXOS CARIBENHOS": "BES",
    "PALAU": "PLW",
    "PANAMA": "PAN",
    "PAPUA NOVA GUINE": "PNG",
    "PAQUISTAO": "PAK",
    "PARAGUAI": "PRY",
    "PERU": "PER",
    "POLINESIA FRANCESA": "PYF",
    "POLONIA": "POL",
    "PORTO RICO": "PRI",
    "PORTUGAL": "PRT",
    "QUENIA": "KEN",
    "QUIRGUISTAO": "KGZ",
    "QUIRIBATI": "KIR",
    "REINO UNIDO": "GBR",
    "REPUBLICA CENTRO AFRICANA": "CAF",
    "REPUBLICA DOMINICANA": "DOM",
    "REUNIAO": "REU",
    "ROMENIA": "ROU",
    "RUANDA": "RWA",
    "RUSSIA": "RUS",
    "SALVADOR": "SLV",
    "SAMOA": "WSM",
    "SAMOA AMERICANA": "ASM",
    "SANTA HELENA": "SHN",
    "SANTA LUCIA": "LCA",
    "SAO BARTOLOMEU": "BLM",
    "SAO CRISTOVAO E NEVES": "KNA",
    "SAO MARINHO": "SMR",
    "SAO MARTINHO SAINT MARTIN": "MAF",
    "SAO MARTINHO SINT MAARTEN": "SXM",
    "SAO PEDRO E MIQUELAO": "SPM",
    "SAO TOME E PRINCIPE": "STP",
    "SAO VICENTE E GRANADINAS": "VCT",
    "SARA OCIDENTAL": "ESH",
    "SEICHELES": "SYC",
    "SENEGAL": "SEN",
    "SERRA LEOA": "SLE",
    "SERVIA": "SRB",
    "SINGAPURA": "SGP",
    "SIRIA": "SYR",
    "SOMALIA": "SOM",
    "SRI LANCA": "LKA",
    "SUDAO": "SDN",
    "SUDAO DO SUL": "SSD",
    "SUECIA": "SWE",
    "SUICA": "CHE",
    "SURINAME": "SUR",
    "SVALBARD E JAN MAYEN": "SJM",
    "TAILANDIA": "THA",
    "TAIWAN": "TWN",
    "TAJIQUISTAO": "TJK",
    "TANZANIA": "TZA",
    "TERRITORIO BRITANICO DO OCEANO INDICO": "IOT",
    "TERRITORIOS AUSTRAIS FRANCESES": "ATF",
    "TERRITORIOS PALESTINIANOS": "PSE",
    "TIMOR LESTE": "TLS",
    "TOGO": "TGO",
    "TONGA": "TON",
    "TOQUELAU": "TKL",
    "TRINDADE E TOBAGO": "TTO",
    "TUNISIA": "TUN",
    "TURQUEMENISTAO": "TKM",
    "TURQUIA": "TUR",
    "TUVALU": "TUV",
    "UCRANIA": "UKR",
    "UGANDA": "UGA",
    "URUGUAI": "URY",
    "USBEQUISTAO": "UZB",
    "VANUATU": "VUT",
    "VENEZUELA": "VEN",
    "VIETNAME": "VNM",
    "WALLIS E FUTUNA": "WLF",
    "ZAMBIA": "ZMB",
    "ZIMBABUE": "ZWE",
}

COUNTRY_NAME_TO_ICAO = {
    **COUNTRY_NAME_PT_TO_ICAO,
    "PORTUGAL": "PRT",
    "FRANCA": "FRA",
    "FRANCE": "FRA",
    "ESPANHA": "ESP",
    "ESPANA": "ESP",
    "SPAIN": "ESP",
    "REINO UNIDO": "GBR",
    "UNITED KINGDOM": "GBR",
    "GREAT BRITAIN": "GBR",
    "INGLATERRA": "GBR",
    "IRELAND": "IRL",
    "IRLANDA": "IRL",
    "ALEMANHA": "DEU",
    "GERMANY": "DEU",
    "DEUTSCHLAND": "DEU",
    "ITALIA": "ITA",
    "ITALY": "ITA",
    "PAISES BAIXOS": "NLD",
    "HOLANDA": "NLD",
    "NETHERLANDS": "NLD",
    "BELGICA": "BEL",
    "BELGIUM": "BEL",
    "SUICA": "CHE",
    "SWITZERLAND": "CHE",
    "AUSTRIA": "AUT",
    "LUXEMBURGO": "LUX",
    "LUXEMBOURG": "LUX",
    "ESTADOS UNIDOS": "USA",
    "ESTADOS UNIDOS DA AMERICA": "USA",
    "EUA": "USA",
    "UNITED STATES": "USA",
    "USA": "USA",
    "CANADA": "CAN",
    "BAHAMAS": "BHS",
    "BAHREIN": "BHR",
    "BAHRAIN": "BHR",
    "BANGLADESH": "BGD",
    "BOTSWANA": "BWA",
    "BRASIL": "BRA",
    "BRAZIL": "BRA",
    "BURKINA FASO": "BFA",
    "CASAQUISTAO": "KAZ",
    "REPUBLICA CHECA": "CZE",
    "REPUBLICA DEMOCRATICA DO CONGO": "COD",
    "COTE D IVOIRE": "CIV",
    "MEXICO": "MEX",
    "ANGOLA": "AGO",
    "HONG KONG": "HKG",
    "LIECHTENSTEIN": "LIE",
    "MACAU": "MAC",
    "ILHAS MAURICIAS": "MUS",
    "MOCAMBIQUE": "MOZ",
    "MOZAMBIQUE": "MOZ",
    "MYANMAR": "MMR",
    "CABO VERDE": "CPV",
    "CAPE VERDE": "CPV",
    "COSTA DO MARFIM": "CIV",
    "EL SALVADOR": "SLV",
    "ESWATINI": "SWZ",
    "SAARA OCIDENTAL": "ESH",
    "SAN MARINO": "SMR",
    "TRINIDAD E TOBAGO": "TTO",
    "UK": "GBR",
    "VIETNAM": "VNM",
}

DOC_TYPE_TO_SIBA = {
    "ID_NACIONAL": "B",
    "ID": "B",
    "CC": "B",
    "BI": "B",
    "CARTAO DE CIDADAO": "B",
    "CARTAO CIDADAO": "B",
    "DOCUMENTO DE IDENTIFICACAO NACIONAL": "B",
    "DOC IDENTIFICACAO NACIONAL": "B",
    "DOC IDENTIFICACAO": "B",
    "NATIONAL IDENTITY DOCUMENT": "B",
    "NATIONAL ID": "B",
    "PASSAPORTE": "P",
    "PASSPORT": "P",
    "OUTRO": "O",
    "OTHER": "O",
    "AUTRE": "O",
}


def _normalize_key(value: Any) -> str:
    text = str(value or "").strip()
    if not text:
        return ""
    text = unicodedata.normalize("NFD", text)
    text = "".join(ch for ch in text if unicodedata.category(ch) != "Mn")
    text = re.sub(r"[^A-Za-z0-9]+", " ", text)
    return re.sub(r"\s+", " ", text).strip().upper()


def country_to_icao(value: Any) -> str:
    key = _normalize_key(value)
    if not key:
        return ""
    compact = key.replace(" ", "")
    if len(compact) == 3 and compact in ICAO_CODES:
        return compact
    if len(compact) == 2 and compact in ISO2_TO_ICAO:
        return ISO2_TO_ICAO[compact]
    return COUNTRY_NAME_TO_ICAO.get(key, "")


def doc_type_to_siba(value: Any) -> str:
    key = _normalize_key(value)
    if not key:
        return ""
    if key in {"P", "B", "O"}:
        return key
    compact_key = key.replace(" ", "_")
    return DOC_TYPE_TO_SIBA.get(key) or DOC_TYPE_TO_SIBA.get(compact_key, "O")
