"""Criar tabelas MENU e CAMPOS

Revision ID: 7ee6cc8b38ff
Revises: 
Create Date: 2025-06-21 18:21:43.424229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '7ee6cc8b38ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MENU',
    sa.Column('menustamp', sa.String(length=25), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('tabela', sa.String(length=18), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('menustamp')
    )
    op.create_table('CAMPOS',
    sa.Column('camposstamp', sa.String(length=25), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('nmcampo', sa.String(length=25), nullable=False),
    sa.Column('descricao', sa.String(length=60), nullable=False),
    sa.Column('tipo', sa.String(length=18), nullable=False),
    sa.Column('tabela', sa.String(length=18), nullable=False),
    sa.Column('lista', sa.Boolean(), nullable=False),
    sa.Column('filtro', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('camposstamp')
    )
    op.drop_table('SP')
    op.drop_table('IC')
    op.drop_table('RS')
    op.drop_table('PR')
    op.drop_table('LP')
    op.drop_table('MN')
    op.drop_table('TP')
    op.drop_table('ET')
    op.drop_table('AL')
    op.drop_table('Emails')
    op.drop_table('FS')
    op.drop_table('ALQ')
    op.drop_table('ND')
    op.drop_table('EP')
    op.drop_table('US')
    op.drop_table('sysdiagrams')
    op.drop_table('ALK')
    op.drop_table('EQ')
    op.drop_table('PESQUISAS')
    op.drop_table('bkp_al')
    op.drop_table('BQ')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BQ',
    sa.Column('BQSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('ALOJAMENTO', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('NMAIRBNB', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('DATA', sa.DATE(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('TRATADO', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False)
    )
    op.create_table('bkp_al',
    sa.Column('ALSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('NOME', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('MORADA', sa.VARCHAR(length=120, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('LOCAL', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('CODPOST', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('EMPRESA', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('PROPRIETARIO', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('LICENCA', sa.VARCHAR(length=18, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('TIPOLOGIA', sa.VARCHAR(length=18, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('LOTACAO', sa.NUMERIC(precision=12, scale=0), autoincrement=False, nullable=False),
    sa.Column('NOMETG', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('LINK', sa.VARCHAR(length=200, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('AVALIACAO', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False)
    )
    op.create_table('PESQUISAS',
    sa.Column('PESQUISASSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text('(left(newid(),(25)))'), autoincrement=False, nullable=False),
    sa.Column('CCUSTO', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('DATA', sa.DATE(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('DTPESQUISA', sa.DATE(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('NOITES', sa.NCHAR(length=10, collation='Latin1_General_CI_AS'), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('HOSPEDES', sa.NUMERIC(precision=18, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('PAGINA', sa.NUMERIC(precision=18, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('POSICAO', sa.NUMERIC(precision=18, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('NMAIRBNB', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False)
    )
    op.create_table('EQ',
    sa.Column('EQSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('NOME', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('EMPRESA', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('CUSTODIA', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('icone', sa.VARCHAR(length=200, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('COR', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False)
    )
    op.create_table('ALK',
    sa.Column('ALKSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text('(left(newid(),(25)))'), autoincrement=False, nullable=False),
    sa.Column('ALSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('ITEM', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False)
    )
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B6142744663'))
    )
    op.create_table('US',
    sa.Column('USSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text('(left(newid(),(25)))'), autoincrement=False, nullable=False),
    sa.Column('USERNAME', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('NOME', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('EMAIL', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('TELEFONE', sa.VARCHAR(length=18, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('ACESSO', sa.VARCHAR(length=18, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('EQUIPA', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False)
    )
    op.create_table('EP',
    sa.Column('EPSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text('(left(newid(),(25)))'), autoincrement=False, nullable=False),
    sa.Column('NOME', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('MORADA', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('LOCAL', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('CODPOST', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('NIF', sa.VARCHAR(length=18, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False)
    )
    op.create_table('ND',
    sa.Column('NDSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text('(left(newid(),(25)))'), autoincrement=False, nullable=False),
    sa.Column('EQUIPA', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('DATA', sa.DATE(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('TIPO', sa.VARCHAR(length=18, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False)
    )
    op.create_table('ALQ',
    sa.Column('ALQSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text('(left(newid(),(25)))'), autoincrement=False, nullable=False),
    sa.Column('ALSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('QUARTO', sa.VARCHAR(length=18, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('CAMASOL', sa.NUMERIC(precision=12, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('CAMACASAL', sa.NUMERIC(precision=12, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('CAMAQS', sa.NUMERIC(precision=12, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('CAMAKS', sa.NUMERIC(precision=12, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('SOFA1P', sa.NUMERIC(precision=12, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('SOFA2P', sa.NUMERIC(precision=12, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False)
    )
    op.create_table('FS',
    sa.Column('FSSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text('(left(newid(),(25)))'), autoincrement=False, nullable=False),
    sa.Column('ALOJAMENTO', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('DATA', sa.DATE(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('USERNAME', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('ITEM', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('URGENTE', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('TRATADO', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('TRATADOPOR', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('DTTRATADO', sa.DATE(), server_default=sa.text("('19000101')"), autoincrement=False, nullable=False)
    )
    op.create_table('Emails',
    sa.Column('EmailID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Sender', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Recipient', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Subject', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Body', sa.NVARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ReceivedDate', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('Attachments', sa.NVARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('EmailUID', sa.NVARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('CCUSTO', sa.NVARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('DATAINI', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('DATAFIM', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('TOTAL', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('NOME', sa.NVARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PAIS', sa.NVARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('OCUPACAO', sa.NVARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('RESERVA', sa.NVARCHAR(length=50, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ESTADIA', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('LIMPEZA', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('CANCELADA', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.Column('DTCANCEL', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('DIASCANCEL', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ADULTOS', sa.INTEGER(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.Column('CRIANCAS', sa.INTEGER(), server_default=sa.text('((0))'), autoincrement=False, nullable=True),
    sa.Column('HORAINI', sa.VARCHAR(length=5, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('HORAFIM', sa.VARCHAR(length=5, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('tratado', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('EmailID', name=op.f('PK__Emails__7ED91AEFFFBBAC1E'))
    )
    op.create_table('AL',
    sa.Column('ALSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text('(left(newid(),(25)))'), autoincrement=False, nullable=False),
    sa.Column('NOME', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('MORADA', sa.VARCHAR(length=120, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('LOCAL', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('CODPOST', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('EMPRESA', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('PROPRIETARIO', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('LICENCA', sa.VARCHAR(length=18, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('TIPOLOGIA', sa.VARCHAR(length=18, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('LOTACAO', sa.NUMERIC(precision=12, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('NOMETG', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('LINK', sa.VARCHAR(length=200, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('AVALIACAO', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('LAT', sa.VARCHAR(length=12, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('LON', sa.VARCHAR(length=12, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('ZONA', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('IDPLABS', sa.INTEGER(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('NMAIRBNB', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('CCUSTO', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False)
    )
    op.create_table('ET',
    sa.Column('ETSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text('(left(newid(),(25)))'), autoincrement=False, nullable=False),
    sa.Column('LPSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('TRATADO', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False)
    )
    op.create_table('TP',
    sa.Column('TPSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text('(left(newid(),(25)))'), autoincrement=False, nullable=False),
    sa.Column('EQUIPA', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('TIPOLOGIA', sa.VARCHAR(length=18, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('PCUSTO', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('((0))'), autoincrement=False, nullable=False)
    )
    op.create_table('MN',
    sa.Column('MNSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text('(left(newid(),(25)))'), autoincrement=False, nullable=False),
    sa.Column('ALOJAMENTO', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('DATA', sa.DATE(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('NOME', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('INCIDENCIA', sa.NUMERIC(precision=12, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('TRATADO', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('DTTRATADO', sa.NCHAR(length=10, collation='Latin1_General_CI_AS'), server_default=sa.text("('19000101')"), autoincrement=False, nullable=False)
    )
    op.create_table('LP',
    sa.Column('LPSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text('(left(newid(),(25)))'), autoincrement=False, nullable=False),
    sa.Column('ALOJAMENTO', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('DATA', sa.DATE(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('HORA', sa.VARCHAR(length=5, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('EQUIPA', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('TERMINADA', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('CUSTO', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('HOSPEDES', sa.NUMERIC(precision=3, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('NOITES', sa.NUMERIC(precision=3, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('OBS', sa.VARCHAR(length=48, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False)
    )
    op.create_table('PR',
    sa.Column('PRSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text('(left(newid(),(25)))'), autoincrement=False, nullable=False),
    sa.Column('NOME', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('TELEFONE', sa.VARCHAR(length=18, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('NIF', sa.VARCHAR(length=18, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False)
    )
    op.create_table('RS',
    sa.Column('RSSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text('(left(newid(),(25)))'), autoincrement=False, nullable=False),
    sa.Column('ALOJAMENTO', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('RDATA', sa.DATE(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('ORIGEM', sa.VARCHAR(length=50, collation='Latin1_General_CI_AS'), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('RESERVA', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('DATAIN', sa.DATE(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('DATAOUT', sa.DATE(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('HORAIN', sa.VARCHAR(length=5, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('HORAOUT', sa.VARCHAR(length=5, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('NOITES', sa.NUMERIC(precision=12, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('NOME', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('PAIS', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('ADULTOS', sa.NUMERIC(precision=12, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('CRIANCAS', sa.NUMERIC(precision=12, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('BEBES', sa.NUMERIC(precision=12, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('ESTADIA', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('LIMPEZA', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('COMISSAO', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('READY', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('ENTROU', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('SAIU', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('ALERTA', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('OBS', sa.VARCHAR(length=250, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('CANCELADA', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('DTCANCEL', sa.DATE(), server_default=sa.text("('1900-01-01')"), autoincrement=False, nullable=False),
    sa.Column('DIASCANCEL', sa.INTEGER(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('NOTIF', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('NOTIF2', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False)
    )
    op.create_table('IC',
    sa.Column('ICSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text('(left(newid(),(25)))'), autoincrement=False, nullable=False),
    sa.Column('ALOJAMENTO', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('RESERVA', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('DATA', sa.DATE(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('TIPO', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('OBS', sa.VARCHAR(length=250, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('URGENTE', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('TRATADO', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('TRATADOPOR', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('DTTRATADO', sa.DATE(), server_default=sa.text("('19000101')"), autoincrement=False, nullable=False),
    sa.Column('INCIDENCIA', sa.NUMERIC(precision=12, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False)
    )
    op.create_table('SP',
    sa.Column('SPSTAMP', sa.VARCHAR(length=25, collation='Latin1_General_CI_AS'), server_default=sa.text('(left(newid(),(25)))'), autoincrement=False, nullable=False),
    sa.Column('ALOJAMENTO', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('SUPERVISAO', sa.NUMERIC(precision=12, scale=0), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('DATA', sa.DATE(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('NOME', sa.VARCHAR(length=60, collation='Latin1_General_CI_AS'), server_default=sa.text("('')"), autoincrement=False, nullable=False),
    sa.Column('TRATADO', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False)
    )
    op.drop_table('CAMPOS')
    op.drop_table('MENU')
    # ### end Alembic commands ###
